version: '3'

services:
  web: &web
    build:
      context: .
    ports:
      - "3001:3000"
    volumes:
      - .:/app:cached
      - bundle:/usr/local/bundle
      - node_modules:/app/node_modules
      - packs:/app/public/packs
      - rails_cache:/app/tmp/cache
      - storage:/app/storage
    environment:
      - WEBPACKER_DEV_SERVER_HOST=webpacker
    env_file:
      - .env/development/database
      - .env/development/web
    tmpfs:
      - /tmp
      - /app/tmp/pids
    depends_on:
      database:
        condition: service_healthy

  database:
    image: mariadb:10
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - .env/development/database
    healthcheck:
      test: mysqladmin ping
      interval: 2s
    volumes:
      - db_data:/var/lib/mysql

  webpacker:
    <<: *web
    command: ./bin/webpacker-dev-server
    environment:
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
    env_file:
      - .env/development/database
      - .env/development/web
    ports:
      - "3035:3035"
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
      - node_modules:/app/node_modules
      - packs:/app/public/packs

volumes:
  bundle:
  db_data:
  node_modules:
  packs:
  rails_cache:
  storage:
