---
- key: system_overview
  output_elements:
  - waterfall_future_energy_net_imports
  - source_of_electricity_production
  - hourly_flexibility_electricity
  - mekko_of_hydrogen_network
  - source_of_electricity_in_p2g
  - sankey_heat_networks
  - heat_network_storage_ht
  - heat_network_storage_mt
  - heat_network_storage_lt
  - merit_order_hourly_supply
  - source_of_electricity_production
  - dynamic_demand_curve
  - merit_order
  - flexibility_hourly_p2p_storage
  - storage_options
  - merit_order_table
  dependent_on: ''
