---
http_interactions:
- request:
    method: post
    uri: https://beta-engine.energytransitionmodel.com/api/v3/scenarios
    body:
      encoding: UTF-8
      string: '{"scenario":{"source":"ETM","area_code":"nl","end_year":2050}}'
    headers:
      User-Agent:
      - Faraday v2.7.3
      Content-Type:
      - application/json
      Authorization:
      - Bearer access_SQu9G7LYxXJ3S9Hv
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Server:
      - nginx/1.21.3
      Date:
      - Mon, 15 May 2023 10:08:09 GMT
      Content-Type:
      - application/json; charset=utf-8
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
      X-Frame-Options:
      - SAMEORIGIN
      X-Xss-Protection:
      - '0'
      X-Content-Type-Options:
      - nosniff
      X-Download-Options:
      - noopen
      X-Permitted-Cross-Domain-Policies:
      - none
      Referrer-Policy:
      - strict-origin-when-cross-origin
      Vary:
      - Accept, Origin
      Etag:
      - W/"843119c652d87c91656da4bbb3159beb"
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - e4ab2486-b136-4297-a2de-a9b1d560c7a3
      X-Runtime:
      - '1.736149'
    body:
      encoding: UTF-8
      string: '{"id":2255690,"created_at":"2023-05-15T10:08:09.000Z","updated_at":"2023-05-15T10:08:09.000Z","user_values":{},"end_year":2050,"keep_compatible":false,"private":false,"area_code":"nl","source":"ETM","balanced_values":{},"metadata":{},"start_year":2015,"owner":null,"active_couplings":[],"inactive_couplings":[],"scaling":null,"template":null,"url":"https://beta-engine.energytransitionmodel.com/api/v3/scenarios/2255690"}'
  recorded_at: Mon, 15 May 2023 10:08:09 GMT
recorded_with: VCR 6.0.0
