---
- label: co2_emitted
  color: "#49A5F8"
  order_by: 100
  group: steam_methane_reforming
  is_target_line: false
  gquery: co2_intensity_of_hydrogen_production_steam_methane_reformer
  output_element_key: co2_intensity_of_hydrogen_production
  key: co2_emission_steam_methane_reforming_co2_intensity_of_hydrogen_production
- label: co2_captured
  color: "#E86C33"
  order_by: 110
  group: steam_methane_reforming
  is_target_line: false
  gquery: captured_co2_intensity_of_hydrogen_production_steam_methane_reformer
  output_element_key: co2_intensity_of_hydrogen_production
  key: captured_co2_steam_methane_reforming_co2_intensity_of_hydrogen_production
- label: co2_threshold
  color: "#AB47BC"
  order_by: 115
  group: steam_methane_reforming
  is_target_line: true
  gquery: co2_intensity_european_commission_threshold
  output_element_key: co2_intensity_of_hydrogen_production
  key: co2_intensity_of_hydrogen_production_smr_co2_intensity_of_hydrogen_production

- label: co2_emitted
  color: "#49A5F8"
  order_by: 120
  group: autothermal_reforming
  is_target_line: false
  gquery: co2_intensity_of_hydrogen_production_autothermal_reformer
  output_element_key: co2_intensity_of_hydrogen_production
  key: co2_emission_autothermal_reforming_co2_intensity_of_hydrogen_production
- label: co2_captured
  color: "#E86C33"
  order_by: 130
  group: autothermal_reforming
  is_target_line: false
  gquery: captured_co2_intensity_of_hydrogen_production_autothermal_reformer
  output_element_key: co2_intensity_of_hydrogen_production
  key: captured_co2_autothermal_reforming_co2_intensity_of_hydrogen_production
- label: co2_threshold
  color: "#AB47BC"
  order_by: 135
  group: autothermal_reforming
  is_target_line: true
  gquery: co2_intensity_european_commission_threshold
  output_element_key: co2_intensity_of_hydrogen_production
  key: co2_intensity_of_hydrogen_production_atr_co2_intensity_of_hydrogen_production

- label: co2_emitted
  color: "#49A5F8"
  order_by: 200
  group: power_to_gas
  is_target_line: false
  gquery: co2_intensity_of_hydrogen_production_p2g_hourly_electricity_input
  output_element_key: co2_intensity_of_hydrogen_production
  key: co2_emission_power_to_gas_co2_intensity_of_hydrogen_production
- label: co2_captured
  color: "#E86C33"
  order_by: 210
  group: power_to_gas
  is_target_line: false
  gquery: captured_co2_intensity_of_hydrogen_production_p2g_hourly_electricity_input
  output_element_key: co2_intensity_of_hydrogen_production
  key: captured_co2_emission_power_to_gas_co2_intensity_of_hydrogen_production
- label: co2_threshold
  color: "#AB47BC"
  order_by: 215
  group: power_to_gas
  is_target_line: true
  gquery: co2_intensity_european_commission_threshold
  output_element_key: co2_intensity_of_hydrogen_production
  key: co2_intensity_of_hydrogen_production_p2g_co2_intensity_of_hydrogen_production

- label: co2_emitted
  color: "#49A5F8"
  order_by: 300
  group: biomass_gasification
  is_target_line: false
  gquery: co2_intensity_of_hydrogen_production_biomass_gasification
  output_element_key: co2_intensity_of_hydrogen_production
  key: co2_emission_biomass_gasification_co2_intensity_of_hydrogen_production
- label: co2_captured
  color: "#E86C33"
  order_by: 310
  group: biomass_gasification
  is_target_line: false
  gquery: captured_co2_intensity_of_hydrogen_production_biomass_gasification
  output_element_key: co2_intensity_of_hydrogen_production
  key: captured_co2_emission_biomass_gasification_co2_intensity_of_hydrogen_production
- label: co2_threshold
  color: "#AB47BC"
  order_by: 315
  group: biomass_gasification
  is_target_line: true
  gquery: co2_intensity_european_commission_threshold
  output_element_key: co2_intensity_of_hydrogen_production
  key: co2_intensity_of_hydrogen_production_biomass_co2_intensity_of_hydrogen_production

- label: co2_emitted
  color: "#49A5F8"
  order_by: 150
  group: ammonia_reforming
  is_target_line: false
  gquery: co2_intensity_of_hydrogen_production_ammonia_reformer
  output_element_key: co2_intensity_of_hydrogen_production
  key: co2_intensity_of_hydrogen_production_ammonia_reformer_co2_intensity_of_hydrogen_production
- label: co2_threshold
  color: "#AB47BC"
  order_by: 155
  group: ammonia_reforming
  is_target_line: true
  gquery: co2_intensity_european_commission_threshold
  output_element_key: co2_intensity_of_hydrogen_production
  key: co2_intensity_of_hydrogen_production_ammonia_co2_intensity_of_hydrogen_production
  

- label: co2_emitted
  color: "#49A5F8"
  order_by: 170
  group: lohc_reforming
  is_target_line: false
  gquery: co2_intensity_of_hydrogen_production_lohc_reformer
  output_element_key: co2_intensity_of_hydrogen_production
  key: co2_intensity_of_hydrogen_production_lohc_reformer_co2_intensity_of_hydrogen_production
- label: co2_threshold
  color: "#AB47BC"
  order_by: 175
  group: lohc_reforming
  is_target_line: true
  gquery: co2_intensity_european_commission_threshold
  output_element_key: co2_intensity_of_hydrogen_production
  key: co2_intensity_of_hydrogen_production_lohc_co2_intensity_of_hydrogen_production 
  
- label: co2_emitted
  color: "#49A5F8"
  order_by: 190
  group: liguid_hydrogen_regasification
  is_target_line: false
  gquery: co2_intensity_of_hydrogen_production_liquid_hydrogen_regasifier
  output_element_key: co2_intensity_of_hydrogen_production
  key: co2_intensity_of_hydrogen_production_liquid_hydrogen_regasifier_co2_intensity_of_hydrogen_production
- label: co2_threshold
  color: "#AB47BC"
  order_by: 195
  group: liguid_hydrogen_regasification
  is_target_line: true
  gquery: co2_intensity_european_commission_threshold
  output_element_key: co2_intensity_of_hydrogen_production
  key: co2_intensity_of_hydrogen_production_liquid_hydrogen_co2_intensity_of_hydrogen_production   


- label: co2_emitted
  color: "#49A5F8"
  order_by: 500
  group: import
  is_target_line: false
  gquery: co2_intensity_of_hydrogen_production_import
  output_element_key: co2_intensity_of_hydrogen_production
  key: co2_emission_import_co2_intensity_of_hydrogen_production
- label: co2_threshold
  color: "#AB47BC"
  order_by: 505
  group: import
  is_target_line: true
  gquery: co2_intensity_european_commission_threshold
  output_element_key: co2_intensity_of_hydrogen_production
  key: co2_intensity_of_hydrogen_production_import_co2_intensity_of_hydrogen_production
