---
- label: costs_building_and_installations
  unit: euro
  color: "#002B42"
  order_by: 1
  group:
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: costs_building_and_installations
  is_1990:
  dependent_on:
  output_element_key: costs_overview
  key: costs_building_and_installations_costs_overview
- label: costs_carriers
  unit: euro
  color: "#619AB7"
  order_by: 2
  group:
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: costs_carriers
  is_1990:
  dependent_on:
  output_element_key: costs_overview
  key: costs_carriers_costs_overview
- label: costs_production
  unit: euro
  color: "#C5D75F"
  order_by: 3
  group:
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: costs_production
  is_1990:
  dependent_on:
  output_element_key: costs_overview
  key: costs_production_costs_overview
- label: costs_storage_and_conversion
  unit: euro
  color: "#CAB39E"
  order_by: 4
  group:
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: costs_storage_and_conversion
  is_1990:
  dependent_on:
  output_element_key: costs_overview
  key: costs_storage_and_conversion_costs_overview
- label: costs_infrastructure
  unit: euro
  color: "#702283"
  order_by: 5
  group:
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: costs_infrastructure
  is_1990:
  dependent_on:
  output_element_key: costs_overview
  key: costs_infrastructure_costs_overview
- label: costs_co2_ccus
  unit: euro
  color: "#fc653d"
  order_by: 7
  group:
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: costs_co2_ccus
  is_1990:
  dependent_on:
  output_element_key: costs_overview
  key: costs_co2_ccus_costs_overview
- label: costs_co2_emissions_costs
  unit: euro
  color: "#FCC43D"
  order_by: 8
  group:
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: costs_co2_energy_graph_co2_emissions_costs
  is_1990:
  dependent_on:
  output_element_key: costs_overview
  key: costs_co2_emissions_costs_costs_overview
