---
- label: coal_final_demand
  color: "#333333"
  order_by: 100
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: coal_demand_in_industry_steel
  is_1990:
  dependent_on:
  output_element_key: demand_in_industry_steel
  key: coal_demand_in_industry_steel
- label: coal_transformation_losses
  color: "#696969"
  order_by: 105
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: coal_transformation_losses_in_industry_steel
  is_1990:
  dependent_on:
  output_element_key: demand_in_industry_steel
  key: coal_transformation_losses_in_industry_steel
- label: coal_gas_final_demand
  color: "#686de0"
  order_by: 110
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: coal_gas_demand_in_industry_steel
  is_1990:
  dependent_on:
  output_element_key: demand_in_industry_steel
  key: coal_gas_demand_in_industry_steel
- label: cokes_final_demand
  color: "#5f27cd"
  order_by: 120
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: cokes_demand_in_industry_steel
  is_1990:
  dependent_on:
  output_element_key: demand_in_industry_steel
  key: cokes_demand_in_industry_steel
- label: network_gas_final_demand
  color: "#CCCCCC"
  order_by: 130
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: network_gas_demand_in_industry_steel
  is_1990:
  dependent_on:
  output_element_key: demand_in_industry_steel
  key: network_gas_demand_in_industry_steel
- label: crude_oil_final_demand
  color: "#854321"
  order_by: 140
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: crude_oil_demand_in_industry_steel
  is_1990:
  dependent_on:
  output_element_key: demand_in_industry_steel
  key: crude_oil_demand_in_industry_steel
- label: electricity_final_demand
  color: "#4169E1"
  order_by: 150
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: electricity_demand_in_industry_steel
  is_1990:
  dependent_on:
  output_element_key: demand_in_industry_steel
  key: electricity_demand_in_industry_steel
- label: heat_final_demand
  color: "#8B0000"
  order_by: 160
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: steam_hot_water_demand_in_industry_steel
  is_1990:
  dependent_on:
  output_element_key: demand_in_industry_steel
  key: heat_demand_in_industry_steel
- label: hydrogen_final_demand
  color: "#87CEEB"
  order_by: 170
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: hydrogen_demand_in_industry_steel
  is_1990:
  dependent_on:
  output_element_key: demand_in_industry_steel
  key: hydrogen_demand_in_industry_steel
- label: biomass_final_demand
  color: "#5D7929"
  order_by: 180
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: wood_pellets_demand_in_industry_steel
  is_1990:
  dependent_on:
  output_element_key: demand_in_industry_steel
  key: biomass_demand_in_industry_steel
