---
- label: collective_heat_demand
  color: "#ffb300"
  order_by: 100
  group: heat_from_surface_water
  is_target_line: false
  gquery: heat_from_aquathermal_surface_water_collective
  output_element_key: heat_aquathermal_demand
  key: heat_aquathermal_demand_surface_water_collective
- label: individual_heat_demand
  color: "#e07033"
  order_by: 105
  group: heat_from_surface_water
  is_target_line: false
  gquery: heat_from_aquathermal_surface_water_individual
  output_element_key: heat_aquathermal_demand
  key: heat_aquathermal_demand_surface_water_individual
- label: technical_thermal_potential
  color: "#4169e1"
  order_by: 110
  group: heat_from_surface_water
  dependent_on: has_aquathermal_potential_for_surface_water
  is_target_line: true
  gquery: heat_aquathermal_potential_from_surface_water
  output_element_key: heat_aquathermal_demand
  key: heat_aquathermal_demand_surface_water_potential

- label: collective_heat_demand
  color: "#ffb300"
  order_by: 200
  group: heat_from_waste_water
  is_target_line: false
  gquery: heat_from_aquathermal_waste_water_collective
  output_element_key: heat_aquathermal_demand
  key: heat_aquathermal_demand_waste_water_collective
- label: individual_heat_demand
  color: "#e07033"
  order_by: 205
  group: heat_from_waste_water
  is_target_line: false
  gquery: heat_from_aquathermal_waste_water_individual
  output_element_key: heat_aquathermal_demand
  key: heat_aquathermal_demand_waste_water_individual
- label: technical_thermal_potential
  color: "#4169e1"
  order_by: 210
  group: heat_from_waste_water
  dependent_on: has_aquathermal_potential_for_waste_water
  is_target_line: true
  gquery: heat_aquathermal_potential_from_waste_water
  output_element_key: heat_aquathermal_demand
  key: heat_aquathermal_demand_waste_water_potential

- label: collective_heat_demand
  color: "#ffb300"
  order_by: 300
  group: heat_from_drink_water
  is_target_line: false
  gquery: heat_from_aquathermal_drink_water_collective
  output_element_key: heat_aquathermal_demand
  key: heat_aquathermal_demand_drink_water_collective
- label: individual_heat_demand
  color: "#e07033"
  order_by: 305
  group: heat_from_drink_water
  is_target_line: false
  gquery: heat_from_aquathermal_drink_water_individual
  output_element_key: heat_aquathermal_demand
  key: heat_aquathermal_demand_drink_water_individual
- label: technical_thermal_potential
  color: "#4169e1"
  order_by: 310
  group: heat_from_drink_water
  dependent_on: has_aquathermal_potential_for_drink_water
  is_target_line: true
  gquery: heat_aquathermal_potential_from_drink_water
  output_element_key: heat_aquathermal_demand
  key: heat_aquathermal_demand_drink_water_potential
