---
- label: heat_network_demand
  color: "#FF0000"
  order_by: 100
  group:
  show_at_first:
  is_target_line: true
  target_line_position:
  gquery: heat_network_lt_demand_curve
  is_1990:
  dependent_on:
  output_element_key: heat_network_production_lt
  key: heat_network_demand_heat_network_production_lt

- label: energy_heat_network_residual_heat_out
  color: "#00008B"
  order_by: 200
  group:
  show_at_first:
  is_target_line:
  target_line_position:
  gquery: energy_heat_production_lt_residual_heat_steam_hot_water_output_curve
  is_1990:
  dependent_on:
  output_element_key: heat_network_production_lt
  key: energy_heat_network_residual_heat_out_heat_network_production_lt
- label: energy_heat_import_steam_hot_water_steam_hot_water_output_curve
  color: "#FF8C8C"
  order_by: 205
  group:
  show_at_first: false
  is_target_line: false
  target_line_position:
  gquery: energy_heat_import_steam_hot_water_lt_steam_hot_water_output_curve
  is_1990: false
  dependent_on:
  output_element_key: heat_network_production_lt
  key: energy_heat_import_steam_hot_water_lt_steam_hot_water_output_curve_heat_network_production
- label: energy_heat_well_shallow_geothermal_steam_hot_water_output_curve
  color: "#FFC04F"
  order_by: 210
  group:
  show_at_first: false
  is_target_line: false
  target_line_position:
  gquery: energy_heat_well_shallow_geothermal_lt_steam_hot_water_output_curve
  is_1990: false
  dependent_on:
  output_element_key: heat_network_production_lt
  key: energy_heat_well_shallow_geothermal_lt_steam_hot_water_output_curve_heat_network_production
- label: energy_heat_solar_thermal_steam_hot_water_output_curve
  color: "#FFD700"
  order_by: 215
  group:
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: energy_heat_solar_thermal_lt_steam_hot_water_output_curve
  is_1990:
  dependent_on:
  output_element_key: heat_network_production_lt
  key: energy_heat_solar_thermal_lt_steam_hot_water_output_curve_heat_network_production

- label: energy_heat_burner_hydrogen_steam_hot_water_output_curve
  color: "#87CEEB"
  order_by: 400
  group:
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: energy_heat_burner_hydrogen_lt_steam_hot_water_output_curve
  is_1990:
  dependent_on:
  output_element_key: heat_network_production_lt
  key: energy_heat_burner_hydrogen_lt_steam_hot_water_output_curve_heat_network_production
- label: energy_heat_heatpump_water_water_electricity_steam_hot_water_output_curve
  color: "#ADD8E6"
  order_by: 405
  group:
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: energy_heat_heatpump_water_water_electricity_lt_steam_hot_water_output_curve
  is_1990:
  dependent_on:
  output_element_key: heat_network_production_lt
  key: energy_heat_heatpump_water_water_electricity_lt_steam_hot_water_output_curve_heat_network_production
- label: energy_heat_heatpump_surface_water_water_ts_electricity_steam_hot_water_output_curve
  color: "#87e3eb"
  order_by: 410
  group:
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: energy_heat_heatpump_surface_water_water_ts_lt_electricity_steam_hot_water_output_curve
  is_1990:
  dependent_on:
  output_element_key: heat_network_production_lt
  key: energy_heat_heatpump_surface_water_water_ts_lt_electricity_steam_hot_water_output_curve_heat_network_production
- label: energy_heat_heatpump_waste_water_water_ts_electricity_steam_hot_water_output_curve
  color: "#9deef5"
  order_by: 415
  group:
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: energy_heat_heatpump_waste_water_water_ts_lt_electricity_steam_hot_water_output_curve
  is_1990:
  dependent_on:
  output_element_key: heat_network_production_lt
  key: energy_heat_heatpump_waste_water_water_ts_lt_electricity_steam_hot_water_output_curve_heat_network_production
- label: energy_heat_heatpump_drink_water_water_ts_electricity_steam_hot_water_output_curve
  color: "#c1f1f5"
  order_by: 420
  group:
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: energy_heat_heatpump_drink_water_water_ts_lt_electricity_steam_hot_water_output_curve
  is_1990:
  dependent_on:
  output_element_key: heat_network_production_lt
  key: energy_heat_heatpump_drink_water_water_ts_lt_electricity_steam_hot_water_output_curve_heat_network_production
- label: energy_heat_boiler_electricity_steam_hot_water_output_curve
  color: "#b9effe"
  order_by: 425
  group:
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: energy_heat_boiler_electricity_lt_steam_hot_water_output_curve
  is_1990:
  dependent_on:
  output_element_key: heat_network_production_lt
  key: energy_heat_boiler_electricity_lt_steam_hot_water_output_curve_heat_network_production

- label: energy_heat_network_storage_out
  color: "#0984E3"
  order_by: 500
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position:
  gquery: energy_heat_network_storage_lt_steam_hot_water_output_curve
  is_1990: false
  dependent_on:
  output_element_key: heat_network_production_lt
  key: energy_heat_network_storage_lt_steam_hot_water_out_heat_network_production
- label: energy_heat_backup_burner_network_gas_steam_hot_water_output_curve
  color: "#CED6E0"
  order_by: 505
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position:
  gquery: energy_heat_backup_burner_network_gas_lt_steam_hot_water_output_curve
  is_1990: false
  dependent_on:
  output_element_key: heat_network_production_lt
  key: energy_heat_backup_burner_network_gas_lt_steam_hot_water_output_curve_heat_network_production
