---
- label: collective
  color: "#ffb300"
  order_by: 100
  group: heat_from_surface_water
  is_target_line: false
  gquery: heat_from_aquathermal_surface_water_collective
  output_element_key: heat_aquathermal_demand
  key: heat_aquathermal_demand_surface_water_collective
- label: individual
  color: "#e07033"
  order_by: 105
  group: heat_from_surface_water
  is_target_line: false
  gquery: heat_from_aquathermal_surface_water_individual
  output_element_key: heat_aquathermal_demand
  key: heat_aquathermal_demand_surface_water_individual
- label: potential_surface_water
  color: "#4169e1"
  order_by: 110
  group: heat_from_surface_water
  is_target_line: true
  gquery: heat_aquathermal_potential_from_surface_water
  output_element_key: heat_aquathermal_demand
  key: heat_aquathermal_demand_surface_water_potential

- label: collective
  color: "#ffb300"
  order_by: 100
  group: heat_from_waste_water
  is_target_line: false
  gquery: heat_from_aquathermal_waste_water_collective
  output_element_key: heat_aquathermal_demand
  key: heat_aquathermal_demand_waste_water_collective
- label: individual
  color: "#e07033"
  order_by: 105
  group: heat_from_waste_water
  is_target_line: false
  gquery: heat_from_aquathermal_waste_water_individual
  output_element_key: heat_aquathermal_demand
  key: heat_aquathermal_demand_waste_water_individual
- label: potential_waste_water
  color: "#4169e1"
  order_by: 110
  group: heat_from_waste_water
  is_target_line: true
  gquery: heat_aquathermal_potential_from_waste_water
  output_element_key: heat_aquathermal_demand
  key: heat_aquathermal_demand_waste_water_potential

- label: collective
  color: "#ffb300"
  order_by: 100
  group: heat_from_drink_water
  is_target_line: false
  gquery: heat_from_aquathermal_drink_water_collective
  output_element_key: heat_aquathermal_demand
  key: heat_aquathermal_demand_drink_water_collective
- label: individual
  color: "#e07033"
  order_by: 105
  group: heat_from_drink_water
  is_target_line: false
  gquery: heat_from_aquathermal_drink_water_individual
  output_element_key: heat_aquathermal_demand
  key: heat_aquathermal_demand_drink_water_individual
- label: potential_drink_water
  color: "#4169e1"
  order_by: 110
  group: heat_from_drink_water
  is_target_line: true
  gquery: heat_aquathermal_potential_from_drink_water
  output_element_key: heat_aquathermal_demand
  key: heat_aquathermal_demand_drink_water_potential
