---
- label: cooking
  color: "#44AA99"
  order_by: 100
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: households_final_demand_cooking
  is_1990: false
  dependent_on: 
  output_element_key: households_final_demand_per_application
  key: cooking_households_final_demand_per_application
- label: appliances
  color: "#648FFF"
  order_by: 105
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: households_final_demand_appliances
  is_1990: false
  dependent_on: 
  output_element_key: households_final_demand_per_application
  key: appliances_households_final_demand_per_application
- label: cooling
  color: "#785EF0"
  order_by: 110
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: households_final_demand_cooling
  is_1990: false
  dependent_on: 
  output_element_key: households_final_demand_per_application
  key: cooling_households_final_demand_per_application
- label: hot_water
  color: "#DC267F"
  order_by: 115
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: households_final_demand_hot_water
  is_1990: false
  dependent_on: 
  output_element_key: households_final_demand_per_application
  key: hot_water_households_final_demand_per_application
- label: space_heating
  color: "#FE6100"
  order_by: 120
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: households_final_demand_space_heating
  is_1990: false
  dependent_on: 
  output_element_key: households_final_demand_per_application
  key: heat_households_final_demand_per_application
- label: lighting
  color: "#FFB000"
  order_by: 125
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: households_final_demand_lighting
  is_1990: false
  dependent_on: 
  output_element_key: households_final_demand_per_application
  key: lighting_households_final_demand_per_application
