---
- label: wind_coastal
  color: "#3f4ca2"
  order_by: 10
  group: wind_onshore
  gquery: land_use_solar_wind_wind_coastal_total_land_use
  output_element_key: land_use_solar_wind_chart
  key: wind_coastal_land_use_solar_wind_chart
- label: battery_wind_inland
  color: "#3fa295"
  order_by: 11
  group: wind_onshore
  gquery: land_use_solar_wind_battery_wind_inland_total_land_use
  output_element_key: land_use_solar_wind_chart
  key: battery_wind_inland_land_use_solar_wind_chart
- label: wind_inland_large
  color: "#3c7da4"
  order_by: 12
  group: wind_onshore
  gquery: land_use_solar_wind_wind_inland_large_total_land_use
  output_element_key: land_use_solar_wind_chart
  key: wind_inland_large_land_use_solar_wind_chart
- label: wind_inland_small
  color: "#9EC4DA"
  order_by: 15
  group: wind_onshore
  gquery: land_use_solar_wind_wind_inland_small_total_land_use
  output_element_key: land_use_solar_wind_chart
  key: wind_inland_small_land_use_solar_wind_chart

- label: battery_solar_PV
  color: "#e1b20b"
  order_by: 15
  group: solar_pv_plants
  gquery: land_use_solar_wind_battery_solar_pv_total_land_use
  output_element_key: land_use_solar_wind_chart
  key: battery_solar_pv_land_use_solar_wind_chart
- label: solar_pv_onshore
  color: "#F7D02F"
  order_by: 16
  group: solar_pv_plants
  gquery: land_use_solar_wind_solar_pv_plants_onshore_total_land_use
  output_element_key: land_use_solar_wind_chart
  key: solar_pv_plants_onshore_land_use_solar_wind_chart

- label: solar_thermal_buildings
  color: "#f49cd3"
  order_by: 20
  group: solar_buildings
  gquery: land_use_solar_wind_solar_thermal_buildings_total_land_use
  output_element_key: land_use_solar_wind_chart
  key: solar_thermal_buildings_land_use_solar_wind_chart
- label: solar_pv_buildings
  color: "#f5bd99"
  order_by: 22
  group: solar_buildings
  gquery: land_use_solar_wind_solar_pv_buildings_total_land_use
  output_element_key: land_use_solar_wind_chart
  key: solar_pv_buildings_land_use_solar_wind_chart
- label: buildings_roof_surface_area_available
  color: "#fd8163"
  order_by: 25
  group: rooftop_area
  is_target_line: true
  gquery: land_use_solar_wind_buildings_roof_surface_area_available
  output_element_key: land_use_solar_wind_chart
  key: buildings_roof_surface_area_available_land_use_solar_wind_chart

- label: solar_thermal_households
  color: "#dd269e"
  order_by: 30
  group: solar_households
  gquery: land_use_solar_wind_solar_thermal_households_total_land_use
  output_element_key: land_use_solar_wind_chart
  key: solar_thermal_households_land_use_solar_wind_chart
- label: solar_pv_households
  color: "#df6516"
  order_by: 31
  group: solar_households
  gquery: land_use_solar_wind_solar_pv_households_total_land_use
  output_element_key: land_use_solar_wind_chart
  key: solar_pv_households_land_use_solar_wind_chart
- label: solar_pvt_households
  color: "#ffaa9c"
  order_by: 32
  group: solar_households
  gquery: land_use_solar_wind_solar_pvt_households_total_land_use
  output_element_key: land_use_solar_wind_chart
  key: solar_pvt_households_land_use_solar_wind_chart
- label: households_roof_surface_area_available
  color: "#ee5364"
  order_by: 35
  group: solar_households
  is_target_line: true
  gquery: land_use_solar_wind_households_roof_surface_area_available
  output_element_key: land_use_solar_wind_chart
  key: households_roof_surface_area_available_land_use_solar_wind_chart
