---
- label: kerosene_demand_domestic_aviation
  color: "#8B0000"
  order_by: 5
  group: demand
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: kerosene_demand_domestic_aviation
  is_1990: false
  dependent_on:
  output_element_key: mekko_of_kerosene_demand_supply
  key: kerosene_demand_domestic_aviation_mekko_of_kerosene_demand_supply
- label: kerosene_demand_international_aviation
  color: "#82589F"
  order_by: 10
  group: demand
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: kerosene_demand_international_aviation
  is_1990: false
  dependent_on:
  output_element_key: mekko_of_kerosene_demand_supply
  key: kerosene_demand_international_aviation_mekko_of_kerosene_demand_supply
- label: kerosene_demand_export
  color: "#CCCCCC"
  order_by: 15
  group: demand
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: kerosene_demand_export
  is_1990: false
  dependent_on:
  output_element_key: mekko_of_kerosene_demand_supply
  key: kerosene_demand_export_mekko_of_kerosene_demand_supply
- label: kerosene_demand_agriculture
  color: "#ff9f43"
  order_by: 20
  group: demand
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: kerosene_demand_agriculture
  is_1990: false
  dependent_on:
  output_element_key: mekko_of_kerosene_demand_supply
  key: kerosene_demand_agriculture_mekko_of_kerosene_demand_supply
- label: kerosene_demand_buildings
  color: "#A7A1C5"
  order_by: 25
  group: demand
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: kerosene_demand_buildings
  is_1990: false
  dependent_on:
  output_element_key: mekko_of_kerosene_demand_supply
  key: kerosene_demand_buildings_mekko_of_kerosene_demand_supply
- label: kerosene_demand_industry
  color: "#2e86de"
  order_by: 30
  group: demand
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: kerosene_demand_industry
  is_1990: false
  dependent_on:
  output_element_key: mekko_of_kerosene_demand_supply
  key: kerosene_demand_industry_mekko_of_kerosene_demand_supply
- label: kerosene_demand_households
  color: "#10ac84"
  order_by: 35
  group: demand
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: kerosene_demand_households
  is_1990: false
  dependent_on:
  output_element_key: mekko_of_kerosene_demand_supply
  key: kerosene_demand_households_mekko_of_kerosene_demand_supply
- label: kerosene_demand_bio_agriculture
  color: "#333333"
  order_by: 40
  group: demand
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: kerosene_demand_bio_agriculture
  is_1990: false
  dependent_on:
  output_element_key: mekko_of_kerosene_demand_supply
  key: kerosene_demand_bio_agriculture_mekko_of_kerosene_demand_supply
- label: kerosene_demand_bio_buildings
  color: "#DFE4EA"
  order_by: 45
  group: demand
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: kerosene_demand_bio_buildings
  is_1990: false
  dependent_on:
  output_element_key: mekko_of_kerosene_demand_supply
  key: kerosene_demand_bio_buildings_mekko_of_kerosene_demand_supply
- label: kerosene_demand_bio_industry
  color: "#63A1C9"
  order_by: 50
  group: demand
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: kerosene_demand_bio_industry
  is_1990: false
  dependent_on:
  output_element_key: mekko_of_kerosene_demand_supply
  key: kerosene_demand_bio_industry_mekko_of_kerosene_demand_supply
- label: kerosene_demand_bio_households
  color: "#5D7929"
  order_by: 55
  group: demand
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: kerosene_demand_bio_households
  is_1990: false
  dependent_on:
  output_element_key: mekko_of_kerosene_demand_supply
  key: kerosene_demand_bio_households_mekko_of_kerosene_demand_supply
  
- label: kerosene_supply_synthetic_kerosene_must_run
  color: "#74B9FF"
  order_by: 100
  group: supply
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: kerosene_supply_synthetic_kerosene_must_run
  is_1990: false
  dependent_on:
  output_element_key: mekko_of_kerosene_demand_supply
  key: kerosene_supply_synthetic_kerosene_must_run_mekko_of_kerosene_demand_supply
- label: kerosene_supply_synthetic_kerosene_dispatchable
  color: "#74ffff"
  order_by: 105
  group: supply
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: kerosene_supply_synthetic_kerosene_dispatchable
  is_1990: false
  dependent_on:
  output_element_key: mekko_of_kerosene_demand_supply
  key: kerosene_supply_synthetic_dispatchable_must_run_mekko_of_kerosene_demand_supply
- label: kerosene_supply_bio_kerosene
  color: "#5D7929"
  order_by: 110
  group: supply
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: kerosene_supply_bio_kerosene
  is_1990: false
  dependent_on:
  output_element_key: mekko_of_kerosene_demand_supply
  key: kerosene_supply_bio_kerosene_mekko_of_kerosene_demand_supply
- label: kerosene_supply_refineries
  color: "#854321"
  order_by: 115
  group: supply
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: kerosene_supply_refineries
  is_1990: false
  dependent_on:
  output_element_key: mekko_of_kerosene_demand_supply
  key: kerosene_supply_refineries_mekko_of_kerosene_demand_supply
- label: kerosene_supply_import
  color: "#FDE97B"
  order_by: 120
  group: supply
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: kerosene_supply_import
  is_1990: false
  dependent_on:
  output_element_key: mekko_of_kerosene_demand_supply
  key: kerosene_supply_import_mekko_of_kerosene_demand_supply
