---
- label: ammonia_demand_domestic_navigation
  color: "#0984E3"
  order_by: 130
  group: demand
  show_at_first: false
  is_target_line: false
  target_line_position:
  gquery: ammonia_demand_domestic_navigation
  is_1990: false
  dependent_on:
  output_element_key: mekko_of_ammonia_demand_supply
  key: ammonia_demand_domestic_navigation_mekko_of_ammonia_demand_supply
- label: ammonia_demand_international_navigation
  color: "#8B4513"
  order_by: 100
  group: demand
  show_at_first: false
  is_target_line: false
  target_line_position:
  gquery: ammonia_demand_international_navigation
  is_1990: false
  dependent_on:
  output_element_key: mekko_of_ammonia_demand_supply
  key: ammonia_demand_international_navigation_mekko_of_ammonia_demand_supply
- label: ammonia_demand_fertilizer_industry
  color: "#228B22"
  order_by: 110
  group: demand
  show_at_first: false
  is_target_line: false
  target_line_position:
  gquery: ammonia_demand_fertilizer_industry
  is_1990: false
  dependent_on:
  output_element_key: mekko_of_ammonia_demand_supply
  key: ammonia_demand_fertilizer_industry_mekko_of_ammonia_demand_supply
- label: ammonia_demand_other_industry
  color: "#0d370d"
  order_by: 120
  group: demand
  show_at_first: false
  is_target_line: false
  target_line_position:
  gquery: ammonia_demand_other_industry
  is_1990: false
  dependent_on:
  output_element_key: mekko_of_ammonia_demand_supply
  key: ammonia_demand_other_industry_mekko_of_ammonia_demand_supply  
- label: ammonia_demand_hydrogen_ammonia_reformer_must_run
  color: "#569CB9"
  order_by: 130
  group: demand
  show_at_first: false
  is_target_line: false
  target_line_position:
  gquery: ammonia_demand_hydrogen_ammonia_reformer_must_run
  is_1990: false
  dependent_on:
  output_element_key: mekko_of_ammonia_demand_supply
  key: ammonia_demand_hydrogen_ammonia_reformer_must_run_mekko_of_ammonia_demand_supply
- label: ammonia_demand_hydrogen_ammonia_reformer_dispatchable
  color: "#87CEEB"
  order_by: 140
  group: demand
  show_at_first: false
  is_target_line: false
  target_line_position:
  gquery: ammonia_demand_hydrogen_ammonia_reformer_dispatchable
  is_1990: false
  dependent_on:
  output_element_key: mekko_of_ammonia_demand_supply
  key: ammonia_demand_hydrogen_ammonia_reformer_dispatchable_mekko_of_ammonia_demand_supply
- label: ammonia_demand_export
  color: "#485460"
  order_by: 150
  group: demand
  show_at_first: false
  is_target_line: false
  target_line_position:
  gquery: ammonia_demand_export
  is_1990: false
  dependent_on:
  output_element_key: mekko_of_ammonia_demand_supply
  key: ammonia_demand_export_mekko_of_ammonia_demand_supply
- label: ammonia_demand_transformation_chemical_fertilizers_industry
  color: "#ddd3d3"
  group: demand
  order_by: 160
  show_at_first: false
  is_target_line: false
  target_line_position:
  gquery: ammonia_demand_transformation_chemical_fertilizers_industry
  is_1990: false
  dependent_on:
  output_element_key: mekko_of_ammonia_demand_supply
  key: ammonia_demand_transformation_chemical_fertilizers_industry_mekko_of_ammonia_demand_supply
- label: ammonia_demand_transformation_chemical_other_industry
  color: "#f8f1f1"
  order_by: 170
  group: demand
  show_at_first: false
  is_target_line: false
  target_line_position:
  gquery: ammonia_demand_transformation_chemical_other_industry
  is_1990: false
  dependent_on:
  output_element_key: mekko_of_ammonia_demand_supply
  key: ammonia_demand_transformation_chemical_other_industry_mekko_of_ammonia_demand_supply
- label: ammonia_demand_transformation_chemical_refineries_industry
  color: "#747373"
  order_by: 180
  group: demand
  show_at_first: false
  is_target_line: false
  target_line_position:
  gquery: ammonia_demand_transformation_chemical_refineries_industry
  is_1990: false
  dependent_on:
  output_element_key: mekko_of_ammonia_demand_supply
  key: ammonia_demand_transformation_chemical_refineries_industry_mekko_of_ammonia_demand_supply




- label: ammonia_supply_import_baseload
  color: "#bdfff6"
  order_by: 200
  group: supply
  show_at_first: false
  is_target_line: false
  target_line_position:
  gquery: ammonia_supply_import_baseload
  is_1990: false
  dependent_on:
  output_element_key: mekko_of_ammonia_demand_supply
  key: ammonia_supply_import_baseload_mekko_of_ammonia_demand_supply
- label: ammonia_supply_import_backup
  color: "#71e3da"
  order_by: 210
  group: supply
  show_at_first: false
  is_target_line: false
  target_line_position:
  gquery: ammonia_supply_import_backup
  is_1990: false
  dependent_on:
  output_element_key: mekko_of_ammonia_demand_supply
  key: ammonia_supply_import_backup_mekko_of_ammonia_demand_supply
- label: ammonia_supply_transformation_chemical_fertilizers_industry
  color: "#d8eded"
  order_by: 220
  group: supply
  show_at_first: false
  is_target_line: false
  target_line_position:
  gquery: ammonia_supply_transformation_chemical_fertilizers_industry
  is_1990: false
  dependent_on:
  output_element_key: mekko_of_ammonia_demand_supply
  key: ammonia_supply_transformation_chemical_fertilizers_industry_mekko_of_ammonia_demand_supply
- label: ammonia_supply_transformation_chemical_other_industry
  color: "#e6fffe"
  order_by: 230
  group: supply
  show_at_first: false
  is_target_line: false
  target_line_position:
  gquery: ammonia_supply_transformation_chemical_other_industry
  is_1990: false
  dependent_on:
  output_element_key: mekko_of_ammonia_demand_supply
  key: ammonia_supply_transformation_chemical_other_industry_mekko_of_ammonia_demand_supply
- label: ammonia_supply_transformation_chemical_refineries_industry
  color: "#697a7a"
  order_by: 240
  group: supply
  show_at_first: false
  is_target_line: false
  target_line_position:
  gquery: ammonia_supply_transformation_chemical_refineries_industry
  is_1990: false
  dependent_on:
  output_element_key: mekko_of_ammonia_demand_supply
  key: ammonia_supply_transformation_chemical_refineries_industry_mekko_of_ammonia_demand_supply

