---
- label: network_gas_production
  color: "#FF0000"
  order_by: 5
  group:
  show_at_first:
  is_target_line: true
  target_line_position:
  gquery: network_gas_production_output_curve
  is_1990:
  dependent_on:
  output_element_key: network_gas_demand
  key: network_gas_production_network_gas_demand
- label: exported_network_gas
  color: "#485460"
  order_by: 10
  group:
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: export_network_gas_input_curve
  is_1990:
  dependent_on:
  output_element_key: network_gas_demand
  key: exported_network_gas_network_gas_demand
- label: industry_final_demand_network_gas
  color: "#416B86"
  order_by: 15
  group:
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: industry_network_gas_input_curve
  is_1990:
  dependent_on:
  output_element_key: network_gas_demand
  key: industry_final_demand_network_gas_network_gas_demand
- label: industry_transformation_network_gas
  color: "#1D303D"
  order_by: 20
  group:
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: industry_transformation_network_gas_input_curve
  is_1990:
  dependent_on:
  output_element_key: network_gas_demand
  key: industry_transformation_network_gas_network_gas_demand
- label: agriculture_final_demand_network_gas
  color: "#6AB04C"
  order_by: 25
  group:
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: agriculture_network_gas_input_curve
  is_1990:
  dependent_on:
  output_element_key: network_gas_demand
  key: agriculture_final_demand_network_gas_network_gas_demand
- label: buildings_final_demand_network_gas
  color: "#F9CA24"
  order_by: 30
  group:
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: buildings_network_gas_input_curve
  is_1990:
  dependent_on:
  output_element_key: network_gas_demand
  key: buildings_final_demand_network_gas_network_gas_demand
- label: households_final_demand_network_gas
  color: "#E69567"
  order_by: 35
  group:
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: households_network_gas_input_curve
  is_1990:
  dependent_on:
  output_element_key: network_gas_demand
  key: households_final_demand_network_gas_network_gas_demand
- label: transport_final_demand_network_gas
  color: "#74B9FF"
  order_by: 40
  group:
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: transport_network_gas_input_curve
  is_1990:
  dependent_on:
  output_element_key: network_gas_demand
  key: transport_final_demand_network_gas_network_gas_demand
- label: other_final_demand_network_gas
  color: "#786FA6"
  order_by: 45
  group:
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: other_network_gas_input_curve
  is_1990:
  dependent_on:
  output_element_key: network_gas_demand
  key: other_final_demand_network_gas_network_gas_demand
- label: bunkers_final_demand_network_gas
  color: "#218C74"
  order_by: 50
  group:
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: bunkers_network_gas_input_curve
  is_1990:
  dependent_on:
  output_element_key: network_gas_demand
  key: bunkers_final_demand_network_gas_network_gas_demand
- label: power_demand_network_gas
  color: "#0984E3"
  order_by: 55
  group:
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: electricity_production_network_gas_input_curve
  is_1990:
  dependent_on:
  output_element_key: network_gas_demand
  key: power_demand_network_gas_network_gas_demand
- label: heat_demand_network_gas
  color: "#E84118"
  order_by: 60
  group:
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: heat_production_network_gas_input_curve
  is_1990:
  dependent_on:
  output_element_key: network_gas_demand
  key: heat_demand_network_gas_network_gas_demand
- label: hydrogen_demand_network_gas
  color: "#87CEEB"
  order_by: 65
  group:
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: hydrogen_production_network_gas_input_curve
  is_1990:
  dependent_on:
  output_element_key: network_gas_demand
  key: hydrogen_demand_network_gas_network_gas_demand
- label: liquid_biofuels_demand_network_gas
  color: "#8FBC8F"
  order_by: 67
  group:
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: liquid_biofuels_production_network_gas_input_curve
  is_1990:
  dependent_on:
  output_element_key: network_gas_demand
  key: liquid_biofuels_demand_network_gas_network_gas_demand
- label: network_gas_storage_input
  color: "#DFE4EA"
  order_by: 70
  group:
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: energy_network_gas_storage_network_gas_input_curve
  is_1990:
  dependent_on:
  output_element_key: network_gas_demand
  key: network_gas_storage_input_network_gas_demand
- label: transport_losses
  color: "#800080"
  order_by: 75
  group:
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: loss_network_gas_input_curve
  is_1990:
  dependent_on:
  output_element_key: network_gas_demand
  key: transport_losses_network_gas_demand
