---
- label: residences_before_1945
  color: "#44AA99"
  order_by: 125
  group: apartments
  show_at_first: 
  is_target_line: false
  target_line_position: 
  gquery: number_of_apartments_before_1945_mekko
  is_1990: 
  dependent_on: 
  output_element_key: number_of_residences_overview
  key: number_of_apartments_before_1945_mekko_number_of_residences_overview
- label: residences_1945_1964
  color: "#648FFF"
  order_by: 120
  group: apartments
  show_at_first: 
  is_target_line: false
  target_line_position: 
  gquery: number_of_apartments_1945_1964_mekko
  is_1990: 
  dependent_on: 
  output_element_key: number_of_residences_overview
  key: number_of_apartments_1945_1964_mekko_number_of_residences_overview
- label: residences_1965_1984
  color: "#785EF0"
  order_by: 115
  group: apartments
  show_at_first: 
  is_target_line: false
  target_line_position: 
  gquery: number_of_apartments_1965_1984_mekko
  is_1990: 
  dependent_on: 
  output_element_key: number_of_residences_overview
  key: number_of_apartments_1965_1984_mekko_number_of_residences_overview  
- label: residences_1985_2004
  color: "#DC267F"
  order_by: 110
  group: apartments
  show_at_first: 
  is_target_line: false
  target_line_position: 
  gquery: number_of_apartments_1985_2004_mekko
  is_1990: 
  dependent_on: 
  output_element_key: number_of_residences_overview
  key: number_of_apartments_1985_2004_mekko_number_of_residences_overview
- label: residences_2005_present
  color: "#FE6100"
  order_by: 105
  group: apartments
  show_at_first: 
  is_target_line: false
  target_line_position: 
  gquery: number_of_apartments_2005_present_mekko
  is_1990: 
  dependent_on: 
  output_element_key: number_of_residences_overview
  key: number_of_apartments_2005_present_mekko_number_of_residences_overview  
- label: residences_future
  color: "#FFB000"
  order_by: 100
  group: apartments
  show_at_first: 
  is_target_line: false
  target_line_position: 
  gquery: number_of_apartments_future_mekko
  is_1990: 
  dependent_on: 
  output_element_key: number_of_residences_overview
  key: number_of_apartments_future_mekko_number_of_residences_overview    


- label: residences_before_1945
  color: "#44AA99"
  order_by: 225
  group: detached_houses
  show_at_first: 
  is_target_line: false
  target_line_position: 
  gquery: number_of_detached_houses_before_1945_mekko
  is_1990: 
  dependent_on: 
  output_element_key: number_of_residences_overview
  key: number_of_detached_houses_before_1945_mekko_number_of_residences_overview
- label: residences_1945_1964
  color: "#648FFF"
  order_by: 220
  group: detached_houses
  show_at_first: 
  is_target_line: false
  target_line_position: 
  gquery: number_of_detached_houses_1945_1964_mekko
  is_1990: 
  dependent_on: 
  output_element_key: number_of_residences_overview
  key: number_of_detached_houses_1945_1964_mekko_number_of_residences_overview
- label: residences_1965_1984
  color: "#785EF0"
  order_by: 215
  group: detached_houses
  show_at_first: 
  is_target_line: false
  target_line_position: 
  gquery: number_of_detached_houses_1965_1984_mekko
  is_1990: 
  dependent_on: 
  output_element_key: number_of_residences_overview
  key: number_of_detached_houses_1965_1984_mekko_number_of_residences_overview  
- label: residences_1985_2004
  color: "#DC267F"
  order_by: 210
  group: detached_houses
  show_at_first: 
  is_target_line: false
  target_line_position: 
  gquery: number_of_detached_houses_1985_2004_mekko
  is_1990: 
  dependent_on: 
  output_element_key: number_of_residences_overview
  key: number_of_detached_houses_1985_2004_mekko_number_of_residences_overview
- label: residences_2005_present
  color: "#FE6100"
  order_by: 205
  group: detached_houses
  show_at_first: 
  is_target_line: false
  target_line_position: 
  gquery: number_of_detached_houses_2005_present_mekko
  is_1990: 
  dependent_on: 
  output_element_key: number_of_residences_overview
  key: number_of_detached_houses_2005_present_mekko_number_of_residences_overview  
- label: residences_future
  color: "#FFB000"
  order_by: 200
  group: detached_houses
  show_at_first: 
  is_target_line: false
  target_line_position: 
  gquery: number_of_detached_houses_future_mekko
  is_1990: 
  dependent_on: 
  output_element_key: number_of_residences_overview
  key: number_of_detached_houses_future_mekko_number_of_residences_overview    

- label: residences_before_1945
  color: "#44AA99"
  order_by: 325
  group: semi_detached_houses
  show_at_first: 
  is_target_line: false
  target_line_position: 
  gquery: number_of_semi_detached_houses_before_1945_mekko
  is_1990: 
  dependent_on: has_semi_detached_houses
  output_element_key: number_of_residences_overview
  key: number_of_semi_detached_houses_before_1945_mekko_number_of_residences_overview
- label: residences_1945_1964
  color: "#648FFF"
  order_by: 320
  group: semi_detached_houses
  show_at_first: 
  is_target_line: false
  target_line_position: 
  gquery: number_of_semi_detached_houses_1945_1964_mekko
  is_1990: 
  dependent_on: has_semi_detached_houses
  output_element_key: number_of_residences_overview
  key: number_of_semi_detached_houses_1945_1964_mekko_number_of_residences_overview
- label: residences_1965_1984
  color: "#785EF0"
  order_by: 315
  group: semi_detached_houses
  show_at_first: 
  is_target_line: false
  target_line_position: 
  gquery: number_of_semi_detached_houses_1965_1984_mekko
  is_1990: 
  dependent_on: has_semi_detached_houses
  output_element_key: number_of_residences_overview
  key: number_of_semi_detached_houses_1965_1984_mekko_number_of_residences_overview  
- label: residences_1985_2004
  color: "#DC267F"
  order_by: 310
  group: semi_detached_houses
  show_at_first: 
  is_target_line: false
  target_line_position: 
  gquery: number_of_semi_detached_houses_1985_2004_mekko
  is_1990: 
  dependent_on: has_semi_detached_houses
  output_element_key: number_of_residences_overview
  key: number_of_semi_detached_houses_1985_2004_mekko_number_of_residences_overview
- label: residences_2005_present
  color: "#FE6100"
  order_by: 305
  group: semi_detached_houses
  show_at_first: 
  is_target_line: false
  target_line_position: 
  gquery: number_of_semi_detached_houses_2005_present_mekko
  is_1990: 
  dependent_on: has_semi_detached_houses
  output_element_key: number_of_residences_overview
  key: number_of_semi_detached_houses_2005_present_mekko_number_of_residences_overview  
- label: residences_future
  color: "#FFB000"
  order_by: 300
  group: semi_detached_houses
  show_at_first: 
  is_target_line: false
  target_line_position: 
  gquery: number_of_semi_detached_houses_future_mekko
  is_1990: 
  dependent_on: has_semi_detached_houses
  output_element_key: number_of_residences_overview
  key: number_of_semi_detached_houses_future_mekko_number_of_residences_overview    

- label: residences_before_1945
  color: "#44AA99"
  order_by: 425
  group: terraced_houses
  show_at_first: 
  is_target_line: false
  target_line_position: 
  gquery: number_of_terraced_houses_before_1945_mekko
  is_1990: 
  dependent_on: 
  output_element_key: number_of_residences_overview
  key: number_of_terraced_houses_before_1945_mekko_number_of_residences_overview
- label: residences_1945_1964
  color: "#648FFF"
  order_by: 420
  group: terraced_houses
  show_at_first: 
  is_target_line: false
  target_line_position: 
  gquery: number_of_terraced_houses_1945_1964_mekko
  is_1990: 
  dependent_on: 
  output_element_key: number_of_residences_overview
  key: number_of_terraced_houses_1945_1964_mekko_number_of_residences_overview
- label: residences_1965_1984
  color: "#785EF0"
  order_by: 415
  group: terraced_houses
  show_at_first: 
  is_target_line: false
  target_line_position: 
  gquery: number_of_terraced_houses_1965_1984_mekko
  is_1990: 
  dependent_on: 
  output_element_key: number_of_residences_overview
  key: number_of_terraced_houses_1965_1984_mekko_number_of_residences_overview  
- label: residences_1985_2004
  color: "#DC267F"
  order_by: 410
  group: terraced_houses
  show_at_first: 
  is_target_line: false
  target_line_position: 
  gquery: number_of_terraced_houses_1985_2004_mekko
  is_1990: 
  dependent_on: 
  output_element_key: number_of_residences_overview
  key: number_of_terraced_houses_1985_2004_mekko_number_of_residences_overview
- label: residences_2005_present
  color: "#FE6100"
  order_by: 405
  group: terraced_houses
  show_at_first: 
  is_target_line: false
  target_line_position: 
  gquery: number_of_terraced_houses_2005_present_mekko
  is_1990: 
  dependent_on: 
  output_element_key: number_of_residences_overview
  key: number_of_terraced_houses_2005_present_mekko_number_of_residences_overview  
- label: residences_future
  color: "#FFB000"
  order_by: 400
  group: terraced_houses
  show_at_first: 
  is_target_line: false
  target_line_position: 
  gquery: number_of_terraced_houses_future_mekko
  is_1990: 
  dependent_on: 
  output_element_key: number_of_residences_overview
  key: number_of_terraced_houses_future_mekko_number_of_residences_overview    




