---
- label: residual_heat_production_ht
  color: "#C9C0F7"
  order_by: 120
  group: residual_heat_production
  show_at_first: 
  is_target_line: false
  target_line_position: 
  gquery: energy_heat_production_output_ht_residual_heat
  is_1990: 
  dependent_on: 
  output_element_key: residual_heat_supply_potential
  key: residual_heat_supply_potential_production_ht_residual_heat
- label: residual_heat_production_mt
  color: "#F0A9CB"
  order_by: 110
  group: residual_heat_production
  show_at_first: 
  is_target_line: false
  target_line_position: 
  gquery: energy_heat_production_output_mt_residual_heat
  is_1990: 
  dependent_on: 
  output_element_key: residual_heat_supply_potential
  key: residual_heat_supply_potential_production_mt_residual_heat
- label: residual_heat_production_lt
  color: "#FEDE9E"
  order_by: 100
  group: residual_heat_production
  show_at_first: 
  is_target_line: false
  target_line_position: 
  gquery: energy_heat_production_output_lt_residual_heat
  is_1990: 
  dependent_on: 
  output_element_key: residual_heat_supply_potential
  key: residual_heat_supply_potential_production_lt_residual_heat

- label: residual_heat_potential_refineries
  color: "#022C41"
  order_by: 200
  group: residual_heat_potential
  show_at_first: 
  is_target_line: false
  target_line_position: 
  gquery: industry_chemicals_refineries_potential_residual_heat
  is_1990: 
  dependent_on: 
  output_element_key: residual_heat_supply_potential
  key: residual_heat_supply_potential_refineries_residual_heat_potential
- label: residual_heat_potential_fertilizers
  color: "#BFD6E1"
  order_by: 210
  group: residual_heat_potential
  show_at_first: 
  is_target_line: false
  target_line_position: 
  gquery: industry_chemicals_fertilizers_potential_residual_heat
  is_1990: 
  dependent_on: 
  output_element_key: residual_heat_supply_potential
  key: residual_heat_supply_potential_fertilizers_residual_heat_potential
- label: residual_heat_potential_chemicals
  color: "#E0E8B2"
  order_by: 220
  group: residual_heat_potential
  show_at_first: 
  is_target_line: false
  target_line_position: 
  gquery: industry_chemicals_other_potential_residual_heat
  is_1990: 
  dependent_on: 
  output_element_key: residual_heat_supply_potential
  key: residual_heat_supply_potential_chemicals_residual_heat_potential
- label: residual_heat_potential_central_ICT
  color: "#683275"
  order_by: 230
  group: residual_heat_potential
  show_at_first: 
  is_target_line: false
  target_line_position: 
  gquery: industry_other_ict_potential_residual_heat
  is_1990: 
  dependent_on: 
  output_element_key: residual_heat_supply_potential
  key: residual_heat_supply_potential_central_ICT_residual_heat_potential
- label: residual_heat_potential_p2g_hydrogen
  color: "#ECB84A"
  order_by: 240
  group: residual_heat_potential
  show_at_first: 
  is_target_line: false
  target_line_position: 
  gquery: energy_hydrogen_flexibility_p2g_potential_residual_heat
  is_1990: 
  dependent_on: 
  output_element_key: residual_heat_supply_potential
  key: residual_heat_supply_potential_p2g_hydrogen_residual_heat_potential
