---
- label: residences_before_1945
  color: "#44AA99"
  order_by: 10
  group: apartments_bar
  show_at_first: 
  is_target_line: false
  target_line_position: 
  gquery: useful_demand_apartments_before_1945_bar
  is_1990: 
  dependent_on: 
  output_element_key: residential_heating_demand
  key: useful_demand_apartments_before_1945_bar_residential_heating_demand
- label: residences_1945_1964
  color: "#648FFF"
  order_by: 20
  group: apartments_bar
  show_at_first: 
  is_target_line: false
  target_line_position: 
  gquery: useful_demand_apartments_1945_1964_bar
  is_1990: 
  dependent_on: 
  output_element_key: residential_heating_demand
  key: useful_demand_apartments_1945_1964_bar_residential_heating_demand
- label: residences_1965_1984
  color: "#785EF0"
  order_by: 30
  group: apartments_bar
  show_at_first: 
  is_target_line: false
  target_line_position: 
  gquery: useful_demand_apartments_1965_1984_bar
  is_1990: 
  dependent_on: 
  output_element_key: residential_heating_demand
  key: useful_demand_apartments_1965_1984_bar_residential_heating_demand  
- label: residences_1985_2004
  color: "#DC267F"
  order_by: 40
  group: apartments_bar
  show_at_first: 
  is_target_line: false
  target_line_position: 
  gquery: useful_demand_apartments_1985_2004_bar
  is_1990: 
  dependent_on: 
  output_element_key: residential_heating_demand
  key: useful_demand_apartments_1985_2004_bar_residential_heating_demand
- label: residences_2005_present
  color: "#FE6100"
  order_by: 50
  group: apartments_bar
  show_at_first: 
  is_target_line: false
  target_line_position: 
  gquery: useful_demand_apartments_2005_present_bar
  is_1990: 
  dependent_on: 
  output_element_key: residential_heating_demand
  key: useful_demand_apartments_2005_present_bar_residential_heating_demand  
- label: residences_future
  color: "#FFB000"
  order_by: 60
  group: apartments_bar
  show_at_first: 
  is_target_line: false
  target_line_position: 
  gquery: useful_demand_apartments_future_bar
  is_1990: 
  dependent_on: 
  output_element_key: residential_heating_demand
  key: useful_demand_apartments_future_bar_residential_heating_demand    

- label: residences_before_1945
  color: "#44AA99"
  order_by: 110
  group: detached_houses_bar
  show_at_first: 
  is_target_line: false
  target_line_position: 
  gquery: useful_demand_detached_houses_before_1945_bar
  is_1990: 
  dependent_on: 
  output_element_key: residential_heating_demand
  key: useful_demand_detached_houses_before_1945_bar_residential_heating_demand
- label: residences_1945_1964
  color: "#648FFF"
  order_by: 120
  group: detached_houses_bar
  show_at_first: 
  is_target_line: false
  target_line_position: 
  gquery: useful_demand_detached_houses_1945_1964_bar
  is_1990: 
  dependent_on: 
  output_element_key: residential_heating_demand
  key: useful_demand_detached_houses_1945_1964_bar_residential_heating_demand
- label: residences_1965_1984
  color: "#785EF0"
  order_by: 130
  group: detached_houses_bar
  show_at_first: 
  is_target_line: false
  target_line_position: 
  gquery: useful_demand_detached_houses_1965_1984_bar
  is_1990: 
  dependent_on: 
  output_element_key: residential_heating_demand
  key: useful_demand_detached_houses_1965_1984_bar_residential_heating_demand  
- label: residences_1985_2004
  color: "#DC267F"
  order_by: 140
  group: detached_houses_bar
  show_at_first: 
  is_target_line: false
  target_line_position: 
  gquery: useful_demand_detached_houses_1985_2004_bar
  is_1990: 
  dependent_on: 
  output_element_key: residential_heating_demand
  key: useful_demand_detached_houses_1985_2004_bar_residential_heating_demand
- label: residences_2005_present
  color: "#FE6100"
  order_by: 150
  group: detached_houses_bar
  show_at_first: 
  is_target_line: false
  target_line_position: 
  gquery: useful_demand_detached_houses_2005_present_bar
  is_1990: 
  dependent_on: 
  output_element_key: residential_heating_demand
  key: useful_demand_detached_houses_2005_present_bar_residential_heating_demand  
- label: residences_future
  color: "#FFB000"
  order_by: 160
  group: detached_houses_bar
  show_at_first: 
  is_target_line: false
  target_line_position: 
  gquery: useful_demand_detached_houses_future_bar
  is_1990: 
  dependent_on: 
  output_element_key: residential_heating_demand
  key: useful_demand_detached_houses_future_bar_residential_heating_demand    

- label: residences_before_1945
  color: "#44AA99"
  order_by: 210
  group: semi_detached_houses_bar
  show_at_first: 
  is_target_line: false
  target_line_position: 
  gquery: useful_demand_semi_detached_houses_before_1945_bar
  is_1990: 
  dependent_on: 
  output_element_key: residential_heating_demand
  key: useful_demand_semi_detached_houses_before_1945_bar_residential_heating_demand
- label: residences_1945_1964
  color: "#648FFF"
  order_by: 220
  group: semi_detached_houses_bar
  show_at_first: 
  is_target_line: false
  target_line_position: 
  gquery: useful_demand_semi_detached_houses_1945_1964_bar
  is_1990: 
  dependent_on: 
  output_element_key: residential_heating_demand
  key: useful_demand_semi_detached_houses_1945_1964_bar_residential_heating_demand
- label: residences_1965_1984
  color: "#785EF0"
  order_by: 230
  group: semi_detached_houses_bar
  show_at_first: 
  is_target_line: false
  target_line_position: 
  gquery: useful_demand_semi_detached_houses_1965_1984_bar
  is_1990: 
  dependent_on: 
  output_element_key: residential_heating_demand
  key: useful_demand_semi_detached_houses_1965_1984_bar_residential_heating_demand  
- label: residences_1985_2004
  color: "#DC267F"
  order_by: 240
  group: semi_detached_houses_bar
  show_at_first: 
  is_target_line: false
  target_line_position: 
  gquery: useful_demand_semi_detached_houses_1985_2004_bar
  is_1990: 
  dependent_on: 
  output_element_key: residential_heating_demand
  key: useful_demand_semi_detached_houses_1985_2004_bar_residential_heating_demand
- label: residences_2005_present
  color: "#FE6100"
  order_by: 250
  group: semi_detached_houses_bar
  show_at_first: 
  is_target_line: false
  target_line_position: 
  gquery: useful_demand_semi_detached_houses_2005_present_bar
  is_1990: 
  dependent_on: 
  output_element_key: residential_heating_demand
  key: useful_demand_semi_detached_houses_2005_present_bar_residential_heating_demand  
- label: residences_future
  color: "#FFB000"
  order_by: 260
  group: semi_detached_houses_bar
  show_at_first: 
  is_target_line: false
  target_line_position: 
  gquery: useful_demand_semi_detached_houses_future_bar
  is_1990: 
  dependent_on: 
  output_element_key: residential_heating_demand
  key: useful_demand_semi_detached_houses_future_bar_residential_heating_demand    

- label: residences_before_1945
  color: "#44AA99"
  order_by: 310
  group: terraced_houses_bar
  show_at_first: 
  is_target_line: false
  target_line_position: 
  gquery: useful_demand_terraced_houses_before_1945_bar
  is_1990: 
  dependent_on: 
  output_element_key: residential_heating_demand
  key: useful_demand_terraced_houses_before_1945_bar_residential_heating_demand
- label: residences_1945_1964
  color: "#648FFF"
  order_by: 320
  group: terraced_houses_bar
  show_at_first: 
  is_target_line: false
  target_line_position: 
  gquery: useful_demand_terraced_houses_1945_1964_bar
  is_1990: 
  dependent_on: 
  output_element_key: residential_heating_demand
  key: useful_demand_terraced_houses_1945_1964_bar_residential_heating_demand
- label: residences_1965_1984
  color: "#785EF0"
  order_by: 330
  group: terraced_houses_bar
  show_at_first: 
  is_target_line: false
  target_line_position: 
  gquery: useful_demand_terraced_houses_1965_1984_bar
  is_1990: 
  dependent_on: 
  output_element_key: residential_heating_demand
  key: useful_demand_terraced_houses_1965_1984_bar_residential_heating_demand  
- label: residences_1985_2004
  color: "#DC267F"
  order_by: 340
  group: terraced_houses_bar
  show_at_first: 
  is_target_line: false
  target_line_position: 
  gquery: useful_demand_terraced_houses_1985_2004_bar
  is_1990: 
  dependent_on: 
  output_element_key: residential_heating_demand
  key: useful_demand_terraced_houses_1985_2004_bar_residential_heating_demand
- label: residences_2005_present
  color: "#FE6100"
  order_by: 350
  group: terraced_houses_bar
  show_at_first: 
  is_target_line: false
  target_line_position: 
  gquery: useful_demand_terraced_houses_2005_present_bar
  is_1990: 
  dependent_on: 
  output_element_key: residential_heating_demand
  key: useful_demand_terraced_houses_2005_present_bar_residential_heating_demand  
- label: residences_future
  color: "#FFB000"
  order_by: 360
  group: terraced_houses_bar
  show_at_first: 
  is_target_line: false
  target_line_position: 
  gquery: useful_demand_terraced_houses_future_bar
  is_1990: 
  dependent_on: 
  output_element_key: residential_heating_demand
  key: useful_demand_terraced_houses_future_bar_residential_heating_demand    

- label: residences_before_1945
  color: "#44AA99"
  order_by: 410
  group: total_residences_bar
  show_at_first: 
  is_target_line: false
  target_line_position: 
  gquery: useful_demand_total_residences_before_1945_bar
  is_1990: 
  dependent_on: 
  output_element_key: residential_heating_demand
  key: useful_demand_total_residences_before_1945_bar_residential_heating_demand
- label: residences_1945_1964
  color: "#648FFF"
  order_by: 420
  group: total_residences_bar
  show_at_first: 
  is_target_line: false
  target_line_position: 
  gquery: useful_demand_total_residences_1945_1964_bar
  is_1990: 
  dependent_on: 
  output_element_key: residential_heating_demand
  key: useful_demand_total_residences_1945_1964_bar_residential_heating_demand
- label: residences_1965_1984
  color: "#785EF0"
  order_by: 430
  group: total_residences_bar
  show_at_first: 
  is_target_line: false
  target_line_position: 
  gquery: useful_demand_total_residences_1965_1984_bar
  is_1990: 
  dependent_on: 
  output_element_key: residential_heating_demand
  key: useful_demand_total_residences_1965_1984_bar_residential_heating_demand  
- label: residences_1985_2004
  color: "#DC267F"
  order_by: 440
  group: total_residences_bar
  show_at_first: 
  is_target_line: false
  target_line_position: 
  gquery: useful_demand_total_residences_1985_2004_bar
  is_1990: 
  dependent_on: 
  output_element_key: residential_heating_demand
  key: useful_demand_total_residences_1985_2004_bar_residential_heating_demand
- label: residences_2005_present
  color: "#FE6100"
  order_by: 450
  group: total_residences_bar
  show_at_first: 
  is_target_line: false
  target_line_position: 
  gquery: useful_demand_total_residences_2005_present_bar
  is_1990: 
  dependent_on: 
  output_element_key: residential_heating_demand
  key: useful_demand_total_residences_2005_present_bar_residential_heating_demand  
- label: residences_future
  color: "#FFB000"
  order_by: 460
  group: total_residences_bar
  show_at_first: 
  is_target_line: false
  target_line_position: 
  gquery: useful_demand_total_residences_future_bar
  is_1990: 
  dependent_on: 
  output_element_key: residential_heating_demand
  key: useful_demand_total_residences_future_bar_residential_heating_demand    
