---
- label: agriculture_local_heat
  color: "#8B0000"
  order_by: 100
  group: 
  show_at_first: 
  is_target_line: 
  target_line_position: 
  gquery: local_heat_used_for_heating_in_agriculture
  is_1990: 
  dependent_on: 
  output_element_key: source_of_heat_in_agriculture
  key: local_heat_source_of_heat_in_agriculture
- label: agriculture_central_ht_heat
  color: "#785EF0"
  order_by: 104
  group: 
  show_at_first: 
  is_target_line: 
  target_line_position: 
  gquery: central_ht_heat_used_for_heating_in_agriculture
  is_1990: 
  dependent_on: 
  output_element_key: source_of_heat_in_agriculture
  key: central_ht_heat_source_of_heat_in_agriculture
- label: agriculture_central_mt_heat
  color: "#DC267F"
  order_by: 105
  group: 
  show_at_first: 
  is_target_line: 
  target_line_position: 
  gquery: central_mt_heat_used_for_heating_in_agriculture
  is_1990: 
  dependent_on: 
  output_element_key: source_of_heat_in_agriculture
  key: central_mt_heat_source_of_heat_in_agriculture
- label: agriculture_wasted_heat
  color: "#FF8C8C"
  order_by: 101
  group: 
  show_at_first: 
  is_target_line: 
  target_line_position: 
  gquery: wasted_heat_used_for_heating_in_agriculture
  is_1990: 
  dependent_on: 
  output_element_key: source_of_heat_in_agriculture
  key: wasted_heat_source_of_heat_in_agriculture
- label: biomass_products
  color: "#5D7929"
  order_by: 220
  group: 
  show_at_first: 
  is_target_line: 
  target_line_position: 
  gquery: biomass_products_used_for_heating_in_agriculture
  is_1990: 
  dependent_on: 
  output_element_key: source_of_heat_in_agriculture
  key: biomass_products_source_of_heat_in_agriculture
- label: coal_and_derivatives
  color: "#333333"
  order_by: 200
  group: 
  show_at_first: 
  is_target_line: 
  target_line_position: 
  gquery: coal_and_derivatives_used_for_heating_in_agriculture
  is_1990: 
  dependent_on: 
  output_element_key: source_of_heat_in_agriculture
  key: coal_and_derivatives_source_of_heat_in_agriculture
- label: electricity
  color: "#4169E1"
  order_by: 215
  group: 
  show_at_first: 
  is_target_line: 
  target_line_position: 
  gquery: electricity_used_for_heating_in_agriculture
  is_1990: 
  dependent_on: 
  output_element_key: source_of_heat_in_agriculture
  key: electricity_source_of_heat_in_agriculture
- label: natural_gas_and_derivatives
  color: "#CCCCCC"
  order_by: 205
  group: 
  show_at_first: 
  is_target_line: 
  target_line_position: 
  gquery: natural_gas_and_derivatives_used_for_heating_in_agriculture
  is_1990: 
  dependent_on: 
  output_element_key: source_of_heat_in_agriculture
  key: natural_gas_and_derivatives_source_of_heat_in_agriculture
- label: oil_and_derivatives
  color: "#854321"
  order_by: 210
  group: 
  show_at_first: 
  is_target_line: 
  target_line_position: 
  gquery: oil_and_derivatives_used_for_heating_in_agriculture
  is_1990: 
  dependent_on: 
  output_element_key: source_of_heat_in_agriculture
  key: oil_and_derivatives_source_of_heat_in_agriculture
- label: ambient_heat
  color: "#ADDE4C"
  order_by: 230
  group: agriculture
  show_at_first: 
  is_target_line: 
  target_line_position: 
  gquery: ambient_used_for_heating_in_agriculture
  is_1990: 
  dependent_on: 
  output_element_key: source_of_heat_in_agriculture
  key: ambient_agriculture_source_of_heat_in_agriculture
- label: geothermal
  color: "#FF8400"
  order_by: 235
  group: agriculture
  show_at_first: 
  is_target_line: 
  target_line_position: 
  gquery: geothermal_used_for_heating_in_agriculture
  is_1990: 
  dependent_on: 
  output_element_key: source_of_heat_in_agriculture
  key: geothermal_agriculture_source_of_heat_in_agriculture
- label: solar
  color: "#FFD900"
  order_by: 225
  group: agriculture
  show_at_first: 
  is_target_line: 
  target_line_position: 
  gquery: solar_used_for_heating_in_agriculture
  is_1990: 
  dependent_on: 
  output_element_key: source_of_heat_in_agriculture
  key: solar_agriculture_source_of_heat_in_agriculture
- label: hydrogen
  color: "#87CEEB"
  order_by: 240
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: hydrogen_used_for_heating_in_agriculture
  is_1990: false
  dependent_on: 
  output_element_key: source_of_heat_in_agriculture
  key: hydrogen_source_of_heat_in_agriculture
