---
- label: ammonia_heating
  color: "#00dba1"
  order_by: 10
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: ammonia_used_for_heating_in_households
  is_1990: false
  dependent_on: 
  output_element_key: source_of_heat_used_in_households
  key: ammonia_heating_source_of_heat_used_in_households  
- label: biomass_products_heating
  color: "#2ca02c"
  order_by: 15
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: biomass_products_used_for_heating_in_households
  is_1990: false
  dependent_on: 
  output_element_key: source_of_heat_used_in_households
  key: biomass_products_heating_source_of_heat_used_in_households
- label: coal_and_derivatives_heating
  color: "#252525"
  order_by: 20
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: coal_and_derivatives_used_for_heating_in_households
  is_1990: false
  dependent_on: 
  output_element_key: source_of_heat_used_in_households
  key: coal_and_derivatives_heating_source_of_heat_used_in_households
- label: electricity_heating
  color: "#1f77b4"
  order_by: 25
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: electricity_used_for_heating_in_households
  is_1990: false
  dependent_on: 
  output_element_key: source_of_heat_used_in_households
  key: electricity_heating_source_of_heat_used_in_households
- label: greengas_heating
  color: "#A3CB38"
  order_by: 30
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: greengas_used_for_heating_in_households
  is_1990: false
  dependent_on: 
  output_element_key: source_of_heat_used_in_households
  key: greengas_heating_source_of_heat_used_in_households    
- label: heat_network_heating
  color: "#cc0000"
  order_by: 35
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: heat_used_for_heating_in_households
  is_1990: false
  dependent_on: 
  output_element_key: source_of_heat_used_in_households
  key: heat_network_heating_source_of_heat_used_in_households
- label: hydrogen_heating
  color: "#87cfeb"
  order_by: 40
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: hydrogen_used_for_heating_in_households
  is_1990: false
  dependent_on: 
  output_element_key: source_of_heat_used_in_households
  key: hydrogen_heating_source_of_heat_used_in_households  
- label: natural_gas_and_derivatives_heating
  color: "#7f7f7f"
  order_by: 45
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: natural_gas_and_derivatives_used_for_heating_in_households
  is_1990: false
  dependent_on: 
  output_element_key: source_of_heat_used_in_households
  key: natural_gas_and_derivatives_heating_source_of_heat_used_in_households
- label: oil_and_derivatives_heating
  color: "#8c564b"
  order_by: 50
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: oil_and_derivatives_used_for_heating_in_households
  is_1990: false
  dependent_on: 
  output_element_key: source_of_heat_used_in_households
  key: oil_and_derivatives_heating_source_of_heat_used_in_households
- label: solar_thermal_heating
  color: "#ffcc00"
  order_by: 55
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: solar_used_for_heating_in_households
  is_1990: false
  dependent_on: ''
  output_element_key: source_of_heat_used_in_households
  key: solar_thermal_heating_source_of_heat_used_in_households



- label: ammonia_hot_water
  color: "#00dba1"
  order_by: 10
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: ammonia_used_for_hot_water_in_households
  is_1990: false
  dependent_on: 
  output_element_key: source_of_heat_used_in_households
  key: ammonia_hot_water_source_of_heat_used_in_households  
- label: biomass_products_hot_water
  color: "#2ca02c"
  order_by: 15
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: biomass_products_used_for_hot_water_in_households
  is_1990: false
  dependent_on: 
  output_element_key: source_of_heat_used_in_households
  key: biomass_products_hot_water_source_of_heat_used_in_households
- label: coal_and_derivatives_hot_water
  color: "#252525"
  order_by: 20
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: coal_and_derivatives_used_for_hot_water_in_households
  is_1990: false
  dependent_on: 
  output_element_key: source_of_heat_used_in_households
  key: coal_and_derivatives_hot_water_source_of_heat_used_in_households
- label: electricity_hot_water
  color: "#1f77b4"
  order_by: 25
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: electricity_used_for_hot_water_in_households
  is_1990: false
  dependent_on: 
  output_element_key: source_of_heat_used_in_households
  key: electricity_hot_water_source_of_heat_used_in_households
- label: greengas_hot_water
  color: "#A3CB38"
  order_by: 30
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: greengas_used_for_hot_water_in_households
  is_1990: false
  dependent_on: 
  output_element_key: source_of_heat_used_in_households
  key: greengas_hot_water_source_of_heat_used_in_households    
- label: heat_network_hot_water
  color: "#cc0000"
  order_by: 35
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: heat_used_for_hot_water_in_households
  is_1990: false
  dependent_on: 
  output_element_key: source_of_heat_used_in_households
  key: heat_network_hot_water_source_of_heat_used_in_households
- label: hydrogen_hot_water
  color: "#87cfeb"
  order_by: 40
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: hydrogen_used_for_hot_water_in_households
  is_1990: false
  dependent_on: 
  output_element_key: source_of_heat_used_in_households
  key: hydrogen_hot_water_source_of_heat_used_in_households  
- label: natural_gas_and_derivatives_hot_water
  color: "#7f7f7f"
  order_by: 45
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: natural_gas_and_derivatives_used_for_hot_water_in_households
  is_1990: false
  dependent_on: 
  output_element_key: source_of_heat_used_in_households
  key: natural_gas_and_derivatives_hot_water_source_of_heat_used_in_households
- label: oil_and_derivatives_hot_water
  color: "#8c564b"
  order_by: 50
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: oil_and_derivatives_used_for_hot_water_in_households
  is_1990: false
  dependent_on: 
  output_element_key: source_of_heat_used_in_households
  key: oil_and_derivatives_hot_water_source_of_heat_used_in_households
- label: solar_thermal_hot_water
  color: "#ffcc00"
  order_by: 55
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: solar_used_for_hot_water_in_households
  is_1990: false
  dependent_on: ''
  output_element_key: source_of_heat_used_in_households
  key: solar_thermal_hot_water_source_of_heat_used_in_households
