---
- label: production
  color: "#ffc04f"
  order_by: 10
  group: electricity
  gquery: system_costs_production_of_electricity
  output_element_key: system_costs_per_carrier
  key: production_electricity_system_costs_per_carrier
- label: infrastructure
  color: "#4f8eff"
  order_by: 20
  group: electricity
  gquery: system_costs_infrastructure_of_electricity
  output_element_key: system_costs_per_carrier
  key: infrastructure_electricity_system_costs_per_carrier
- label: flexibility
  color: "#ff4f8e"
  order_by: 30
  group: electricity
  gquery: system_costs_flexibility_of_electricity
  output_element_key: system_costs_per_carrier
  key: flexibility_electricity_system_costs_per_carrier
- label: production
  color: "#ffc04f"
  order_by: 40
  group: heat
  gquery: system_costs_production_of_heat
  output_element_key: system_costs_per_carrier
  key: production_heat_system_costs_per_carrier
- label: infrastructure
  color: "#4f8eff"
  order_by: 50
  group: heat
  gquery: system_costs_infrastructure_of_heat
  output_element_key: system_costs_per_carrier
  key: infrastructure_heat_system_costs_per_carrier
- label: flexibility
  color: "#ff4f8e"
  order_by: 60
  group: heat
  gquery: system_costs_flexibility_of_heat
  output_element_key: system_costs_per_carrier
  key: flexibility_heat_system_costs_per_carrier
- label: production
  color: "#ffc04f"
  order_by: 70
  group: hydrogen
  gquery: system_costs_production_of_hydrogen
  output_element_key: system_costs_per_carrier
  key: production_hydrogen_system_costs_per_carrier
- label: infrastructure
  color: "#4f8eff"
  order_by: 80
  group: hydrogen
  gquery: system_costs_infrastructure_of_hydrogen
  output_element_key: system_costs_per_carrier
  key: infrastructure_hydrogen_system_costs_per_carrier
- label: flexibility
  color: "#ff4f8e"
  order_by: 90
  group: hydrogen
  gquery: system_costs_flexibility_of_hydrogen
  output_element_key: system_costs_per_carrier
  key: flexibility_hydrogen_system_costs_per_carrier
- label: production
  color: "#ffc04f"
  order_by: 40
  group: network_gas
  gquery: system_costs_production_of_network_gas
  output_element_key: system_costs_per_carrier
  key: production_network_gas_system_costs_per_carrier
- label: infrastructure
  color: "#4f8eff"
  order_by: 50
  group: network_gas
  gquery: system_costs_infrastructure_of_network_gas
  output_element_key: system_costs_per_carrier
  key: infrastructure_network_gas_system_costs_per_carrier
- label: flexibility
  color: "#ff4f8e"
  order_by: 60
  group: network_gas
  gquery: system_costs_flexibility_of_network_gas
  output_element_key: system_costs_per_carrier
  key: flexibility_network_gas_system_costs_per_carrier
