---
- label: appliances
  color: "#44AA99"
  order_by: 100
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: appliances_demand_in_use_of_final_demand_in_households
  is_1990: false
  dependent_on: 
  output_element_key: use_of_final_demand_in_households
  key: electrical_appliances_use_of_final_demand_in_households
  key: heat_demand_households_use_of_final_demand_in_households
- label: cooking_demand
  color: "#648FFF"
  order_by: 105
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: cooking_demand_in_use_of_final_demand_in_households
  is_1990: false
  dependent_on: 
  output_element_key: use_of_final_demand_in_households
  key: cooking_demand_use_of_final_demand_in_households  
- label: cooling_demand
  color: "#785EF0"
  order_by: 110
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: cooling_demand_in_use_of_final_demand_in_households
  is_1990: false
  dependent_on: 
  output_element_key: use_of_final_demand_in_households
  key: cooling_demand_use_of_final_demand_in_households
- label: hot_water_demand
  color: "#DC267F"
  order_by: 115
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: hot_water_demand_in_use_of_final_demand_in_households
  is_1990: false
  dependent_on: 
  output_element_key: use_of_final_demand_in_households
  key: hot_water_demanduse_of_final_demand_in_households
- label: lighting
  color: "#FE6100"
  order_by: 120
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: lighting_demand_in_use_of_final_demand_in_households
  is_1990: false
  dependent_on: 
  output_element_key: use_of_final_demand_in_households
  key: lighting_use_of_final_demand_in_households
- label: space_heating
  color: "#FFB000"
  order_by: 125
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: space_heating_demand_in_use_of_final_demand_in_households
  is_1990: false
  dependent_on: 
  output_element_key: use_of_final_demand_in_households  
  key: space_heating_use_of_final_demand_in_households

