---
- label: ammonia
  color: "#44AA99" 
  order_by: 10 
  group: future
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: ammonia_in_future_energy_transit
  is_1990: false
  dependent_on: 
  output_element_key: waterfall_future_energy_transit_flows
  key: ammonia_future_energy_transit_flows

- label: biomass_products
  color: "#117733" 
  order_by: 20
  group: future
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: biomass_products_in_future_energy_transit
  is_1990: false
  dependent_on: 
  output_element_key: waterfall_future_energy_transit_flows
  key: biomass_future_energy_transit_flows

- label: coal_and_coal_products 
  color: "#CC6677" 
  order_by: 30
  group: future
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: coal_and_coal_products_in_future_energy_transit
  is_1990: false
  dependent_on: 
  output_element_key: waterfall_future_energy_transit_flows
  key: coal_future_energy_transit_flows

- label: crude_oil
  color: "#8c564b" 
  order_by: 40
  group: future
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: crude_oil_in_future_energy_transit
  is_1990: false
  dependent_on: 
  output_element_key: waterfall_future_energy_transit_flows
  key: crude_oil_future_energy_transit_flows

- label: electricity
  color: "#332288" 
  order_by: 50
  group: future
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: electricity_in_future_energy_transit
  is_1990: false
  dependent_on: 
  output_element_key: waterfall_future_energy_transit_flows
  key: electricity_future_energy_transit_flows

- label: heat 
  color: "#882255"
  order_by: 60
  group: future
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: heat_in_future_energy_transit
  is_1990: false
  dependent_on: 
  output_element_key: waterfall_future_energy_transit_flows
  key: heat_future_energy_transit_flows

- label: hydrogen_gaseous 
  color: "#88CCEE"
  order_by: 70
  group: future
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: hydrogen_gaseous_in_future_energy_transit
  is_1990: false
  dependent_on: 
  output_element_key: waterfall_future_energy_transit_flows
  key: hydrogen_gaseous_future_energy_transit_flows

- label: hydrogen_liquid
  color: "#88CCEE" 
  order_by: 80
  group: future
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: hydrogen_liquid_in_future_energy_transit
  is_1990: false
  dependent_on: 
  output_element_key: waterfall_future_energy_transit_flows
  key: hydrogen_liquid_future_energy_transit_flows

- label: hydrogen_lohc
  color: "#88CCEE" 
  order_by: 90
  group: future
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: hydrogen_lohc_in_future_energy_transit
  is_1990: false
  dependent_on: 
  output_element_key: waterfall_future_energy_transit_flows
  key: hydrogen_lohc_future_energy_transit_flows

- label: lng 
  color: "#7f7f7f" 
  order_by: 100
  group: future
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: lng_in_future_energy_transit
  is_1990: false
  dependent_on: 
  output_element_key: waterfall_future_energy_transit_flows
  key: lng_future_energy_transit_flows

- label: natural_gas
  color: "#7f7f7f" 
  order_by: 110
  group: future
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: natural_gas_in_future_energy_transit
  is_1990: false
  dependent_on: 
  output_element_key: waterfall_future_energy_transit_flows
  key: natural_gas_future_energy_transit_flows

- label: non_biogenic_waste
  color: "#7f7f7f" 
  order_by: 120
  group: future
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: non_biogenic_waste_in_future_energy_transit
  is_1990: false
  dependent_on: 
  output_element_key: waterfall_future_energy_transit_flows
  key: non_biogenic_waste_future_energy_transit_flows  

- label: oil_products
  color: "#8c564b" 
  order_by: 130
  group: future
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: oil_products_in_future_energy_transit
  is_1990: false
  dependent_on: 
  output_element_key: waterfall_future_energy_transit_flows
  key: oil_products_future_energy_transit_flows  

- label: uranium_oxide
  color: "#AA4499" 
  order_by: 140
  group: future
  show_at_first: false
  is_target_line: false
  target_line_position: ''
  gquery: uranium_oxide_in_future_energy_transit
  is_1990: false
  dependent_on: 
  output_element_key: waterfall_future_energy_transit_flows
  key: uranium_oxide_future_energy_transit_flows    