---
- key: supply_ccus_capture_overview
  position: 100
  sidebar_item_key: ccus
  output_element_key: mekko_of_co2_demand_supply
- key: supply_ccus_capture_energy
  position: 105
  sidebar_item_key: ccus
  output_element_key: waterfall_captured_emissions
- key: supply_ccus_capture_industry
  group_sub_header: of_potential
  position: 110
  sidebar_item_key: ccus
  output_element_key: ccus_sankey
- key: supply_ccus_capture_import
  position: 115
  sidebar_item_key: ccus
  output_element_key: mekko_of_co2_demand_supply
- key: supply_ccus_utilisation_storage
  group_sub_header: per_year
  position: 120
  sidebar_item_key: ccus
  output_element_key: ccus_sankey
- key: supply_ccus_transport
  position: 125
  sidebar_item_key: ccus
  output_element_key: ccus_sankey
