---
- general_sub_header: change
  key: costs_combustion_investment
  position: 2
  sidebar_item_key: combustion
  output_element_key: costs_overview_detailed
- general_sub_header: change
  key: costs_combustion_operational_and_maintenance
  position: 3
  sidebar_item_key: combustion
  output_element_key: costs_overview_detailed
- general_sub_header: change
  key: costs_combustion_efficiency
  position: 4
  sidebar_item_key: combustion
  output_element_key: costs_overview_detailed