---
- key: data_visuals_scenario_report
  position: 10
  sidebar_item_key: data_visuals
  output_element_key: final_demand_mekko_energetic_mece
- key: data_visuals_land_use_solar_wind
  position: 15
  sidebar_item_key: data_visuals
  output_element_key: land_use_solar_wind_chart
- key: data_visuals_energy_mix
  position: 20
  sidebar_item_key: data_visuals
  dependent_on: has_offshore_solar    # only true for NL regions so energy mix only visible for NL regions
  output_element_key: final_demand_mekko_energetic_mece
- key: data_visuals_co2_sheet
  position: 30
  sidebar_item_key: data_visuals
  output_element_key: co2_emissions
- key: data_visuals_graph
  position: 40
  sidebar_item_key: data_visuals
  output_element_key: final_energy_demand_per_sector_joule
- key: data_visuals_molecule_graph
  position: 50
  sidebar_item_key: data_visuals
  output_element_key: mekko_of_co2_demand_supply
