---
- key: emissions_emission_factors_imported_heat
  position: 1
  sidebar_item_key: emission_factors
  output_element_key: sankey_heat_networks
- key: emissions_emission_factors_hydrogen_co2_import
  position: 2
  sidebar_item_key: emission_factors
  output_element_key: co2_intensity_of_hydrogen_production
- key: emissions_emission_factors_ammonia_co2_import
  position: 3
  sidebar_item_key: emission_factors
  output_element_key: co2_intensity_of_hydrogen_production