---
- key: flexibility_electricity_conversion_overview
  position: 1
  sidebar_item_key: flexibility_conversion
  output_element_key: use_of_excess_electricity
- group_sub_header: electricity_input
  key: flexibility_flexibility_power_to_gas
  position: 2
  sidebar_item_key: flexibility_conversion
  output_element_key: source_of_electricity_in_p2g
- group_sub_header: heat_output
  key: flexibility_flexibility_power_to_heat_for_district_heating
  position: 3
  sidebar_item_key: flexibility_conversion
  output_element_key: flexibility_integral_costs
- group_sub_header: consumption_price
  key: flexibility_flexibility_power_to_heat_for_industry
  position: 4
  sidebar_item_key: flexibility_conversion
  output_element_key: storage_options
- group_sub_header: consumption_price
  key: flexibility_flexibility_power_to_heat_for_agriculture
  position: 5
  sidebar_item_key: flexibility_conversion
  output_element_key: storage_options
- group_sub_header: consumption_price
  key: flexibility_flexibility_energy_production_synthetic_kerosene
  position: 5
  sidebar_item_key: flexibility_conversion
  output_element_key: mekko_of_kerosene_demand_supply
