---
- group_sub_header: fuel_production
  key: supply_fuel_production_overview
  position: 100
  sidebar_item_key: fuel_production
  output_element_key: refinery
- group_sub_header: fuel_production
  key: supply_fuel_fossil_refinery
  position: 110
  sidebar_item_key: fuel_production
  output_element_key: refinery
- group_sub_header: output_share
  key: supply_fuel_production_fischer_tropsch
  position: 120
  sidebar_item_key: fuel_production
  output_element_key: refinery
- group_sub_header: output_share
  key: supply_fuel_production_methanol_synthesis
  position: 130
  sidebar_item_key: fuel_production
  output_element_key: refinery
- group_sub_header: fuel_production
  key: supply_fuel_production_pyrolysis
  position: 140
  sidebar_item_key: fuel_production
  output_element_key: refinery
