---
- key: supply_fuel_production_overview
  position: 100
  sidebar_item_key: fuel_production
  output_element_key: waterfall_future_energy_imports
- key: supply_fuel_production_fischer_tropsch
  position: 110
  sidebar_item_key: fuel_production
  output_element_key: waterfall_future_energy_imports
- key: supply_fuel_production_methanol_synthesis
  position: 120
  sidebar_item_key: fuel_production
  output_element_key: waterfall_future_energy_imports
- key: supply_fuel_production_pyrolysis
  position: 130
  sidebar_item_key: fuel_production
  output_element_key: waterfall_future_energy_imports
