---
- key: supply_heat_overview
  position: 1
  sidebar_item_key: heat
  output_element_key: sankey_heat_networks
- key: supply_heat_overview_chp
  position: 2
  sidebar_item_key: heat
  output_element_key: sankey_heat_networks
- key: supply_heat_overview_emissions
  position: 4
  sidebar_item_key: heat
  output_element_key: sankey_heat_networks
- key: supply_heat_overview_residual
  position: 3
  sidebar_item_key: heat
  output_element_key: sankey_heat_networks
