---
- key: sources_mt
  position: 1
  sidebar_item_key: heat_mt
  output_element_key: collective_heat_mekko
- key: storage_mt
  position: 2
  sidebar_item_key: heat_mt
  output_element_key: collective_heat_mekko
- key: transport_mt
  position: 3
  sidebar_item_key: heat_mt
  output_element_key: collective_heat_mekko
- key: supply_heat_network_order_mt
  position: 4
  sidebar_item_key: heat_mt
  output_element_key: heat_cost_capacity