---
- key: supply_heat_overview
  position: 100
  sidebar_item_key: heat
  output_element_key: sankey_heat_networks
- key: supply_heat_overview_chp
  position: 200
  sidebar_item_key: heat
  output_element_key: sankey_heat_networks
- key: supply_heat_overview_p2h
  position: 300
  sidebar_item_key: heat
  output_element_key: sankey_heat_networks
- key: supply_heat_overview_emissions
  position: 400
  sidebar_item_key: heat
  output_element_key: sankey_heat_networks
