---
- key: sources_lt
  position: 1
  sidebar_item_key: heat_lt
  output_element_key: collective_heat_mekko
- key: storage_lt
  position: 2
  sidebar_item_key: heat_lt
  output_element_key: collective_heat_mekko
- key: transport_lt
  position: 3
  sidebar_item_key: heat_lt
  output_element_key: collective_heat_mekko