---
- key: sources_ht
  position: 1
  sidebar_item_key: heat_ht
  output_element_key: collective_heat_mekko
- key: storage_ht
  position: 2
  sidebar_item_key: heat_ht
  output_element_key: collective_heat_mekko
- key: transport_ht
  position: 3
  sidebar_item_key: heat_ht
  output_element_key: collective_heat_mekko
- key: supply_heat_network_order_ht
  position: 4
  sidebar_item_key: heat_ht
  output_element_key: heat_cost_capacity
