---
- key: supply_heat_sources
  position: 1
  sidebar_item_key: heat
  output_element_key: collective_heat_mekko
- key: waste_burner
  position: 2
  sidebar_item_key: heat
  output_element_key: collective_heat_mekko
- key: aquathermal
  position: 3
  sidebar_item_key: heat
  output_element_key: collective_heat_mekko
- key: biomass_burner
  position: 4
  sidebar_item_key: heat
  output_element_key: collective_heat_mekko
- key: e_boiler_hp
  position: 5
  sidebar_item_key: heat
  output_element_key: collective_heat_mekko
- key: geothermal_heat
  position: 6
  sidebar_item_key: heat
  output_element_key: collective_heat_mekko
- key: solar_thermal
  position: 7
  sidebar_item_key: heat
  output_element_key: collective_heat_mekko
- key: hydrogen_burner
  position: 8
  sidebar_item_key: heat
  output_element_key: collective_heat_mekko
- key: network_gas_burner
  position: 9
  sidebar_item_key: heat
  output_element_key: collective_heat_mekko
- key: coal_burner
  position: 10
  sidebar_item_key: heat
  output_element_key: collective_heat_mekko
- key: oil_burner
  position: 11
  sidebar_item_key: heat
  output_element_key: collective_heat_mekko
- key: chp_heat
  position: 12
  sidebar_item_key: heat
  output_element_key: collective_heat_mekko
- key: residual_heat
  position: 13
  sidebar_item_key: heat
  output_element_key: collective_heat_mekko
- key: import_heat
  position: 14
  sidebar_item_key: heat
  output_element_key: collective_heat_mekko
- key: supply_heat_network_storage_toggle
  position: 15
  sidebar_item_key: heat
  output_element_key: heat_network_storage
