---
- key: supply_heat_sources_lt
  position: 1
  sidebar_item_key: heat_lt
  output_element_key: collective_heat_mekko
- key: supply_heat_storage_lt
  position: 2
  sidebar_item_key: heat_lt
  output_element_key: collective_heat_mekko
- key: supply_heat_transport_lt
  position: 3
  sidebar_item_key: heat_lt
  output_element_key: collective_heat_mekko
- key: supply_heat_network_order_lt
  position: 4
  sidebar_item_key: heat_lt
  output_element_key: heat_cost_capacity