---
- general_sub_header: heat output
  key: demand_households_heating_technologies
  position: 100
  sidebar_item_key: households_heating_order
  output_element_key: households_deficits
- key: demand_households_heating_producers_order
  position: 200
  sidebar_item_key: households_heating_order
  output_element_key: households_deficits
