---
- key: specs_transport_efficiency_improvement
  image: car_engine.gif
  general_sub_header: "%/year"
  position: 2
  sidebar_item_key: specs_transport
  output_element_key: transport_categories_overview
