---
- under_construction: false
  unit: euro
  percentage: false
  group: Cost
  sub_group: 
  show_point_label: false
  growth_chart: false
  key: system_costs_per_carrier
  max_axis_value:
  min_axis_value:
  hidden: true
  requires_merit_order: false
  dependent_on: ''
  output_element_type_name: category_bar