---
- under_construction: false
  unit: "%"
  percentage: true
  group: Demand
  sub_group: overview
  show_point_label: true
  growth_chart: false
  key: final_energy_demand_per_sector_percentage
  max_axis_value: 1.0
  min_axis_value: 0.0
  hidden: false
  requires_merit_order: false
  dependent_on: ''
  output_element_type_name: vertical_stacked_bar
- under_construction: false
  unit: PJ
  config:
    period: future
    y_precision: 0
  percentage: false
  group: Demand
  sub_group: overview
  show_point_label: false
  growth_chart: false
  key: heat_aquathermal_demand
  max_axis_value: 
  min_axis_value: 
  hidden: false
  requires_merit_order: false
  dependent_on: ''
  output_element_type_name: category_bar