---
- under_construction: false
  unit: PJ
  percentage: false
  group: Demand
  sub_group: export
  show_point_label: true
  growth_chart: false
  key: future_energy_transit_flows
  max_axis_value: 
  min_axis_value: 
  hidden: false
  requires_merit_order: false
  dependent_on: ''
  output_element_type_name: waterfall