---
- key: investment_costs_co2_ccs
  step_value: 1.0
  unit: "%"
  position: 100
  slide_key: costs_co2_capture_energy
- key: om_costs_co2_ccs
  step_value: 1.0
  unit: "%"
  position: 200
  slide_key: costs_co2_capture_energy
