---
- key: costs_hydrogen
  step_value: 1.0
  unit: "€/MWh"
  command_type: value
  position: 1
  slide_key: costs_hydrogen_import
- key: costs_imported_liquid_hydrogen
  step_value: 1.0
  unit: "€/MWh"
  command_type: value
  position: 1
  slide_key: costs_hydrogen_import
- key: costs_imported_lohc
  step_value: 1.0
  unit: "€/MWh"
  command_type: value
  position: 1
  slide_key: costs_hydrogen_import
- key: costs_imported_ammonia
  step_value: 1.0
  unit: "€/MWh"
  command_type: value
  position: 1
  slide_key: costs_hydrogen_import
