---
- key: investment_costs_fischer_tropsch
  interface_group: costs_fischer_tropsch
  step_value: 1.0
  unit: "%"
  position: 100
  slide_key: costs_fuel_production_processes
- key: om_costs_fischer_tropsch
  interface_group: costs_fischer_tropsch
  step_value: 1.0
  unit: "%"
  position: 110
  slide_key: costs_fuel_production_processes
- key: investment_costs_methanol_synthesis
  interface_group: costs_methanol_synthesis
  step_value: 1.0
  unit: "%"
  position: 120
  slide_key: costs_fuel_production_processes
- key: om_costs_methanol_synthesis
  interface_group: costs_methanol_synthesis
  step_value: 1.0
  unit: "%"
  position: 130
  slide_key: costs_fuel_production_processes
- key: investment_costs_fractionation_pyrolysis_oil
  interface_group: costs_fractionation_pyrolysis_oil
  step_value: 1.0
  unit: "%"
  position: 140
  slide_key: costs_fuel_production_processes
- key: om_costs_fractionation_pyrolysis_oil
  interface_group: costs_fractionation_pyrolysis_oil
  step_value: 1.0
  unit: "%"
  position: 150
  slide_key: costs_fuel_production_processes
- key: investment_costs_pyrolysis
  interface_group: costs_pyrolysis
  step_value: 1.0
  unit: "%"
  position: 160
  slide_key: costs_fuel_production_processes
- key: om_costs_pyrolysis
  interface_group: costs_pyrolysis
  step_value: 1.0
  unit: "%"
  position: 170
  slide_key: costs_fuel_production_processes
- key: investment_costs_hvo
  interface_group: costs_hvo
  step_value: 1.0
  unit: "%"
  position: 180
  slide_key: costs_fuel_production_processes
- key: om_costs_hvo
  interface_group: costs_hvo
  step_value: 1.0
  unit: "%"
  position: 190
  slide_key: costs_fuel_production_processes
- key: investment_costs_bio_ethanol
  interface_group: costs_bio_ethanol
  step_value: 1.0
  unit: "%"
  position: 200
  slide_key: costs_fuel_production_processes
- key: om_costs_bio_ethanol
  interface_group: costs_bio_ethanol
  step_value: 1.0
  unit: "%"
  position: 210
  slide_key: costs_fuel_production_processes
