---
- key: investment_costs_households_flexibility_p2p_electricity
  interface_group: investment_costs
  step_value: 1.0
  unit: "%"
  related_node: households_flexibility_p2p_electricity
  position: 100
  slide_key: costs_flexibility_storage
- key: investment_costs_energy_flexibility_mv_batteries_electricity
  interface_group: investment_costs
  step_value: 1.0
  unit: "%"
  related_node: energy_flexibility_mv_batteries_electricity
  position: 105
  slide_key: costs_flexibility_storage
- key: investment_costs_energy_flexibility_hv_opac_electricity
  interface_group: investment_costs
  step_value: 1.0
  unit: "%"
  related_node: energy_flexibility_hv_opac_electricity
  position: 110
  slide_key: costs_flexibility_storage
- key: capacity_costs_energy_flexibility_flow_batteries_electricity
  interface_group: investment_costs
  step_value: 1.0
  unit: "%"
  related_node: energy_flexibility_flow_batteries_electricity
  position: 115
  slide_key: costs_flexibility_storage
- key: volume_costs_energy_flexibility_flow_batteries_electricity
  interface_group: investment_costs
  step_value: 1.0
  unit: "%"
  related_node: energy_flexibility_flow_batteries_electricity
  position: 115
  slide_key: costs_flexibility_storage

- key: efficiency_households_flexibility_p2p_electricity
  interface_group: roundtrip_efficiency
  step_value: 1.0
  unit: "%"
  related_node: households_flexibility_p2p_electricity
  position: 200
  slide_key: costs_flexibility_storage
- key: efficiency_transport_flexibility_p2p_electricity
  interface_group: roundtrip_efficiency
  step_value: 1.0
  unit: "%"
  related_node: transport_car_flexibility_p2p_electricity
  position: 205
  slide_key: costs_flexibility_storage
- key: efficiency_energy_flexibility_mv_batteries_electricity
  interface_group: roundtrip_efficiency
  step_value: 1.0
  unit: "%"
  related_node: energy_flexibility_mv_batteries_electricity
  position: 210
  slide_key: costs_flexibility_storage
- key: efficiency_energy_flexibility_pumped_storage_electricity
  interface_group: roundtrip_efficiency
  dependent_on: has_mountains
  step_value: 1.0
  unit: "%"
  related_node: energy_flexibility_pumped_storage_electricity
  position: 215
  slide_key: costs_flexibility_storage
- key: efficiency_energy_flexibility_hv_opac_electricity
  interface_group: roundtrip_efficiency
  step_value: 1.0
  unit: "%"
  related_node: energy_flexibility_hv_opac_electricity
  position: 220
  slide_key: costs_flexibility_storage
- key: efficiency_energy_flexibility_flow_batteries_electricity
  interface_group: roundtrip_efficiency
  step_value: 1.0
  unit: "%"
  related_node: energy_flexibility_flow_batteries_electricity
  position: 225
  slide_key: costs_flexibility_storage
