---
- key: investment_costs_electric_heat_pumps
  interface_group: heat_pumps
  step_value: 1.0
  unit: "%"
  related_node: households_space_heater_heatpump_ground_water_electricity
  position: 1
  slide_key: costs_heat_sources_other
- key: investment_costs_gas_heat_pumps
  interface_group: heat_pumps
  step_value: 1.0
  unit: "%"
  related_node: buildings_space_heater_heatpump_air_water_network_gas
  position: 2
  slide_key: costs_heat_sources_other
- key: investment_costs_geothermal
  interface_group: geothermal
  step_value: 1.0
  unit: "%"
  related_node: energy_heat_well_geothermal
  position: 3
  slide_key: costs_heat_sources_other
- key: om_costs_geothermal
  interface_group: geothermal
  step_value: 1.0
  unit: "%"
  related_node: energy_heat_well_geothermal
  position: 4
  slide_key: costs_heat_sources_other
- key: investment_costs_solar_thermal
  interface_group: solar_thermal
  step_value: 1.0
  unit: "%"
  related_node: energy_heat_solar_thermal
  position: 5
  slide_key: costs_heat_sources_other
- key: om_costs_solar_thermal
  interface_group: solar_thermal
  step_value: 1.0
  unit: "%"
  related_node: energy_heat_solar_thermal
  position: 6
  slide_key: costs_heat_sources_other
- key: costs_imported_heat
  interface_group: residual_heat
  step_value: 0.1
  unit: "€/GJ"
  position: 7
  slide_key: costs_heat_sources_other
- key: costs_industry_residual_heat
  interface_group: residual_heat
  step_value: 0.1
  unit: "%"
  position: 8
  slide_key: costs_heat_sources_other
- key: costs_households_ht_heat_delivery_system_costs_apartments_eur_per_connection
  interface_group: heat_delivery_system
  step_value: 100
  unit: "€/connection"
  position: 9
  slide_key: costs_heat_sources_other
- key: costs_households_mt_heat_delivery_system_costs_apartments_eur_per_connection
  interface_group: heat_delivery_system
  step_value: 100
  unit: "€/connection"
  position: 10
  slide_key: costs_heat_sources_other
- key: costs_households_lt_heat_delivery_system_costs_apartments_eur_per_connection
  interface_group: heat_delivery_system
  step_value: 100
  unit: "€/connection"
  position: 11
  slide_key: costs_heat_sources_other
- key: costs_households_ht_heat_delivery_system_costs_ground_level_houses_eur_per_connection
  interface_group: heat_delivery_system
  step_value: 100
  unit: "€/connection"
  position: 12
  slide_key: costs_heat_sources_other
- key: costs_households_mt_heat_delivery_system_costs_ground_level_houses_eur_per_connection
  interface_group: heat_delivery_system
  step_value: 100
  unit: "€/connection"
  position: 13
  slide_key: costs_heat_sources_other
- key: costs_households_lt_heat_delivery_system_costs_ground_level_houses_eur_per_connection
  interface_group: heat_delivery_system
  step_value: 100
  unit: "€/connection"
  position: 14
  slide_key: costs_heat_sources_other
- key: costs_buildings_ht_heat_delivery_system_costs_eur_per_connection
  interface_group: heat_delivery_system
  step_value: 100
  unit: "€/connection"
  position: 15
  slide_key: costs_heat_sources_other
- key: costs_buildings_mt_heat_delivery_system_costs_eur_per_connection
  interface_group: heat_delivery_system
  step_value: 100
  unit: "€/connection"
  position: 16
  slide_key: costs_heat_sources_other
- key: costs_buildings_lt_heat_delivery_system_costs_eur_per_connection
  interface_group: heat_delivery_system
  step_value: 100
  unit: "€/connection"
  position: 17
  slide_key: costs_heat_sources_other