- key: land_use_impact_visual_wind_inland_large_scale
  share_group: wind_turbines_inland_scale
  step_value: 0.1
  unit: "%"
  position: 1
  slide_key: data_visuals_land_use_solar_wind
- key: land_use_impact_visual_wind_inland_small_scale
  share_group: wind_turbines_inland_scale
  step_value: 0.1
  unit: "%"
  position: 2
  slide_key: data_visuals_land_use_solar_wind