---
- key: households_behavior_standby_killer_turn_off_appliances
  step_value: 0.1
  unit: "%"
  position: 100
  slide_key: demand_households_behaviour
- key: households_behavior_turn_off_the_light
  step_value: 0.1
  unit: "%"
  position: 105
  slide_key: demand_households_behaviour
- key: households_behavior_low_temperature_washing
  step_value: 0.1
  unit: "%"
  position: 110
  slide_key: demand_households_behaviour
