---
- key: buildings_number_of_buildings_present
  step_value: 1.0
  unit: "#"
  position: 100
  slide_key: demand_buildings_stock
- key: buildings_number_of_buildings_future
  step_value: 1.0
  unit: "#"
  position: 105
  slide_key: demand_buildings_stock
