---
- key: households_heater_network_gas_heat_output_capacity
  step_value: 0.1
  unit: "kW"
  related_node: households_space_heater_network_gas
  position: 15
  slide_key: demand_households_heating_technologies 
- key: households_heater_combined_network_gas_heat_output_capacity
  step_value: 0.1
  unit: "kW"
  related_node: households_space_heater_combined_network_gas
  position: 20
  slide_key: demand_households_heating_technologies
- key: households_heater_combined_hydrogen_heat_output_capacity
  step_value: 0.1
  unit: "kW"
  related_node: households_space_heater_combined_hydrogen
  position: 25
  slide_key: demand_households_heating_technologies
- key: households_heater_wood_pellets_heat_output_capacity
  step_value: 0.1
  unit: "kW"
  related_node: households_space_heater_wood_pellets
  position: 30
  slide_key: demand_households_heating_technologies
- key: households_heater_electricity_heat_output_capacity
  step_value: 0.1
  unit: "kW"
  related_node: households_space_heater_electricity
  position: 35
  slide_key: demand_households_heating_technologies
- key: households_heater_heatpump_air_water_electricity_heat_output_capacity
  step_value: 0.1
  unit: "kW"
  related_node: households_space_heater_air_water_electricity
  position: 40
  slide_key: demand_households_heating_technologies
- key: households_heater_heatpump_ground_water_electricity_heat_output_capacity
  step_value: 0.1
  unit: "kW"
  related_node: households_space_heater_ground_water_electricity
  position: 45
  slide_key: demand_households_heating_technologies
- key: households_heater_heatpump_surface_water_water_ts_electricity_heat_output_capacity
  step_value: 0.1
  unit: "kW"
  related_node: households_space_heater_eatpump_surface_water_water_ts_electricity
  position: 50
  slide_key: demand_households_heating_technologies
- key: households_heater_heatpump_pvt_electricity_heat_output_capacity
  step_value: 0.1
  unit: "kW"
  related_node: households_space_heater_heatpump_pvt_electricity
  position: 55
  slide_key: demand_households_heating_technologies
- key: households_heater_district_heating_lt_steam_hot_water_heat_output_capacity
  step_value: 0.1
  unit: "kW"
  related_node: households_space_heater_district_heating_lt_steam_hot_water
  position: 60
  slide_key: demand_households_heating_technologies
- key: households_heater_district_heating_mt_steam_hot_water_heat_output_capacity
  step_value: 0.1
  unit: "kW"
  related_node: households_heater_district_heating_mt_steam_hot_water
  position: 65
  slide_key: demand_households_heating_technologies
- key: households_heater_district_heating_ht_steam_hot_water_heat_output_capacity
  step_value: 0.1
  unit: "kW"
  related_node: households_heater_district_heating_ht_steam_hot_water
  position: 70
  slide_key: demand_households_heating_technologies
- key: households_heater_hybrid_heatpump_air_water_electricity_heat_output_capacity
  step_value: 0.1
  unit: "kW"
  related_node: households_space_heater_hybrid_heatpump_air_water_electricity
  position: 75
  slide_key: demand_households_heating_technologies
- key: households_heater_hybrid_hydrogen_heatpump_air_water_electricity_heat_output_capacity
  step_value: 0.1
  unit: "kW"
  related_node: households_space_heater_hybrid_hydrogen_heatpump_air_water_electricity
  position: 80
  slide_key: demand_households_heating_technologies   
- key: households_heater_hybrid_crude_oil_heatpump_air_water_electricity_heat_output_capacity
  step_value: 0.1
  unit: "kW"
  related_node: households_space_heater_hybrid_crude_oil_heatpump_air_water_electricity
  position: 85
  dependent_on: has_coal_oil_for_heating_built_environment
  slide_key: demand_households_heating_technologies     
- key: households_heater_coal_heat_output_capacity
  step_value: 0.1
  unit: "kW"
  related_node: households_space_heater_coal
  position: 5
  dependent_on: has_coal_oil_for_heating_built_environment
  slide_key: demand_households_heating_technologies
- key: households_heater_crude_oil_heat_output_capacity
  step_value: 0.1
  unit: "kW"
  related_node: households_space_heater_crude_oil
  position: 10
  dependent_on: has_coal_oil_for_heating_built_environment
  slide_key: demand_households_heating_technologies                 