---
- key: households_insulation_level_apartments_future
  step_value: 0.1
  draw_to_min: 0.0
  unit: "kWh/m2"
  interface_group: insulation_apartments
  position: 100
  slide_key: demand_households_insulation
- key: households_insulation_level_apartments_2005
  step_value: 0.1
  draw_to_min: 0.0
  unit: "kWh/m2"
  interface_group: insulation_apartments
  position: 200
  slide_key: demand_households_insulation
- key: households_insulation_level_apartments_1985_2004
  step_value: 0.1
  draw_to_min: 0.0
  unit: "kWh/m2"
  interface_group: insulation_apartments
  position: 300
  slide_key: demand_households_insulation
- key: households_insulation_level_apartments_1965_1984
  step_value: 0.1
  draw_to_min: 0.0
  unit: "kWh/m2"
  interface_group: insulation_apartments
  position: 400
  slide_key: demand_households_insulation
- key: households_insulation_level_apartments_1945_1964
  step_value: 0.1
  draw_to_min: 0.0
  unit: "kWh/m2"
  interface_group: insulation_apartments
  position: 500
  slide_key: demand_households_insulation
- key: households_insulation_level_apartments_1945
  step_value: 0.1
  draw_to_min: 0.0
  unit: "kWh/m2"
  interface_group: insulation_apartments
  position: 600
  slide_key: demand_households_insulation
- key: households_insulation_level_terraced_future
  step_value: 0.1
  draw_to_min: 0.0
  unit: "kWh/m2"
  interface_group: insulation_terraced
  position: 700
  slide_key: demand_households_insulation
- key: households_insulation_level_terraced_2005
  step_value: 0.1
  draw_to_min: 0.0
  unit: "kWh/m2"
  interface_group: insulation_terraced
  position: 800
  slide_key: demand_households_insulation
- key: households_insulation_level_terraced_1985_2004
  step_value: 0.1
  draw_to_min: 0.0
  unit: "kWh/m2"
  interface_group: insulation_terraced
  position: 900
  slide_key: demand_households_insulation
- key: households_insulation_level_terraced_1965_1984
  step_value: 0.1
  draw_to_min: 0.0
  unit: "kWh/m2"
  interface_group: insulation_terraced
  position: 1000
  slide_key: demand_households_insulation
- key: households_insulation_level_terraced_1945_1964
  step_value: 0.1
  draw_to_min: 0.0
  unit: "kWh/m2"
  interface_group: insulation_terraced
  position: 1100
  slide_key: demand_households_insulation
- key: households_insulation_level_terraced_1945
  step_value: 0.1
  draw_to_min: 0.0
  unit: "kWh/m2"
  interface_group: insulation_terraced
  position: 1200
  slide_key: demand_households_insulation
- key: households_insulation_level_semi_detached_future
  step_value: 0.1
  draw_to_min: 0.0
  unit: "kWh/m2"
  interface_group: insulation_semi_detached
  position: 1300
  slide_key: demand_households_insulation
- key: households_insulation_level_semi_detached_2005
  step_value: 0.1
  draw_to_min: 0.0
  unit: "kWh/m2"
  interface_group: insulation_semi_detached
  position: 1400
  slide_key: demand_households_insulation
- key: households_insulation_level_semi_detached_1985_2004
  step_value: 0.1
  draw_to_min: 0.0
  unit: "kWh/m2"
  interface_group: insulation_semi_detached
  position: 1500
  slide_key: demand_households_insulation
- key: households_insulation_level_semi_detached_1965_1984
  step_value: 0.1
  draw_to_min: 0.0
  unit: "kWh/m2"
  interface_group: insulation_semi_detached
  position: 1600
  slide_key: demand_households_insulation
- key: households_insulation_level_semi_detached_1945_1964
  step_value: 0.1
  draw_to_min: 0.0
  unit: "kWh/m2"
  interface_group: insulation_semi_detached
  position: 1700
  slide_key: demand_households_insulation
- key: households_insulation_level_semi_detached_1945
  step_value: 0.1
  draw_to_min: 0.0
  unit: "kWh/m2"
  interface_group: insulation_semi_detached
  position: 1800
  slide_key: demand_households_insulation
- key: households_insulation_level_detached_future
  step_value: 0.1
  draw_to_min: 0.0
  unit: "kWh/m2"
  interface_group: insulation_detached
  position: 1900
  slide_key: demand_households_insulation
- key: households_insulation_level_detached_2005
  step_value: 0.1
  draw_to_min: 0.0
  unit: "kWh/m2"
  interface_group: insulation_detached
  position: 2000
  slide_key: demand_households_insulation
- key: households_insulation_level_detached_1985_2004
  step_value: 0.1
  draw_to_min: 0.0
  unit: "kWh/m2"
  interface_group: insulation_detached
  position: 2100
  slide_key: demand_households_insulation
- key: households_insulation_level_detached_1965_1984
  step_value: 0.1
  draw_to_min: 0.0
  unit: "kWh/m2"
  interface_group: insulation_detached
  position: 2200
  slide_key: demand_households_insulation
- key: households_insulation_level_detached_1945_1964
  step_value: 0.1
  draw_to_min: 0.0
  unit: "kWh/m2"
  interface_group: insulation_detached
  position: 2300
  slide_key: demand_households_insulation
- key: households_insulation_level_detached_1945
  step_value: 0.1
  draw_to_min: 0.0
  unit: "kWh/m2"
  interface_group: insulation_detached
  position: 2400
  slide_key: demand_households_insulation
