---
- key: households_heater_combined_network_gas_share
  share_group: heating_households
  step_value: 0.1
  unit: "%"
  interface_group: space_and_water_heating_technologies
  related_node: households_space_heater_combined_network_gas
  position: 1
  slide_key: demand_households_heating
- key: households_heater_combined_hydrogen_share
  share_group: heating_households
  step_value: 0.1
  unit: "%"
  interface_group: space_and_water_heating_technologies
  related_node: households_space_heater_combined_hydrogen
  position: 2
  slide_key: demand_households_heating
- key: households_heater_district_heating_ht_steam_hot_water_share
  share_group: heating_households
  step_value: 0.1
  unit: "%"
  interface_group: space_and_water_heating_technologies
  position: 3
  slide_key: demand_households_heating
- key: households_heater_district_heating_mt_steam_hot_water_share
  share_group: heating_households
  step_value: 0.1
  unit: "%"
  interface_group: space_and_water_heating_technologies
  position: 4
  slide_key: demand_households_heating
- key: households_heater_district_heating_lt_steam_hot_water_share
  share_group: heating_households
  step_value: 0.1
  unit: "%"
  interface_group: space_and_water_heating_technologies
  position: 5
  slide_key: demand_households_heating
- key: households_heater_heatpump_air_water_electricity_share
  share_group: heating_households
  step_value: 0.1
  unit: "%"
  interface_group: space_and_water_heating_technologies
  related_node: households_space_heater_heatpump_air_water_electricity
  position: 6
  slide_key: demand_households_heating
- key: households_heater_heatpump_ground_water_electricity_share
  share_group: heating_households
  step_value: 0.1
  unit: "%"
  interface_group: space_and_water_heating_technologies
  related_node: households_space_heater_heatpump_ground_water_electricity
  position: 7
  slide_key: demand_households_heating
- key: households_heater_heatpump_surface_water_water_ts_electricity_share
  share_group: heating_households
  step_value: 0.1
  unit: "%"
  interface_group: space_and_water_heating_technologies
  related_node: households_space_heater_heatpump_surface_water_water_ts_electricity
  position: 8
  slide_key: demand_households_heating
- key: households_heater_hybrid_heatpump_air_water_electricity_share
  share_group: heating_households
  step_value: 0.1
  unit: "%"
  interface_group: space_and_water_heating_technologies
  related_node: households_space_heater_hybrid_heatpump_air_water_electricity
  position: 9
  slide_key: demand_households_heating
- key: households_heater_hybrid_hydrogen_heatpump_air_water_electricity_share
  share_group: heating_households
  step_value: 0.1
  unit: "%"
  interface_group: space_and_water_heating_technologies
  related_node: households_space_heater_hybrid_hydrogen_heatpump_air_water_electricity
  position: 10
  slide_key: demand_households_heating
- key: households_heater_heatpump_pvt_electricity_share
  share_group: heating_households
  step_value: 0.1
  unit: "%"
  interface_group: space_and_water_heating_technologies
  related_node: households_space_heater_heatpump_pvt_electricity
  position: 12
  slide_key: demand_households_heating
- key: households_heater_wood_pellets_share
  share_group: heating_households
  step_value: 0.1
  unit: "%"
  interface_group: space_and_water_heating_technologies
  related_node: households_space_heater_wood_pellets
  position: 13
  slide_key: demand_households_heating
- key: households_heater_electricity_share
  share_group: heating_households
  step_value: 0.1
  unit: "%"
  interface_group: space_and_water_heating_technologies
  related_node: households_space_heater_electricity
  position: 14
  slide_key: demand_households_heating
- key: households_heater_network_gas_share
  share_group: heating_households
  step_value: 0.1
  unit: "%"
  interface_group: space_and_water_heating_technologies
  related_node: households_space_heater_network_gas
  position: 15
  slide_key: demand_households_heating
- key: households_heater_crude_oil_share
  share_group: heating_households
  step_value: 0.1
  unit: "%"
  interface_group: space_and_water_heating_technologies
  related_node: households_space_heater_crude_oil
  position: 16
  dependent_on: has_coal_oil_for_heating_built_environment
  slide_key: demand_households_heating
- key: households_heater_coal_share
  share_group: heating_households
  step_value: 0.1
  unit: "%"
  interface_group: space_and_water_heating_technologies
  related_node: households_space_heater_coal
  position: 17
  dependent_on: has_coal_oil_for_heating_built_environment
  slide_key: demand_households_heating
- key: households_heater_hybrid_crude_oil_heatpump_air_water_electricity_share
  share_group: heating_households
  step_value: 0.1
  unit: "%"
  interface_group: space_and_water_heating_technologies
  related_node: households_space_heater_crude_oil_hydrogen_heatpump_air_water_electricity
  position: 18
  dependent_on: has_coal_oil_for_heating_built_environment
  slide_key: demand_households_heating  

- key: households_water_heater_solar_thermal_share
  step_value: 0.1
  unit: "%"
  interface_group: share_in_hot_water
  related_node: households_water_heater_solar_thermal
  position: 1
  slide_key: demand_households_heating
