---
- key: buildings_number_of_buildings_present
  step_value: 1.0
  unit: "#"
  position: 100
  slide_key: demand_buildings_demand_growth
- key: buildings_number_of_buildings_future
  step_value: 1.0
  unit: "#"
  position: 105
  slide_key: demand_buildings_demand_growth

- key: buildings_useful_demand_electricity
  step_value: 0.1
  unit: "%"
  position: 200
  slide_key: demand_buildings_demand_growth
- key: buildings_useful_demand_cooling
  step_value: 0.1
  unit: "%"
  position: 205
  slide_key: demand_buildings_demand_growth
