---
- key: households_number_of_inhabitants
  step_value: 0.1
  unit: mln
  position: 100
  slide_key: demand_households_population

- key: households_number_of_apartments_future
  step_value: 1.0
  unit: "#"
  interface_group: housing_stock_apartments
  position: 200
  slide_key: demand_households_population
- key: households_number_of_apartments_2005_present
  step_value: 1.0
  unit: "#"
  interface_group: housing_stock_apartments
  position: 205
  slide_key: demand_households_population
- key: households_number_of_apartments_1985_2004
  step_value: 1.0
  unit: "#"
  interface_group: housing_stock_apartments
  position: 210
  slide_key: demand_households_population
- key: households_number_of_apartments_1965_1984
  step_value: 1.0
  unit: "#"
  interface_group: housing_stock_apartments
  position: 215
  slide_key: demand_households_population
- key: households_number_of_apartments_1945_1964
  step_value: 1.0
  unit: "#"
  interface_group: housing_stock_apartments
  position: 220
  slide_key: demand_households_population
- key: households_number_of_apartments_before_1945
  step_value: 1.0
  unit: "#"
  interface_group: housing_stock_apartments
  position: 225
  slide_key: demand_households_population

- key: households_number_of_detached_houses_future
  step_value: 1.0
  unit: "#"
  interface_group: housing_stock_detached_houses
  position: 300
  slide_key: demand_households_population
- key: households_number_of_detached_houses_2005_present
  step_value: 1.0
  unit: "#"
  interface_group: housing_stock_detached_houses
  position: 305
  slide_key: demand_households_population
- key: households_number_of_detached_houses_1985_2004
  step_value: 1.0
  unit: "#"
  interface_group: housing_stock_detached_houses
  position: 310
  slide_key: demand_households_population
- key: households_number_of_detached_houses_1965_1984
  step_value: 1.0
  unit: "#"
  interface_group: housing_stock_detached_houses
  position: 315
  slide_key: demand_households_population
- key: households_number_of_detached_houses_1945_1964
  step_value: 1.0
  unit: "#"
  interface_group: housing_stock_detached_houses
  position: 320
  slide_key: demand_households_population
- key: households_number_of_detached_houses_before_1945
  step_value: 1.0
  unit: "#"
  interface_group: housing_stock_detached_houses
  position: 325
  slide_key: demand_households_population

- key: households_number_of_semi_detached_houses_future
  step_value: 1.0
  unit: "#"
  interface_group: housing_stock_semi_detached_houses
  position: 400
  slide_key: demand_households_population
- key: households_number_of_semi_detached_houses_2005_present
  step_value: 1.0
  unit: "#"
  interface_group: housing_stock_semi_detached_houses
  position: 405
  slide_key: demand_households_population
- key: households_number_of_semi_detached_houses_1985_2004
  step_value: 1.0
  unit: "#"
  interface_group: housing_stock_semi_detached_houses
  position: 410
  slide_key: demand_households_population
- key: households_number_of_semi_detached_houses_1965_1984
  step_value: 1.0
  unit: "#"
  interface_group: housing_stock_semi_detached_houses
  position: 415
  slide_key: demand_households_population
- key: households_number_of_semi_detached_houses_1945_1964
  step_value: 1.0
  unit: "#"
  interface_group: housing_stock_semi_detached_houses
  position: 420
  slide_key: demand_households_population
- key: households_number_of_semi_detached_houses_before_1945
  step_value: 1.0
  unit: "#"
  interface_group: housing_stock_semi_detached_houses
  position: 425
  slide_key: demand_households_population

- key: households_number_of_terraced_houses_future
  step_value: 1.0
  unit: "#"
  interface_group: housing_stock_terraced_houses
  position: 500
  slide_key: demand_households_population
- key: households_number_of_terraced_houses_2005_present
  step_value: 1.0
  unit: "#"
  interface_group: housing_stock_terraced_houses
  position: 505
  slide_key: demand_households_population
- key: households_number_of_terraced_houses_1985_2004
  step_value: 1.0
  unit: "#"
  interface_group: housing_stock_terraced_houses
  position: 510
  slide_key: demand_households_population
- key: households_number_of_terraced_houses_1965_1984
  step_value: 1.0
  unit: "#"
  interface_group: housing_stock_terraced_houses
  position: 515
  slide_key: demand_households_population
- key: households_number_of_terraced_houses_1945_1964
  step_value: 1.0
  unit: "#"
  interface_group: housing_stock_terraced_houses
  position: 520
  slide_key: demand_households_population
- key: households_number_of_terraced_houses_before_1945
  step_value: 1.0
  unit: "#"
  interface_group: housing_stock_terraced_houses
  position: 525
  slide_key: demand_households_population
