---
- key: volume_of_baseload_export_coal
  step_value: 1.0
  unit: "PJ"
  interface_group: coal_products
  position: 15
  slide_key: demand_export_energy
- key: volume_of_baseload_export_lignite
  step_value: 1.0
  unit: "PJ"
  interface_group: coal_products
  position: 20
  slide_key: demand_export_energy
- key: volume_of_baseload_export_cokes
  step_value: 1.0
  unit: "PJ"
  interface_group: coal_products
  position: 25
  slide_key: demand_export_energy
- key: volume_of_baseload_export_lng
  step_value: 1.0
  unit: "PJ"
  interface_group: gas_products
  position: 30
  slide_key: demand_export_energy
- key: volume_of_baseload_export_crude_oil
  step_value: 1.0
  unit: "PJ"
  interface_group: oil_products
  position: 35
  slide_key: demand_export_energy
- key: volume_of_baseload_export_kerosene
  step_value: 1.0
  unit: "PJ"
  interface_group: oil_products
  position: 40
  slide_key: demand_export_energy
- key: volume_of_baseload_export_gasoline
  step_value: 1.0
  unit: "PJ"
  interface_group: oil_products
  position: 45
  slide_key: demand_export_energy
- key: volume_of_baseload_export_diesel
  step_value: 1.0
  unit: "PJ"
  interface_group: oil_products
  position: 47
  slide_key: demand_export_energy
- key: volume_of_baseload_export_lpg
  step_value: 1.0
  unit: "PJ"
  interface_group: oil_products
  position: 50
  slide_key: demand_export_energy
- key: volume_of_baseload_export_heavy_fuel_oil
  step_value: 1.0
  unit: "PJ"
  interface_group: oil_products
  position: 52
  slide_key: demand_export_energy
- key: volume_of_baseload_export_ammonia
  step_value: 1.0
  unit: "PJ"
  interface_group: gas_products
  position: 55
  slide_key: demand_export_energy
- key: volume_of_baseload_export_network_gas
  step_value: 1.0
  unit: "PJ"
  interface_group: gas_products
  position: 60
  slide_key: demand_export_energy
- key: volume_of_baseload_export_hydrogen
  step_value: 1.0
  unit: "PJ"
  interface_group: gas_products
  position: 65
  slide_key: demand_export_energy