---

- key: households_heater_combined_network_gas_share
  share_group: heating_households
  step_value: 0.1
  unit: "%"
  related_node: households_space_heater_combined_network_gas
  position: 1
  slide_key: demand_households_heating
- key: households_heater_combined_hydrogen_share
  share_group: heating_households
  step_value: 0.1
  unit: "%"
  related_node: households_space_heater_combined_hydrogen
  position: 2
  slide_key: demand_households_heating
- key: households_heater_district_heating_ht_steam_hot_water_share
  share_group: heating_households
  step_value: 0.1
  unit: "%"
  position: 3
  slide_key: demand_households_heating
- key: households_heater_district_heating_mt_steam_hot_water_share
  share_group: heating_households
  step_value: 0.1
  unit: "%"
  position: 4
  slide_key: demand_households_heating
- key: households_heater_district_heating_lt_steam_hot_water_share
  share_group: heating_households
  step_value: 0.1
  unit: "%"
  position: 5
  slide_key: demand_households_heating
- key: households_heater_heatpump_air_water_electricity_share
  share_group: heating_households
  step_value: 0.1
  unit: "%"
  related_node: households_space_heater_heatpump_air_water_electricity
  position: 6
  slide_key: demand_households_heating
- key: households_heater_heatpump_ground_water_electricity_share
  share_group: heating_households
  step_value: 0.1
  unit: "%"
  related_node: households_space_heater_heatpump_ground_water_electricity
  position: 7
  slide_key: demand_households_heating
- key: households_heater_heatpump_surface_water_water_ts_electricity_share
  share_group: heating_households
  step_value: 0.1
  unit: "%"
  related_node: households_space_heater_heatpump_surface_water_water_ts_electricity
  position: 8
  slide_key: demand_households_heating
- key: households_heater_hybrid_heatpump_air_water_electricity_share
  share_group: heating_households
  step_value: 0.1
  unit: "%"
  related_node: households_space_heater_hybrid_heatpump_air_water_electricity
  position: 9
  slide_key: demand_households_heating
- key: households_heater_hybrid_hydrogen_heatpump_air_water_electricity_share
  share_group: heating_households
  step_value: 0.1
  unit: "%"
  related_node: households_space_heater_hybrid_hydrogen_heatpump_air_water_electricity
  position: 10
  slide_key: demand_households_heating
- key: households_heater_heatpump_pvt_electricity_share
  share_group: heating_households
  step_value: 0.1
  unit: "%"
  related_node: households_space_heater_heatpump_pvt_electricity
  position: 11
  slide_key: demand_households_heating
- key: households_heater_wood_pellets_share
  share_group: heating_households
  step_value: 0.1
  unit: "%"
  related_node: households_space_heater_wood_pellets
  position: 12
  slide_key: demand_households_heating
- key: households_heater_electricity_share
  share_group: heating_households
  step_value: 0.1
  unit: "%"
  related_node: households_space_heater_electricity
  position: 13
  slide_key: demand_households_heating
- key: households_heater_network_gas_share
  share_group: heating_households
  step_value: 0.1
  unit: "%"
  related_node: households_space_heater_network_gas
  position: 14
  slide_key: demand_households_heating
- key: households_heater_crude_oil_share
  share_group: heating_households
  step_value: 0.1
  unit: "%"
  related_node: households_space_heater_crude_oil
  position: 15
  dependent_on: has_coal_oil_for_heating_built_environment
  slide_key: demand_households_heating
- key: households_heater_coal_share
  share_group: heating_households
  step_value: 0.1
  unit: "%"
  related_node: households_space_heater_coal
  position: 16
  dependent_on: has_coal_oil_for_heating_built_environment
  slide_key: demand_households_heating
