---
- key: co2_emissions_of_imported_ammonia_present
  step_value: 1.0
  unit: kg/MWh
  position: 1
  slide_key: emissions_emission_factors_ammonia_co2_import
- key: co2_emissions_of_imported_ammonia_future
  step_value: 1.0
  unit: kg/MWh
  position: 2
  slide_key: emissions_emission_factors_ammonia_co2_import
