---
- key: co2_emissions_of_imported_hydrogen_present
  step_value: 1.0
  unit: kg/MWh
  position: 1
  slide_key: emissions_emission_factors_hydrogen_co2_import
- key: co2_emissions_of_imported_hydrogen_future
  step_value: 1.0
  unit: kg/MWh
  position: 2
  slide_key: emissions_emission_factors_hydrogen_co2_import
