---
- key: external_coupling_efficiency_industry_chp_ultra_supercritical_coal_electricity
  step_value: 1.0
  unit: '%'
  position: 100
  slide_key: specs_electricity_coal_plants
  share_group: ''
  interface_group: efficiency
  coupling_icon: true
- key: external_coupling_efficiency_industry_chp_ultra_supercritical_coal_heat
  step_value: 1.0
  unit: '%'
  position: 105
  slide_key: specs_electricity_coal_plants
  share_group: ''
  interface_group: efficiency
  coupling_icon: true
- key: external_coupling_efficiency_industry_chp_combined_cycle_gas_power_fuelmix_electricity
  step_value: 1.0
  unit: '%'
  position: 200
  slide_key: specs_electricity_gas_plants
  share_group: ''
  interface_group: efficiency_industry_plants
  coupling_icon: true
- key: external_coupling_efficiency_industry_chp_engine_gas_power_fuelmix_electricity
  step_value: 1.0
  unit: '%'
  position: 205
  slide_key: specs_electricity_gas_plants
  share_group: ''
  interface_group: efficiency_industry_plants
  coupling_icon: true
- key: external_coupling_efficiency_industry_chp_turbine_gas_power_fuelmix_electricity
  step_value: 1.0
  unit: '%'
  position: 210
  slide_key: specs_electricity_gas_plants
  share_group: ''
  interface_group: efficiency_industry_plants
  coupling_icon: true
- key: external_coupling_efficiency_industry_chp_combined_cycle_gas_power_fuelmix_heat
  step_value: 1.0
  unit: '%'
  position: 215
  slide_key: specs_electricity_gas_plants
  share_group: ''
  interface_group: efficiency_industry_plants
  coupling_icon: true
- key: external_coupling_efficiency_industry_chp_engine_gas_power_fuelmix_heat
  step_value: 1.0
  unit: '%'
  position: 220
  slide_key: specs_electricity_gas_plants
  share_group: ''
  interface_group: efficiency_industry_plants
  coupling_icon: true
- key: external_coupling_efficiency_industry_chp_turbine_gas_power_fuelmix_heat
  step_value: 1.0
  unit: '%'
  position: 225
  slide_key: specs_electricity_gas_plants
  share_group: ''
  interface_group: efficiency_industry_plants
  coupling_icon: true
- key: external_coupling_efficiency_industry_chp_wood_pellets_electricity
  step_value: 1.0
  unit: '%'
  position: 300
  slide_key: specs_electricity_renewable_biomass_plants
  share_group: ''
  interface_group: efficiency_industry_plants
  coupling_icon: true
- key: external_coupling_efficiency_industry_chp_wood_pellets_heat
  step_value: 1.0
  unit: '%'
  position: 305
  slide_key: specs_electricity_renewable_biomass_plants
  share_group: ''
  interface_group: efficiency_industry_plants
  coupling_icon: true
- key: external_coupling_efficiency_industry_chp_turbine_hydrogen_electricity
  step_value: 1.0
  unit: '%'
  position: 400
  slide_key: specs_electricity_renewable_hydrogen_plants
  share_group: ''
  interface_group: efficiency
  coupling_icon: true
- key: external_coupling_efficiency_industry_chp_turbine_hydrogen_heat
  step_value: 1.0
  unit: '%'
  position: 405
  slide_key: specs_electricity_renewable_hydrogen_plants
  share_group: ''
  interface_group: efficiency
  coupling_icon: true
- key: external_coupling_capacity_of_industry_chp_combined_cycle_gas_power_fuelmix
  step_value: 1.0
  unit: MW
  position: 500
  slide_key: supply_heat_network_industry
  share_group: ''
  interface_group: industry_chps
  coupling_icon: true
- key: external_coupling_capacity_of_industry_chp_engine_gas_power_fuelmix
  step_value: 1.0
  unit: MW
  position: 505
  slide_key: supply_heat_network_industry
  share_group: ''
  interface_group: industry_chps
  coupling_icon: true
- key: external_coupling_capacity_of_industry_chp_turbine_gas_power_fuelmix
  step_value: 1.0
  unit: MW
  position: 510
  slide_key: supply_heat_network_industry
  share_group: ''
  interface_group: industry_chps
  coupling_icon: true
- key: external_coupling_capacity_of_industry_chp_turbine_hydrogen
  step_value: 1.0
  unit: MW
  position: 515
  slide_key: supply_heat_network_industry
  share_group: ''
  interface_group: industry_chps
  coupling_icon: true
- key: external_coupling_capacity_of_industry_chp_ultra_supercritical_coal
  step_value: 1.0
  unit: MW
  position: 520
  slide_key: supply_heat_network_industry
  share_group: ''
  interface_group: industry_chps
  coupling_icon: true
- key: external_coupling_capacity_of_industry_chp_wood_pellets
  step_value: 1.0
  unit: MW
  position: 525
  slide_key: supply_heat_network_industry
  share_group: ''
  interface_group: industry_chps
  coupling_icon: true
