---
- key: external_coupling_molecules_other_utilisation_demand
  step_value: 0.1
  unit: Mton
  position: 100
  slide_key: supply_ccus_utilisation_storage
  share_group: ''
  interface_group: external_coupling_ccus_utilisation
- key: external_coupling_energy_production_synthetic_kerosene_demand
  step_value: 0.1
  unit: PJ
  position: 102
  slide_key: supply_ccus_utilisation_storage
  share_group: ''
  interface_group: external_coupling_ccus_utilisation
- key: external_coupling_energy_production_synthetic_methanol_demand
  step_value: 0.1
  unit: PJ
  position: 104
  slide_key: supply_ccus_utilisation_storage
  share_group: ''
  interface_group: external_coupling_ccus_utilisation
