---
- key: external_coupling_energy_chp_supercritical_ccs_waste_mix_electrical_efficiency
  step_value: 1.0
  unit: '%'
  position: 100
  slide_key: specs_electricity_renewable_waste_power
  share_group: ''
  interface_group: efficiency
  coupling_icon: true
- key: external_coupling_energy_chp_supercritical_waste_mix_electrical_efficiency
  step_value: 1.0
  unit: '%'
  position: 105
  slide_key: specs_electricity_renewable_waste_power
  share_group: ''
  interface_group: efficiency
  coupling_icon: true
- key: external_coupling_energy_chp_supercritical_ccs_waste_mix_heat_efficiency
  step_value: 1.0
  unit: '%'
  position: 110
  slide_key: specs_electricity_renewable_waste_power
  share_group: ''
  interface_group: efficiency
  coupling_icon: true
- key: external_coupling_energy_chp_supercritical_waste_mix_heat_efficiency
  step_value: 1.0
  unit: '%'
  position: 115
  slide_key: specs_electricity_renewable_waste_power
  share_group: ''
  interface_group: efficiency
  coupling_icon: true
- key: external_coupling_biogenic_waste_max_demand
  step_value: 0.1
  unit: PJ
  position: 200
  slide_key: supply_biomass_potential
  share_group: ''
  interface_group: ''
  coupling_icon: true
- key: external_coupling_non_biogenic_waste_max_demand
  step_value: 0.1
  unit: PJ
  position: 205
  slide_key: supply_biomass_potential
  share_group: ''
  interface_group: ''
  coupling_icon: true
- key: external_coupling_waste_mix_biogenic_waste_share
  step_value: 0.1
  unit: '%'
  position: 300
  slide_key: supply_biomass_potential
  share_group: waste_mix
  interface_group: external_coupling_biomass_waste_mix
  coupling_icon: true
- key: external_coupling_waste_mix_non_biogenic_waste_share
  step_value: 0.1
  unit: '%'
  position: 305
  slide_key: supply_biomass_potential
  share_group: waste_mix
  interface_group: external_coupling_biomass_waste_mix
  coupling_icon: true
- key: external_coupling_energy_chp_supercritical_ccs_waste_mix_captured_co2
  step_value: 1.0
  unit: '%'
  position: 400
  slide_key: supply_ccus_capture_energy
  share_group: ''
  interface_group: power_plants
  coupling_icon: true
- key: external_coupling_energy_chp_supercritical_waste_mix_capacity
  step_value: 1.0
  unit: MW
  position: 500
  slide_key: supply_electricity_renewable_waste_power
  share_group: ''
  interface_group: ''
  coupling_icon: true
