---
- key: external_coupling_industry_external_coupling_node_captured_co2_supply
  step_value: 0.1
  unit: Mton
  position: 100
  slide_key: supply_ccus_capture_industry
  share_group:
  interface_group:
  coupling_icon: true

- key: external_coupling_molecules_other_utilisation_demand
  step_value: 0.1
  unit: Mton
  position: 200
  slide_key: supply_ccus_utilisation_storage
  share_group:
  interface_group: external_coupling_ccus_utilisation
  coupling_icon: true
