---
- key: external_coupling_energy_heat_production_ht_residual_heat_investment_costs
  step_value: 1.0
  unit: "€/unit"
  position: 100
  slide_key: costs_heat_sources_other
  share_group: ''
  interface_group: residual_heat
  coupling_icon: true
- key: external_coupling_energy_heat_production_ht_residual_heat_wacc
  step_value: 1.0
  unit: '%'
  position: 105
  slide_key: costs_heat_sources_other
  share_group: ''
  interface_group: residual_heat
  coupling_icon: true
- key: external_coupling_energy_heat_production_ht_residual_heat_technical_lifetime
  step_value: 1.0
  unit: year
  position: 110
  slide_key: costs_heat_sources_other
  share_group: ''
  interface_group: residual_heat
  coupling_icon: true
- key: external_coupling_energy_heat_production_ht_residual_heat_fixed_om_costs
  step_value: 1.0
  unit: "€/year/unit"
  position: 115
  slide_key: costs_heat_sources_other
  share_group: ''
  interface_group: residual_heat
  coupling_icon: true
