---
- key: external_coupling_industry_metal_other_metals_investment_costs
  step_value: 1.0
  unit: "€/unit"
  position: 100
  slide_key: demand_industry_other_metals
  share_group: ''
  interface_group: external_coupling_industry_metal_other_costs
  coupling_icon: true
- key: external_coupling_industry_metal_other_metals_technical_lifetime
  step_value: 1.0
  unit: year
  position: 105
  slide_key: demand_industry_other_metals
  share_group: ''
  interface_group: external_coupling_industry_metal_other_costs
  coupling_icon: true
- key: external_coupling_industry_metal_other_metals_fixed_om_costs
  step_value: 1.0
  unit: "€/year/unit"
  position: 110
  slide_key: demand_industry_other_metals
  share_group: ''
  interface_group: external_coupling_industry_metal_other_costs
  coupling_icon: true
- key: external_coupling_industry_other_metals_crude_oil_share
  step_value: 0.1
  unit: '%'
  position: 200
  slide_key: demand_industry_other_metals
  share_group: external_coupling_industry_other_metal_energetic_input
  interface_group: external_coupling_industry_metal_other_energetic
  coupling_icon: true
- key: external_coupling_industry_other_metals_heat_useable_heat_share
  step_value: 0.1
  unit: '%'
  position: 205
  slide_key: demand_industry_other_metals
  share_group: external_coupling_industry_other_metal_energetic_input
  interface_group: external_coupling_industry_metal_other_energetic
  coupling_icon: true
- key: external_coupling_industry_other_metals_electricity_share
  step_value: 0.1
  unit: '%'
  position: 210
  slide_key: demand_industry_other_metals
  share_group: external_coupling_industry_other_metal_energetic_input
  interface_group: external_coupling_industry_metal_other_energetic
  coupling_icon: true
- key: external_coupling_industry_other_metals_coal_share
  step_value: 0.1
  unit: '%'
  position: 215
  slide_key: demand_industry_other_metals
  share_group: external_coupling_industry_other_metal_energetic_input
  interface_group: external_coupling_industry_metal_other_energetic
  coupling_icon: true
- key: external_coupling_industry_other_metals_network_gas_share
  step_value: 0.1
  unit: '%'
  position: 220
  slide_key: demand_industry_other_metals
  share_group: external_coupling_industry_other_metal_energetic_input
  interface_group: external_coupling_industry_metal_other_energetic
  coupling_icon: true
- key: external_coupling_industry_other_metals_hydrogen_share
  step_value: 0.1
  unit: '%'
  position: 225
  slide_key: demand_industry_other_metals
  share_group: external_coupling_industry_other_metal_energetic_input
  interface_group: external_coupling_industry_metal_other_energetic
  coupling_icon: true
- key: external_coupling_industry_metal_other_metals_hydrogen_efficiency
  step_value: 1.0
  unit: '%'
  position: 300
  slide_key: demand_industry_other_metals
  share_group: ''
  interface_group: external_coupling_industry_metal_other_general
  coupling_icon: true
- key: external_coupling_industry_metal_other_metals_total_demand
  step_value: 0.1
  unit: '%'
  position: 305
  slide_key: demand_industry_other_metals
  share_group: ''
  interface_group: external_coupling_industry_metal_other_general
  coupling_icon: true
- key: external_coupling_industry_other_metals_external_coupling_share
  step_value: 0.1
  unit: '%'
  position: 400
  slide_key: demand_industry_other_metals
  share_group: external_coupling_industry_other_metal_production_route
  interface_group: external_coupling_industry_metal_other_production_route
  coupling_icon: true
- key: external_coupling_industry_other_metals_process_electricity_share
  step_value: 0.1
  unit: '%'
  position: 405
  slide_key: demand_industry_other_metals
  share_group: external_coupling_industry_other_metal_production_route
  interface_group: external_coupling_industry_metal_other_production_route
  coupling_icon: true
- key: external_coupling_industry_other_metals_process_heat_useable_heat_share
  step_value: 0.1
  unit: '%'
  position: 410
  slide_key: demand_industry_other_metals
  share_group: external_coupling_industry_other_metal_production_route
  interface_group: external_coupling_industry_metal_other_production_route
  coupling_icon: true
