---
- key: external_coupling_industry_metal_steel_investment_costs
  step_value: 1.0
  unit: "€/Mton"
  position: 100
  slide_key: demand_industry_steel
  share_group: ''
  interface_group: external_coupling_industry_metal_steel_costs
  coupling_icon: true
- key: external_coupling_industry_metal_steel_wacc
  step_value: 1.0
  unit: '%'
  position: 105
  slide_key: demand_industry_steel
  share_group: ''
  interface_group: external_coupling_industry_metal_steel_costs
  coupling_icon: true
- key: external_coupling_industry_metal_steel_technical_lifetime
  step_value: 1.0
  unit: year
  position: 110
  slide_key: demand_industry_steel
  share_group: ''
  interface_group: external_coupling_industry_metal_steel_costs
  coupling_icon: true
- key: external_coupling_industry_metal_steel_fixed_om_costs
  step_value: 1.0
  unit: "€/year/Mton"
  position: 115
  slide_key: demand_industry_steel
  share_group: ''
  interface_group: external_coupling_industry_metal_steel_costs
  coupling_icon: true
- key: external_coupling_industry_metal_steel_energetic_wood_pellets_share
  step_value: 0.1
  unit: '%'
  position: 200
  slide_key: demand_industry_steel
  share_group: external_coupling_industry_steel_energetic_input
  interface_group: external_coupling_industry_metal_steel_energetic
  coupling_icon: true
- key: external_coupling_industry_metal_steel_energetic_coal_gas_share
  step_value: 0.1
  unit: '%'
  position: 205
  slide_key: demand_industry_steel
  share_group: external_coupling_industry_steel_energetic_input
  interface_group: external_coupling_industry_metal_steel_energetic
  coupling_icon: true
- key: external_coupling_industry_metal_steel_energetic_crude_oil_share
  step_value: 0.1
  unit: '%'
  position: 210
  slide_key: demand_industry_steel
  share_group: external_coupling_industry_steel_energetic_input
  interface_group: external_coupling_industry_metal_steel_energetic
  coupling_icon: true
- key: external_coupling_industry_metal_steel_energetic_steam_hot_water_share
  step_value: 0.1
  unit: '%'
  position: 215
  slide_key: demand_industry_steel
  share_group: external_coupling_industry_steel_energetic_input
  interface_group: external_coupling_industry_metal_steel_energetic
  coupling_icon: true
- key: external_coupling_industry_metal_steel_energetic_electricity_share
  step_value: 0.1
  unit: '%'
  position: 220
  slide_key: demand_industry_steel
  share_group: external_coupling_industry_steel_energetic_input
  interface_group: external_coupling_industry_metal_steel_energetic
  coupling_icon: true
- key: external_coupling_industry_metal_steel_energetic_coal_share
  step_value: 0.1
  unit: '%'
  position: 225
  slide_key: demand_industry_steel
  share_group: external_coupling_industry_steel_energetic_input
  interface_group: external_coupling_industry_metal_steel_energetic
  coupling_icon: true
- key: external_coupling_industry_metal_steel_energetic_cokes_share
  step_value: 0.1
  unit: '%'
  position: 230
  slide_key: demand_industry_steel
  share_group: external_coupling_industry_steel_energetic_input
  interface_group: external_coupling_industry_metal_steel_energetic
  coupling_icon: true
- key: external_coupling_industry_metal_steel_energetic_network_gas_share
  step_value: 0.1
  unit: '%'
  position: 235
  slide_key: demand_industry_steel
  share_group: external_coupling_industry_steel_energetic_input
  interface_group: external_coupling_industry_metal_steel_energetic
  coupling_icon: true
- key: external_coupling_industry_metal_steel_energetic_hydrogen_share
  step_value: 0.1
  unit: '%'
  position: 240
  slide_key: demand_industry_steel
  share_group: external_coupling_industry_steel_energetic_input
  interface_group: external_coupling_industry_metal_steel_energetic
  coupling_icon: true
- key: external_coupling_industry_metal_steel_efficiency
  step_value: 1.0
  unit: '%'
  position: 300
  slide_key: demand_industry_steel
  share_group: ''
  interface_group: external_coupling_industry_metal_steel_general
  coupling_icon: true
- key: external_coupling_industry_metal_steel_total_demand
  step_value: 0.1
  unit: '%'
  position: 305
  slide_key: demand_industry_steel
  share_group: ''
  interface_group: external_coupling_industry_metal_steel_general
  coupling_icon: true
- key: external_coupling_industry_metal_steel_cyclonefurnace_bof_share
  step_value: 0.1
  unit: '%'
  position: 400
  slide_key: demand_industry_steel
  share_group: external_coupling_industry_steel_production_route
  interface_group: external_coupling_industry_metal_steel_production_route
  coupling_icon: true
- key: external_coupling_industry_metal_steel_external_coupling_share
  step_value: 0.1
  unit: '%'
  position: 405
  slide_key: demand_industry_steel
  share_group: external_coupling_industry_steel_production_route
  interface_group: external_coupling_industry_metal_steel_production_route
  coupling_icon: true
- key: external_coupling_industry_metal_steel_blastfurnace_bof_share
  step_value: 0.1
  unit: '%'
  position: 410
  slide_key: demand_industry_steel
  share_group: external_coupling_industry_steel_production_route
  interface_group: external_coupling_industry_metal_steel_production_route
  coupling_icon: true
- key: external_coupling_industry_metal_steel_scrap_hbi_eaf_share
  step_value: 0.1
  unit: '%'
  position: 415
  slide_key: demand_industry_steel
  share_group: external_coupling_industry_steel_production_route
  interface_group: external_coupling_industry_metal_steel_production_route
  coupling_icon: true
- key: external_coupling_industry_metal_steel_dri_network_gas_share
  step_value: 0.1
  unit: '%'
  position: 420
  slide_key: demand_industry_steel
  share_group: external_coupling_industry_steel_production_route
  interface_group: external_coupling_industry_metal_steel_production_route
  coupling_icon: true
- key: external_coupling_industry_metal_steel_dri_hydrogen_share
  step_value: 0.1
  unit: '%'
  position: 425
  slide_key: demand_industry_steel
  share_group: external_coupling_industry_steel_production_route
  interface_group: external_coupling_industry_metal_steel_production_route
  coupling_icon: true
- key: external_coupling_industry_metal_steel_ccus_capture_potential
  step_value: 1.0
  unit: '%'
  position: 500
  slide_key: supply_ccus_capture_industry
  share_group: ''
  interface_group: external_coupling_industry_metal_steel_ccus
  coupling_icon: true
- key: external_coupling_industry_metal_steel_ccus_electricity_use
  step_value: 1.0
  unit: PJ/Mton
  position: 505
  slide_key: supply_ccus_capture_industry
  share_group: ''
  interface_group: external_coupling_industry_metal_steel_ccus
  coupling_icon: true
- key: external_coupling_industry_metal_steel_ccus_captured_co2
  step_value: 1.0
  unit: '%'
  position: 510
  slide_key: supply_ccus_capture_industry
  share_group: ''
  interface_group: external_coupling_industry_metal_steel_ccus
  coupling_icon: true
- key: external_coupling_energy_distribution_coal_gas_final_demand_share
  step_value: 0.01
  unit: '%'
  position: 600
  slide_key: supply_ccus_steel_coal_gas
  share_group: external_coupling_coal_gas_distribution
  interface_group: external_coupling_industry_metal_steel_coal_gas
  coupling_icon: true
- key: external_coupling_energy_distribution_coal_gas_energy_production_share
  step_value: 0.01
  unit: '%'
  position: 605
  slide_key: supply_ccus_steel_coal_gas
  share_group: external_coupling_coal_gas_distribution
  interface_group: external_coupling_industry_metal_steel_coal_gas
  coupling_icon: true
- key: external_coupling_energy_distribution_coal_gas_chemical_feedstock_share
  step_value: 0.01
  unit: '%'
  position: 610
  slide_key: supply_ccus_steel_coal_gas
  share_group: external_coupling_coal_gas_distribution
  interface_group: external_coupling_industry_metal_steel_coal_gas
  coupling_icon: true
