---
- key: connection_capacity_always_on_wind_turbine_inland
  step_value: 0.1
  unit: "%"
  interface_group: wind_turbine_inland
  position: 100
  slide_key: flexibility_power_storage_wind_turbine_inland
- key: battery_capacity_always_on_wind_turbine_inland
  step_value: 0.1
  unit: "%"
  interface_group: wind_turbine_inland
  related_node: energy_flexibility_wind_batteries_electricity
  position: 200
  slide_key: flexibility_power_storage_wind_turbine_inland
  additional_specs:
    other:
      timeframe: i_h_d
- key: volume_of_energy_flexibility_wind_batteries_electricity
  step_value: 0.1
  unit: "hours"
  interface_group: wind_turbine_inland
  related_node: energy_flexibility_wind_batteries_electricity
  position: 300
  slide_key: flexibility_power_storage_wind_turbine_inland
  additional_specs:
    other:
      timeframe: i_h_d
