---
- key: wtp_of_energy_production_synthetic_kerosene_dispatchable
  step_value: 0.1
  unit: "€/MWh"
  interface_group: willingness_to_pay
  related_node: energy_production_synthetic_kerosene_dispatchable
  position: 1
  slide_key: flexibility_flexibility_energy_production_synthetic_kerosene

  
