---
- key: energy_production_fischer_tropsch_synthetic_share
  share_group: fischer_tropsch
  interface_group: syngas_share
  step_value: 0.1
  unit: "%"
  position: 100
  slide_key: supply_fuel_production_fischer_tropsch
- key: energy_production_fischer_tropsch_non_biogenic_waste_ccs_share
  share_group: fischer_tropsch
  interface_group: syngas_share
  step_value: 0.1
  unit: "%"
  position: 100
  slide_key: supply_fuel_production_fischer_tropsch
- key: energy_production_fischer_tropsch_biogenic_waste_ccs_share
  share_group: fischer_tropsch
  interface_group: syngas_share
  step_value: 0.1
  unit: "%"
  position: 100
  slide_key: supply_fuel_production_fischer_tropsch
- key: energy_production_fischer_tropsch_dry_biomass_ccs_share
  share_group: fischer_tropsch
  interface_group: syngas_share
  step_value: 0.1
  unit: "%"
  position: 100
  slide_key: supply_fuel_production_fischer_tropsch
