---
- key: energy_production_methanol_synthesis_synthetic_share
  share_group: methanol_synthesis
  step_value: 0.1
  unit: "%"
  position: 100
  slide_key: supply_fuel_production_methanol_synthesis
- key: energy_production_methanol_synthesis_non_biogenic_waste_ccs_share
  share_group: methanol_synthesis
  step_value: 0.1
  unit: "%"
  position: 100
  slide_key: supply_fuel_production_methanol_synthesis
- key: energy_production_methanol_synthesis_biogenic_waste_ccs_share
  share_group: methanol_synthesis
  step_value: 0.1
  unit: "%"
  position: 100
  slide_key: supply_fuel_production_methanol_synthesis
- key: energy_production_methanol_synthesis_dry_biomass_ccs_share
  share_group: methanol_synthesis
  step_value: 0.1
  unit: "%"
  position: 100
  slide_key: supply_fuel_production_methanol_synthesis
