---
- key: share_of_industry_chemicals_other_reused_residual_lt_heat
  step_value: 0.1
  unit: %
  interface_group: residual_heat_chemical
  position: 1
  slide_key: residual_heat
- key: share_of_industry_chemicals_other_reused_residual_mt_heat
  step_value: 0.1
  unit: %
  interface_group: residual_heat_chemical
  position: 2
  slide_key: residual_heat
- key: share_of_industry_chemicals_other_reused_residual_ht_heat
  step_value: 0.1
  unit: %
  interface_group: residual_heat_chemical
  position: 3
  slide_key: residual_heat
- key: share_of_industry_chemicals_fertilizers_reused_residual_lt_heat
  step_value: 0.1
  unit: %
  interface_group: residual_heat_fertilizer
  position: 4
  slide_key: residual_heat
- key: share_of_industry_chemicals_fertilizers_reused_residual_mt_heat
  step_value: 0.1
  unit: %
  interface_group: residual_heat_fertilizer
  position: 5
  slide_key: residual_heat
- key: share_of_industry_chemicals_fertilizers_reused_residual_ht_heat
  step_value: 0.1
  unit: %
  interface_group: residual_heat_fertilizer
  position: 6
  slide_key: residual_heat
- key: share_of_industry_chemicals_refineries_reused_residual_lt_heat
  step_value: 0.1
  unit: %
  interface_group: residual_heat_refinery
  position: 7
  slide_key: residual_heat
- key: share_of_industry_chemicals_refineries_reused_residual_mt_heat
  step_value: 0.1
  unit: %
  interface_group: residual_heat_refinery
  position: 8
  slide_key: residual_heat
- key: share_of_industry_chemicals_refineries_reused_residual_ht_heat
  step_value: 0.1
  unit: %
  interface_group: residual_heat_refinery
  position: 9
  slide_key: residual_heat
- key: share_of_industry_other_ict_reused_residual_lt_heat
  step_value: 0.1
  unit: %
  interface_group: residual_heat_ict
  position: 10
  slide_key: residual_heat
- key: share_of_industry_other_ict_reused_residual_mt_heat
  step_value: 0.1
  unit: %
  interface_group: residual_heat_ict
  position: 11
  slide_key: residual_heat
- key: share_of_energy_hydrogen_flexibility_p2g_electricity_lt_heat
  step_value: 0.1
  unit: %
  interface_group: residual_heat_electrolysis
  position: 12
  slide_key: residual_heat
- key: share_of_energy_hydrogen_flexibility_p2g_electricity_mt_heat
  step_value: 0.1
  unit: %
  interface_group: residual_heat_electrolysis
  position: 13
  slide_key: residual_heat
