---
- key: capacity_of_energy_heat_lt_burner_wood_pellets  
  step_value: 0.1
  unit: MW
  position: 1
  slide_key: biomass_burner
- key: capacity_of_energy_heat_mt_burner_wood_pellets   
  step_value: 0.1
  unit: MW
  position: 1
  slide_key: biomass_burner
- key: capacity_of_energy_heat_ht_burner_wood_pellets
  step_value: 0.1
  unit: MW
  position: 1
  slide_key: biomass_burner
