---
- key: capacity_of_energy_heat_boiler_lt_electricity  
  step_value: 0.1
  unit: MW
  position: 4
  slide_key: supply_heat_sources_lt
- key: capacity_of_energy_heat_burner_lt_hydrogen  
  step_value: 0.1
  unit: MW
  position: 5
  slide_key: supply_heat_sources_lt
- key: capacity_of_energy_heat_heatpump_water_water_lt_electricity  
  step_value: 0.1
  unit: MW
  position: 3
  slide_key: supply_heat_sources_lt
- key: capacity_of_energy_heat_solar_lt_solar_thermal  
  step_value: 0.1
  unit: MW
  position: 1
  slide_key: supply_heat_sources_lt
- key: capacity_of_energy_heat_well_shallow_lt_geothermal  
  step_value: 0.1
  unit: MW
  position: 2
  slide_key: supply_heat_sources_lt
- key: volume_of_lt_imported_heat  
  step_value: 0.1
  unit: PJ
  position: 6
  slide_key: supply_heat_sources_lt
