---
- key: share_of_energy_chp_ultra_supercritical_coal_lt_heat
  step_value: 0.1
  unit: %
  interface_group: chp_coal_heat
  position: 1
  slide_key: chp_heat
- key: share_of_energy_chp_ultra_supercritical_coal_mt_heat
  step_value: 0.1
  unit: %
  interface_group: chp_coal_heat
  position: 2
  slide_key: chp_heat
- key: share_of_energy_chp_ultra_supercritical_coal_ht_heat
  step_value: 0.1
  unit: %
  interface_group: chp_coal_heat
  position: 3
  slide_key: chp_heat
- key: share_of_energy_chp_ultra_supercritical_cofiring_coal_lt_heat
  step_value: 0.1
  unit: %
  interface_group: chp_cofiring_coal_heat
  position: 4
  slide_key: 
- key: share_of_energy_chp_ultra_supercritical_cofiring_coal_mt_heat
  step_value: 0.1
  unit: %
  interface_group: chp_cofiring_coal_heat
  position: 5
  slide_key: 
- key: share_of_energy_chp_ultra_supercritical_cofiring_coal_ht_heat
  step_value: 0.1
  unit: %
  interface_group: chp_cofiring_coal_heat
  position: 6
  slide_key: 
- key: share_of_energy_chp_combined_cycle_network_gas_lt_heat
  step_value: 0.1
  unit: %
  interface_group: chp_network_gas_heat
  position: 7
  slide_key: 
- key: share_of_energy_chp_combined_cycle_network_gas_mt_heat
  step_value: 0.1
  unit: %
  interface_group: chp_network_gas_heat
  position: 8
  slide_key: 
- key: share_of_energy_chp_combined_cycle_network_gas_ht_heat
  step_value: 0.1
  unit: %
  interface_group: chp_network_gas_heat
  position: 9
  slide_key: 
- key: share_of_energy_chp_local_engine_network_gas_lt_heat
  step_value: 0.1
  unit: %
  interface_group: chp_local_network_gas_heat
  position: 10
  slide_key: 
- key: share_of_energy_chp_local_engine_network_gas_mt_heat
  step_value: 0.1
  unit: %
  interface_group: chp_local_network_gas_heat
  position: 11
  slide_key: 
- key: share_of_energy_chp_local_engine_network_gas_ht_heat
  step_value: 0.1
  unit: %
  interface_group: chp_local_network_gas_heat
  position: 12
  slide_key: 
- key: share_of_energy_chp_local_wood_pellets_lt_heat
  step_value: 0.1
  unit: %
  interface_group: chp_wood_pellet_heat
  position: 13
  slide_key: 
- key: share_of_energy_chp_local_wood_pellets_mt_heat
  step_value: 0.1
  unit: %
  interface_group: chp_wood_pellet_heat
  position: 14
  slide_key: 
- key: share_of_energy_chp_local_wood_pellets_ht_heat
  step_value: 0.1
  unit: %
  interface_group: chp_wood_pellet_heat
  position: 15
  slide_key: 
- key: share_of_energy_chp_local_engine_biogas_lt_heat
  step_value: 0.1
  unit: %
  interface_group: chp_local_biogas_heat
  position: 16
  slide_key: 
- key: share_of_energy_chp_local_engine_biogas_mt_heat
  step_value: 0.1
  unit: %
  interface_group: chp_local_biogas_heat
  position: 17
  slide_key: 
- key: share_of_energy_chp_local_engine_biogas_ht_heat
  step_value: 0.1
  unit: %
  interface_group: chp_local_biogas_heat
  position: 18
  slide_key: 
- key: share_of_energy_chp_supercritical_waste_mix_lt_heat
  step_value: 0.1
  unit: %
  interface_group: chp_waste_mix_heat
  position: 19
  slide_key: 
- key: share_of_energy_chp_supercritical_waste_mix_mt_heat
  step_value: 0.1
  unit: %
  interface_group: chp_waste_mix_heat
  position: 20
  slide_key: 
- key: share_of_energy_chp_supercritical_waste_mix_ht_heat
  step_value: 0.1
  unit: %
  interface_group: chp_waste_mix_heat
  position: 21
  slide_key: 