---
- key: capacity_of_energy_heat_well_lt_shallow_geothermal
  step_value: 0.1
  unit: MW
  interface_group: shallow_geothermal_heat
  position: 1
  slide_key: geothermal_heat
- key: capacity_of_energy_heat_well_mt_shallow_geothermal
  step_value: 0.1
  unit: MW
  interface_group: shallow_geothermal_heat
  position: 2
  slide_key: geothermal_heat
- key: capacity_of_energy_heat_well_lt_geothermal
  step_value: 0.1
  unit: MW
  interface_group: geothermal_heat
  position: 3
  slide_key: geothermal_heat
- key: capacity_of_energy_heat_well_mt_geothermal
  step_value: 0.1
  unit: MW
  interface_group: geothermal_heat
  position: 4
  slide_key: geothermal_heat
- key: capacity_of_energy_heat_well_ht_geothermal
  step_value: 0.1
  unit: MW
  interface_group: geothermal_heat
  position: 5
  slide_key: geothermal_heat
- key: capacity_of_energy_heat_well_ultra_deep_lt_geothermal
  step_value: 0.1
  unit: MW
  interface_group: ultra_deep_geothermal_heat
  position: 6
  slide_key: geothermal_heat
- key: capacity_of_energy_heat_well_ultra_deep_mt_geothermal
  step_value: 0.1
  unit: MW
  interface_group: ultra_deep_geothermal_heat
  position: 7
  slide_key: geothermal_heat
- key: capacity_of_energy_heat_well_ultra_deep_ht_geothermal
  step_value: 0.1
  unit: MW
  interface_group: ultra_deep_geothermal_heat
  position: 8
  slide_key: geothermal_heat
