---
- key: capacity_of_energy_hydrogen_wind_turbine_offshore
  step_value: 1.0
  unit: MW
  command_type: value
  related_node: energy_hydrogen_electrolysis_wind_electricity
  position: 10
  slide_key: supply_hydrogen_production
- key: capacity_of_energy_hydrogen_solar_pv_solar_radiation
  step_value: 1.0
  unit: MW
  command_type: value
  related_node: energy_hydrogen_electrolysis_solar_electricity
  position: 20
  slide_key: supply_hydrogen_production
- key: capacity_of_energy_hydrogen_steam_methane_reformer
  step_value: 1.0
  unit: MW
  command_type: value
  related_node: energy_hydrogen_steam_methane_reformer
  position: 30
  slide_key: supply_hydrogen_production
- key: capacity_of_energy_hydrogen_autothermal_reformer
  step_value: 1.0
  unit: MW
  command_type: value
  related_node: energy_hydrogen_autothermal_reformer
  position: 40
  slide_key: supply_hydrogen_production
- key: capacity_of_energy_hydrogen_ammonia_reformer
  step_value: 1.0
  unit: MW
  command_type: value
  related_node: energy_hydrogen_ammonia_reformer
  position: 50
  slide_key: supply_hydrogen_production
- key: capacity_of_energy_hydrogen_liquid_hydrogen_regasifier
  step_value: 1.0
  unit: MW
  command_type: value
  related_node: energy_hydrogen_liquid_hydrogen_regasifier
  position: 60
  slide_key: supply_hydrogen_production
- key: capacity_of_energy_hydrogen_lohc_reformer
  step_value: 1.0
  unit: MW
  command_type: value
  related_node: energy_hydrogen_lohc_reformer
  position: 70
  slide_key: supply_hydrogen_production
- key: capacity_of_energy_hydrogen_biomass_gasification
  step_value: 1.0
  unit: MW
  related_node: energy_hydrogen_biomass_gasification
  position: 20
  slide_key: supply_hydrogen_production
- key: capacity_of_energy_imported_hydrogen_baseload
  step_value: 1.0
  unit: MW
  command_type: value
  position: 80
  slide_key: supply_hydrogen_production
