---
- key: capacity_of_energy_heat_lt_surface_water
  step_value: 0.1
  unit: MW
  interface_group: energy_heat_surface_water
  position: 1
  slide_key: aquathermal
- key: capacity_of_energy_heat_mt_surface_water
  step_value: 0.1
  unit: MW
  interface_group: energy_heat_surface_water
  position: 2
  slide_key: aquathermal
- key: capacity_of_energy_heat_lt_waste_water
  step_value: 0.1
  unit: MW
  interface_group: energy_heat_waste_water
  position: 3
  slide_key: aquathermal
- key: capacity_of_energy_heat_mt_waste_water
  step_value: 0.1
  unit: MW
  interface_group: energy_heat_waste_water
  position: 4
  slide_key: aquathermal
- key: capacity_of_energy_heat_lt_potable_water
  step_value: 0.1
  unit: MW
  interface_group: energy_heat_potable_water
  position: 5
  slide_key: aquathermal
- key: capacity_of_energy_heat_mt_potable_water
  step_value: 0.1
  unit: MW
  interface_group: energy_heat_potable_water
  position: 6
  slide_key: aquathermal
