---
- key: capacity_of_energy_heat_burner_mt_coal
  step_value: 0.1
  unit: MW
  position: 1
  slide_key: coal_burner
- key: capacity_of_energy_heat_burner_ht_coal
  step_value: 0.1
  unit: MW
  position: 2
  slide_key: coal_burner
