---
- key: max_demand_of_wet_biomass
  step_value: 0.1
  unit: PJ
  position: 5
  slide_key: supply_biomass_potential
- key: max_demand_of_dry_biomass
  step_value: 0.1
  unit: PJ
  position: 10
  slide_key: supply_biomass_potential
- key: max_demand_of_oily_biomass
  step_value: 0.1
  unit: PJ
  position: 15
  slide_key: supply_biomass_potential
- key: max_demand_of_biogenic_waste
  step_value: 0.1
  unit: PJ
  position: 20
  slide_key: supply_biomass_potential
- key: max_demand_of_non_biogenic_waste
  step_value: 0.1
  unit: PJ
  position: 25
  slide_key: supply_biomass_potential