---
- key: capacity_of_energy_heat_well_deep_ht_geothermal  
  step_value: 0.1
  unit: MW
  interface_group: non_dispatchable_heat
  position: 100
  slide_key: supply_heat_sources_ht

- key: capacity_of_energy_heat_boiler_ht_electricity  
  step_value: 0.1
  unit: MW
  interface_group: dispatchable_heat
  position: 100
  slide_key: supply_heat_sources_ht
- key: capacity_of_energy_heat_heatpump_water_water_ht_electricity  
  step_value: 0.1
  unit: MW
  interface_group: dispatchable_heat
  position: 105
  slide_key: supply_heat_sources_ht
- key: capacity_of_energy_heat_burner_ht_hydrogen  
  step_value: 0.1
  unit: MW
  interface_group: dispatchable_heat
  position: 110
  slide_key: supply_heat_sources_ht
- key: capacity_of_energy_heat_burner_ht_wood_pellets  
  step_value: 0.1
  unit: MW
  interface_group: dispatchable_heat
  position: 115
  slide_key: supply_heat_sources_ht
- key: capacity_of_energy_heat_burner_ht_waste_mix  
  step_value: 0.1
  unit: MW
  interface_group: dispatchable_heat
  position: 120
  slide_key: supply_heat_sources_ht
- key: capacity_of_energy_heat_burner_ht_crude_oil  
  step_value: 0.1
  unit: MW
  interface_group: dispatchable_heat
  position: 125
  slide_key: supply_heat_sources_ht
- key: capacity_of_energy_heat_burner_ht_network_gas  
  step_value: 0.1
  unit: MW
  interface_group: dispatchable_heat
  position: 130
  slide_key: supply_heat_sources_ht
- key: capacity_of_energy_heat_burner_ht_coal  
  step_value: 0.1
  unit: MW
  interface_group: dispatchable_heat
  position: 135
  slide_key: supply_heat_sources_ht

- key: volume_of_ht_imported_heat  
  step_value: 0.1
  unit: PJ
  interface_group: imported_heat
  position: 200
  slide_key: supply_heat_sources_ht
