---
- key: capacity_of_energy_heat_boiler_ht_electricity  
  step_value: 0.1
  unit: MW
  position: 4
  slide_key: supply_heat_sources_ht
- key: capacity_of_energy_heat_burner_ht_hydrogen  
  step_value: 0.1
  unit: MW
  position: 5
  slide_key: supply_heat_sources_ht
- key: capacity_of_energy_heat_heatpump_water_water_ht_electricity  
  step_value: 0.1
  unit: MW
  position: 3
  slide_key: supply_heat_sources_ht
- key: volume_of_ht_imported_heat  
  step_value: 0.1
  unit: PJ
  position: 11
  slide_key: supply_heat_sources_ht
- key: capacity_of_energy_heat_burner_ht_coal  
  step_value: 0.1
  unit: MW
  position: 10
  slide_key: supply_heat_sources_ht
- key: capacity_of_energy_heat_burner_ht_crude_oil  
  step_value: 0.1
  unit: MW
  position: 8
  slide_key: supply_heat_sources_ht
- key: capacity_of_energy_heat_burner_ht_network_gas  
  step_value: 0.1
  unit: MW
  position: 9
  slide_key: supply_heat_sources_ht
- key: capacity_of_energy_heat_burner_ht_waste_mix  
  step_value: 0.1
  unit: MW
  position: 7
  slide_key: supply_heat_sources_ht
- key: capacity_of_energy_heat_burner_ht_wood_pellets  
  step_value: 0.1
  unit: MW
  position: 6
  slide_key: supply_heat_sources_ht







