---
- key: industry_useful_demand_for_chemical_refineries
  interface_group: fuel_production 
  step_value: 0.1
  unit: "PJ"
  position: 100
  slide_key: supply_fuel_production_overview
- key: output_of_energy_production_fischer_tropsch
  interface_group: fuel_production 
  step_value: 0.1
  unit: PJ
  position: 110
  slide_key: supply_fuel_production_overview
- key: output_of_energy_production_methanol_synthesis
  interface_group: fuel_production
  step_value: 0.1
  unit: PJ
  position: 120
  slide_key: supply_fuel_production_overview
- key: output_of_energy_production_pyrolysis_oil_fractionation_pyrolysis_oil
  interface_group: fuel_production
  step_value: 0.1
  unit: PJ
  position: 130
  slide_key: supply_fuel_production_overview
- key: output_of_energy_production_pyrolysis_oil_fractionation_bio_pyrolysis_oil
  interface_group: fuel_production
  step_value: 0.1
  unit: PJ
  position: 140
  slide_key: supply_fuel_production_overview
- key: output_of_energy_production_hvo_bio_kerosene
  interface_group: fuel_production
  step_value: 0.1
  unit: PJ
  position: 150
  slide_key: supply_fuel_production_overview
- key: output_of_energy_production_hvo_biodiesel
  interface_group: fuel_production
  step_value: 0.1
  unit: PJ
  position: 160
  slide_key: supply_fuel_production_overview
- key: output_of_energy_production_bio_ethanol
  interface_group: fuel_production
  step_value: 0.1
  unit: PJ
  position: 170
  slide_key: supply_fuel_production_overview
