---
- key: capacity_of_energy_chp_local_engine_biogas
  step_value: 0.1
  unit: MW
  interface_group: must_run_chps
  related_node: energy_chp_local_engine_ht_biogas
  position: 100
  slide_key: supply_electricity_renewable_biomass_plants
- key: capacity_of_energy_chp_local_wood_pellets_must_run
  step_value: 0.1
  unit: MW
  interface_group: must_run_chps
  related_node: energy_chp_local_ht_wood_pellets_must_run
  position: 110
  slide_key: supply_electricity_renewable_biomass_plants
- key: capacity_of_energy_power_wood_pellets_must_run
  step_value: 0.1
  unit: MW
  interface_group: must_run_chps
  related_node: energy_power_wood_pellets_must_run
  position: 120
  slide_key: supply_electricity_renewable_biomass_plants

- key: capacity_of_energy_chp_local_wood_pellets_dispatchable
  step_value: 0.1
  unit: MW
  interface_group: flexible_chps
  related_node: energy_chp_local_ht_wood_pellets_dispatchable
  position: 200
  slide_key: supply_electricity_renewable_biomass_plants
- key: capacity_of_energy_power_wood_pellets_dispatchable
  step_value: 0.1
  unit: MW
  interface_group: flexible_chps
  related_node: energy_power_wood_pellets_dispatchable
  position: 210
  slide_key: supply_electricity_renewable_biomass_plants
