---
- key: industry_useful_demand_for_chemical_refineries_electricity_efficiency
  step_value: 1
  unit: "%"
  interface_group: efficiency_industry_total
  position: 10
  slide_key: supply_fuel_fossil_refinery
- key: industry_useful_demand_for_chemical_refineries_useable_heat_efficiency
  step_value: 1
  unit: "%"
  interface_group: efficiency_industry_total
  position: 15
  slide_key: supply_fuel_fossil_refinery
- key: industry_chemicals_refineries_burner_network_gas_share
  share_group: chemical_refineries_heat
  step_value: 0.1
  unit: "%"
  interface_group: heat_production
  related_node: industry_chemicals_refineries_burner_network_gas
  position: 20
  slide_key: supply_fuel_fossil_refinery
- key: industry_chemicals_refineries_burner_crude_oil_share
  share_group: chemical_refineries_heat
  step_value: 0.1
  unit: "%"
  interface_group: heat_production
  related_node: industry_chemicals_refineries_burner_crude_oil
  position: 25
  slide_key: supply_fuel_fossil_refinery
- key: industry_chemicals_refineries_burner_wood_pellets_share
  share_group: chemical_refineries_heat
  step_value: 0.1
  unit: "%"
  interface_group: heat_production
  related_node: industry_chemicals_refineries_burner_wood_pellets
  position: 30
  slide_key: supply_fuel_fossil_refinery
- key: industry_chemicals_refineries_burner_coal_share
  share_group: chemical_refineries_heat
  step_value: 0.1
  unit: "%"
  interface_group: heat_production
  related_node: industry_chemicals_refineries_burner_coal
  position: 35
  slide_key: supply_fuel_fossil_refinery
- key: industry_final_demand_for_chemical_refineries_steam_hot_water_share
  share_group: chemical_refineries_heat
  step_value: 0.1
  unit: "%"
  interface_group: heat_production
  position: 40
  slide_key: supply_fuel_fossil_refinery
- key: industry_chemicals_refineries_burner_hydrogen_share
  share_group: chemical_refineries_heat
  step_value: 0.1
  unit: "%"
  interface_group: heat_production
  related_node: industry_chemicals_refineries_burner_hydrogen
  position: 45
  slide_key: supply_fuel_fossil_refinery  
- key: capacity_of_industry_chemicals_refineries_flexibility_p2h_electricity
  step_value: 1.0
  unit: MW
  interface_group: hybrid_heating
  related_node: industry_chemicals_refineries_flexibility_p2h_network_gas_electricity
  position: 50
  slide_key: supply_fuel_fossil_refinery
