---
- key: share_of_energy_chp_ultra_supercritical_ht_coal  
  share_group: chp_coal_heat
  step_value: 1.0
  unit: "%"
  interface_group: heat_allocation_coal_chp_pwd
  position: 100
  slide_key: supply_heat_overview_chp
- key: share_of_energy_chp_ultra_supercritical_mt_coal  
  share_group: chp_coal_heat
  step_value: 1.0
  unit: "%"
  interface_group: heat_allocation_coal_chp_pwd
  position: 110
  slide_key: supply_heat_overview_chp

- key: share_of_energy_chp_ultra_supercritical_cofiring_ht_coal  
  share_group: chp_cofiring_coal_heat
  step_value: 1.0
  unit: "%"
  interface_group: heat_allocation_coal_chp_pwd_cofiring
  position: 120
  slide_key: supply_heat_overview_chp
- key: share_of_energy_chp_ultra_supercritical_cofiring_mt_coal  
  share_group: chp_cofiring_coal_heat
  step_value: 1.0
  unit: "%"
  interface_group: heat_allocation_coal_chp_pwd_cofiring
  position: 130
  slide_key: supply_heat_overview_chp

- key: share_of_energy_chp_ultra_supercritical_ht_lignite  
  share_group: chp_lignite_heat
  step_value: 1.0
  unit: "%"
  interface_group: heat_allocation_lignite_chp
  position: 120
  dependent_on: has_lignite
  slide_key: supply_heat_overview_chp
- key: share_of_energy_chp_ultra_supercritical_mt_lignite  
  share_group: chp_lignite_heat
  step_value: 1.0
  unit: "%"
  interface_group: heat_allocation_lignite_chp
  position: 130
  dependent_on: has_lignite
  slide_key: supply_heat_overview_chp

- key: share_of_energy_chp_combined_cycle_ht_network_gas  
  share_group: chp_cc_network_gas_heat
  step_value: 1.0
  unit: "%"
  interface_group: heat_allocation_gas_chp_ccgt
  position: 200
  slide_key: supply_heat_overview_chp
- key: share_of_energy_chp_combined_cycle_mt_network_gas
  share_group: chp_cc_network_gas_heat
  step_value: 1.0
  unit: "%"
  interface_group: heat_allocation_gas_chp_ccgt
  position: 210
  slide_key: supply_heat_overview_chp

- key: share_of_energy_chp_local_engine_ht_network_gas
  share_group: chp_network_gas_heat
  step_value: 1.0
  unit: "%"
  interface_group: heat_allocation_gas_chp_engine
  position: 250
  slide_key: supply_heat_overview_chp
- key: share_of_energy_chp_local_engine_mt_network_gas
  share_group: chp_network_gas_heat
  step_value: 1.0
  unit: "%"
  interface_group: heat_allocation_gas_chp_engine
  position: 260
  slide_key: supply_heat_overview_chp

- key: share_of_energy_chp_local_ht_wood_pellets_must_run
  share_group: chp_wood_pellets_heat_must_run
  step_value: 1.0
  unit: "%"
  interface_group: heat_allocation_wood_pellets_chp_must_run
  position: 300
  slide_key: supply_heat_overview_chp
- key: share_of_energy_chp_local_mt_wood_pellets_must_run
  share_group: chp_wood_pellets_heat_must_run
  step_value: 1.0
  unit: "%"
  interface_group: heat_allocation_wood_pellets_chp_must_run
  position: 310
  slide_key: supply_heat_overview_chp

- key: share_of_energy_chp_local_ht_wood_pellets_dispatchable
  share_group: chp_wood_pellets_heat_dispatchable
  step_value: 1.0
  unit: "%"
  interface_group: heat_allocation_wood_pellets_chp_dispatchable
  position: 300
  slide_key: supply_heat_overview_chp
- key: share_of_energy_chp_local_mt_wood_pellets_dispatchable
  share_group: chp_wood_pellets_heat_dispatchable
  step_value: 1.0
  unit: "%"
  interface_group: heat_allocation_wood_pellets_chp_dispatchable
  position: 310
  slide_key: supply_heat_overview_chp

- key: share_of_energy_chp_local_engine_ht_biogas  
  share_group: chp_biogas_heat
  step_value: 1.0
  unit: "%"
  interface_group: heat_allocation_biogas_chp
  position: 350
  slide_key: supply_heat_overview_chp
- key: share_of_energy_chp_local_engine_mt_biogas  
  share_group: chp_biogas_heat
  step_value: 1.0
  unit: "%"
  interface_group: heat_allocation_biogas_chp
  position: 360
  slide_key: supply_heat_overview_chp

- key: share_of_energy_chp_supercritical_ht_waste_mix  
  share_group: chp_waste_heat
  step_value: 1.0
  unit: "%"
  interface_group: heat_allocation_waste_chp
  position: 400
  slide_key: supply_heat_overview_chp
- key: share_of_energy_chp_supercritical_mt_waste_mix  
  share_group: chp_waste_heat
  step_value: 1.0
  unit: "%"
  interface_group: heat_allocation_waste_chp
  position: 410
  slide_key: supply_heat_overview_chp
