---
- key: capacity_of_energy_heat_boiler_mt_electricity  
  step_value: 0.1
  unit: MW
  position: 4
  slide_key: sources_mt
- key: capacity_of_energy_heat_burner_mt_hydrogen  
  step_value: 0.1
  unit: MW
  position: 5
  slide_key: sources_mt
- key: capacity_of_energy_heat_heatpump_water_water_mt_electricity  
  step_value: 0.1
  unit: MW
  position: 3
  slide_key: sources_mt
- key: capacity_of_energy_heat_solar_mt_solar_thermal  
  step_value: 0.1
  unit: MW
  position: 1
  slide_key: sources_mt
- key: capacity_of_energy_heat_well_deep_mt_geothermal  
  step_value: 0.1
  unit: MW
  position: 2
  slide_key: sources_mt
- key: capacity_of_energy_heat_well_shallow_heatpump_mt_geothermal  
  step_value: 0.1
  unit: MW
  position: 2
  slide_key: sources_mt
- key: volume_of_mt_imported_heat  
  step_value: 0.1
  unit: PJ
  position: 11
  slide_key: sources_mt
- key: capacity_of_energy_heat_burner_mt_coal  
  step_value: 0.1
  unit: MW
  position: 10
  slide_key: sources_mt
- key: capacity_of_energy_heat_burner_mt_crude_oil  
  step_value: 0.1
  unit: MW
  position: 8
  slide_key: sources_mt
- key: capacity_of_energy_heat_burner_mt_network_gas  
  step_value: 0.1
  unit: MW
  position: 9
  slide_key: sources_mt
- key: capacity_of_energy_heat_burner_mt_waste_mix  
  step_value: 0.1
  unit: MW
  position: 7
  slide_key: sources_mt
- key: capacity_of_energy_heat_burner_mt_wood_pellets  
  step_value: 0.1
  unit: MW
  position: 6
  slide_key: sources_mt







