---
- key: capacity_of_energy_heat_burner_lt_wood_pellets  
  step_value: 0.1
  unit: MW
  position: 1
  slide_key: biomass_burner
- key: capacity_of_energy_heat_burner_mt_wood_pellets   
  step_value: 0.1
  unit: MW
  position: 1
  slide_key: biomass_burner
- key: capacity_of_energy_heat_burner_ht_wood_pellets
  step_value: 0.1
  unit: MW
  position: 1
  slide_key: biomass_burner
