---
- key: output_of_energy_production_fischer_tropsch
  step_value: 0.1
  unit: PJ
  position: 100
  slide_key: supply_fuel_production_overview
- key: output_of_energy_production_methanol_synthesis
  step_value: 0.1
  unit: PJ
  position: 110
  slide_key: supply_fuel_production_overview
- key: output_of_energy_production_pyrolysis_oil_fractionation_pyrolysis_oil
  step_value: 0.1
  unit: PJ
  position: 120
  slide_key: supply_fuel_production_overview
- key: output_of_energy_production_pyrolysis_oil_fractionation_bio_pyrolysis_oil
  step_value: 0.1
  unit: PJ
  position: 130
  slide_key: supply_fuel_production_overview
- key: output_of_energy_production_hvo_bio_kerosene
  step_value: 0.1
  unit: PJ
  position: 140
  slide_key: supply_fuel_production_overview
- key: output_of_energy_production_hvo_biodiesel
  step_value: 0.1
  unit: PJ
  position: 150
  slide_key: supply_fuel_production_overview
- key: output_of_energy_production_bio_ethanol
  step_value: 0.1
  unit: PJ
  position: 160
  slide_key: supply_fuel_production_overview
