---
- key: energy_heat_network_storage_ht_loss_share  
  step_value: 0.1
  unit: "%"
  position: 3
  slide_key: supply_heat_storage_ht
- key: energy_heat_network_storage_ht_steam_hot_water_output_capacity_share
  step_value: 0.1
  unit: "%"
  fixed: false
  position: 2
  slide_key: supply_heat_storage_ht
- key: heat_storage_enabled_ht
  step_value: 0.1
  unit: boolean
  position: 1
  slide_key: supply_heat_storage_ht

