---
- key: capacity_of_energy_heat_heatpump_water_water_lt_electricity
  step_value: 0.1
  unit: MW
  interface_group: hp_heat
  position: 1
  slide_key: e_boiler_hp
- key: capacity_of_energy_heat_heatpump_water_water_mt_electricity
  step_value: 0.1
  unit: MW
  interface_group: hp_heat
  position: 2
  slide_key: e_boiler_hp
- key: capacity_of_energy_heat_heatpump_water_water_ht_electricity
  step_value: 0.1
  unit: MW
  interface_group: hp_heat
  position: 3
  slide_key: e_boiler_hp
- key: capacity_of_energy_heat_boiler_lt_electricity
  step_value: 0.1
  unit: MW
  interface_group: e_bioler_heat
  position: 4
  slide_key: e_boiler_hp
- key: capacity_of_energy_heat_boiler_mt_electricity
  step_value: 0.1
  unit: MW
  interface_group: e_bioler_heat
  position: 5
  slide_key: e_boiler_hp
- key: capacity_of_energy_heat_boiler_ht_electricity
  step_value: 0.1
  unit: MW
  interface_group: e_bioler_heat
  position: 6
  slide_key: e_boiler_hp
