---
- key: demand_of_molecules_offshore_sequestration_co2
  step_value: 0.1
  unit: "Mton"
  interface_group: sequestration
  related_node: molecules_offshore_sequestration_co2
  position: 100
  slide_key: supply_ccus_utilisation_storage

- key: demand_of_molecules_other_utilisation_co2
  step_value: 0.1
  unit: "Mton"
  interface_group: utilisation
  position: 210
  slide_key: supply_ccus_utilisation_storage
