---
- key: fuel_production_coal
  step_value: 1.0
  unit: PJ
  position: 1
  slide_key: supply_fuel_extraction
- key: fuel_production_lignite
  step_value: 1.0
  unit: PJ
  dependent_on: has_lignite
  position: 2
  slide_key: supply_fuel_extraction
- key: fuel_production_crude_oil
  step_value: 1.0
  unit: PJ
  position: 3
  slide_key: supply_fuel_extraction
- key: fuel_production_natural_gas
  step_value: 1.0
  unit: PJ
  position: 4
  slide_key: supply_fuel_extraction
- key: fuel_production_uranium_oxide
  step_value: 1.0
  unit: PJ
  position: 5
  slide_key: supply_fuel_extraction
