---
- key: volume_of_imported_lt_heat
  step_value: 0.1
  unit: PJ
  position: 1
  slide_key: import_heat
- key: volume_of_imported_mt_heat
  step_value: 0.1
  unit: PJ
  position: 2
  slide_key: import_heat
- key: volume_of_imported_ht_heat
  step_value: 0.1
  unit: PJ
  position: 3
  slide_key: import_heat
- key: co2_emissions_of_imported_lt_heat
  step_value: 0.1
  unit: kg/GJ
  interface_group: import_heat_co2
  position: 4
  slide_key: import_heat
- key: co2_emissions_of_imported_mt_heat
  step_value: 0.1
  unit: kg/GJ
  interface_group: import_heat_co2
  position: 5
  slide_key: import_heat
- key: co2_emissions_of_imported_ht_heat
  step_value: 0.1
  unit: kg/GJ
  interface_group: import_heat_co2
  position: 6
  slide_key: import_heat