---
- key: share_of_industry_steel_captured_co2
  step_value: 1.0
  unit: "%"
  related_node: industry_steel_blastfurnace_bof_captured_co2
  interface_group: industry
  position: 5
  slide_key: supply_ccus_capture
- key: share_of_industry_chemicals_refineries_captured_co2
  step_value: 1.0
  unit: "%"
  related_node: industry_chemicals_refineries_captured_co2
  interface_group: industry
  position: 10
  slide_key: supply_ccus_capture
  dependent_on: true
- key: share_of_industry_chemicals_fertilizers_captured_processes_co2
  step_value: 1.0
  unit: "%"
  related_node: industry_chemicals_fertilizers_captured_processes_co2
  interface_group: industry
  dependent_on: has_detailed_chemical_industry
  position: 15
  slide_key: supply_ccus_capture
- key: share_of_industry_chemicals_fertilizers_captured_combustion_co2
  step_value: 1.0
  unit: "%"
  related_node: industry_chemicals_fertilizers_captured_combustion_co2
  interface_group: industry
  dependent_on: has_detailed_chemical_industry
  position: 20
  slide_key: supply_ccus_capture
- key: share_of_industry_chemical_other_captured_co2
  step_value: 1.0
  unit: "%"
  related_node: industry_chemical_other_captured_co2
  interface_group: industry
  position: 25
  slide_key: supply_ccus_capture
  dependent_on: _always_hidden
- key: share_of_industry_other_paper_captured_co2
  step_value: 1.0
  unit: "%"
  related_node: industry_other_paper_captured_co2
  interface_group: industry
  position: 30
  slide_key: supply_ccus_capture
- key: share_of_industry_other_food_captured_co2
  step_value: 1.0
  unit: "%"
  related_node: industry_other_food_captured_co2
  interface_group: industry
  position: 35
  slide_key: supply_ccus_capture


- key: share_of_energy_power_ultra_supercritical_ccs_coal
  step_value: 1.0
  unit: "%"
  interface_group: power_plants
  related_node: energy_power_ultra_supercritical_ccs_coal
  position: 100
  slide_key: supply_ccus_capture
- key: share_of_energy_power_combined_cycle_ccs_coal
  step_value: 1.0
  unit: "%"
  interface_group: power_plants
  related_node: energy_power_combined_cycle_ccs_coal
  position: 105
  slide_key: supply_ccus_capture
- key: share_of_energy_power_combined_cycle_ccs_network_gas
  step_value: 1.0
  unit: "%"
  interface_group: power_plants
  related_node: energy_power_combined_cycle_ccs_network_gas
  position: 110
  slide_key: supply_ccus_capture
- key: share_of_energy_power_ultra_supercritical_oxyfuel_ccs_lignite
  step_value: 1.0
  unit: "%"
  interface_group: power_plants
  related_node: energy_power_ultra_supercritical_oxyfuel_ccs_lignite
  position: 115
  dependent_on: has_lignite
  slide_key: supply_ccus_capture
- key: share_of_energy_chp_supercritical_ccs_ht_waste_mix
  step_value: 1.0
  unit: "%"
  related_node: energy_chp_supercritical_ccs_ht_waste_mix
  interface_group: power_plants
  position: 120
  slide_key: supply_ccus_capture
- key: share_of_energy_chp_supercritical_ccs_mt_waste_mix
  step_value: 1.0
  unit: "%"
  related_node: energy_chp_supercritical_ccs_mt_waste_mix
  interface_group: power_plants
  position: 125
  slide_key: supply_ccus_capture
- key: share_of_energy_power_supercritical_ccs_waste_mix
  step_value: 1.0
  unit: "%"
  related_node: energy_power_supercritical_ccs_waste_mix
  interface_group: power_plants
  position: 130
  slide_key: supply_ccus_capture
- key: share_of_energy_power_wood_pellets_ccs_must_run
  step_value: 1.0
  unit: "%"
  related_node: energy_power_wood_pellets_ccs_must_run
  interface_group: power_plants
  position: 135
  slide_key: supply_ccus_capture  
- key: share_of_energy_power_wood_pellets_ccs_dispatchable
  step_value: 1.0
  unit: "%"
  related_node: energy_power_wood_pellets_ccs_dispatchable
  interface_group: power_plants
  position: 137
  slide_key: supply_ccus_capture  
- key: share_of_energy_chp_local_mt_wood_pellets_ccs_must_run
  step_value: 1.0
  unit: "%"
  related_node: energy_chp_local_mt_wood_pellets_ccs_must_run
  interface_group: power_plants
  position: 150
  slide_key: supply_ccus_capture
- key: share_of_energy_chp_local_mt_wood_pellets_ccs_dispatchable
  step_value: 1.0
  unit: "%"
  related_node: energy_chp_local_mt_wood_pellets_ccs_dispatchable
  interface_group: power_plants
  position: 155
  slide_key: supply_ccus_capture
- key: share_of_energy_chp_local_ht_wood_pellets_ccs_must_run
  step_value: 1.0
  unit: "%"
  related_node: energy_chp_local_ht_wood_pellets_ccs_must_run
  interface_group: power_plants
  position: 160
  slide_key: supply_ccus_capture
- key: share_of_energy_chp_local_ht_wood_pellets_ccs_dispatchable
  step_value: 1.0
  unit: "%"
  related_node: energy_chp_local_ht_wood_pellets_ccs_dispatchable
  interface_group: power_plants
  position: 165
  slide_key: supply_ccus_capture

- key: flh_of_energy_power_wood_pellets_ccs_must_run
  step_value: 1.0
  unit: "#"
  interface_group: full_load_hours
  position: 180
  slide_key: supply_ccus_capture
- key: flh_of_energy_chp_local_mt_wood_pellets_ccs_must_run
  step_value: 1.0
  unit: "#"
  interface_group: full_load_hours
  position: 185
  slide_key: supply_ccus_capture
- key: flh_of_energy_chp_local_ht_wood_pellets_ccs_must_run
  step_value: 1.0
  unit: "#"
  interface_group: full_load_hours
  position: 190
  slide_key: supply_ccus_capture

- key: share_of_energy_hydrogen_steam_methane_reformer_ccs
  step_value: 1.0
  unit: "%"
  interface_group: hydrogen_plants
  related_node: energy_hydrogen_steam_methane_reformer_ccs  
  position: 200
  slide_key: supply_ccus_capture
- key: share_of_energy_hydrogen_autothermal_reformer_ccs
  step_value: 1.0
  unit: "%"
  interface_group: hydrogen_plants
  related_node: energy_hydrogen_autothermal_reformer_ccs
  position: 205
  slide_key: supply_ccus_capture
- key: share_of_energy_hydrogen_biomass_gasification_ccs
  step_value: 1.0
  unit: "%"
  interface_group: hydrogen_plants
  related_node: energy_hydrogen_biomass_gasification_ccs
  position: 210
  slide_key: supply_ccus_capture


- key: demand_of_molecules_direct_air_capture_co2
  step_value: 0.1
  unit: "Mton"
  related_node: molecules_direct_air_capture_co2
  interface_group: direct_air_capture
  position: 300
  slide_key: supply_ccus_capture
- key: volume_of_molecules_import_co2_baseload
  step_value: 0.1
  unit: "Mton"
  related_node: 
  interface_group: Import
  position: 400
  slide_key: supply_ccus_capture