---
- key: energy_production_pyrolysis_biogenic_waste_share
  share_group: bio_pyrolysis_oil
  related_node: energy_production_pyrolysis_biogenic_waste
  interface_group: pyrolysis_biogenic
  step_value: 0.1
  unit: "%"
  position: 100
  slide_key: supply_fuel_production_pyrolysis
- key: energy_production_pyrolysis_dry_biomass_share
  related_node: energy_production_pyrolysis_dry_biomass
  share_group: bio_pyrolysis_oil
  interface_group: pyrolysis_biogenic
  step_value: 0.1
  unit: "%"
  position: 110
  slide_key: supply_fuel_production_pyrolysis

- key: volume_of_baseload_import_pyrolysis_oil
  interface_group: pyrolysis_import
  step_value: 0.1
  unit: PJ
  position: 200
  slide_key: supply_fuel_production_pyrolysis
- key: volume_of_baseload_import_bio_pyrolysis_oil
  interface_group: pyrolysis_import
  step_value: 0.1
  unit: PJ
  position: 210
  slide_key: supply_fuel_production_pyrolysis
