---
- key: capacity_of_households_solar_pv_solar_radiation
<<<<<<< HEAD
  step_value: 1.0
=======
  step_value: 1
>>>>>>> 6de6702cc (Move household solar PV to renewable electricity and solar thermal collectors to households - space heating. Remove slide households - solar panels.)
  unit: MW
  related_node: households_solar_pv_solar_radiation
  position: 1
  slide_key: supply_electricity_renewable_solar_power
<<<<<<< HEAD
- key: capacity_of_buildings_solar_pv_solar_radiation
  step_value: 1.0
  unit: MW
  related_node: buildings_solar_pv_solar_radiation
  position: 2
  slide_key: supply_electricity_renewable_solar_power
=======
>>>>>>> 6de6702cc (Move household solar PV to renewable electricity and solar thermal collectors to households - space heating. Remove slide households - solar panels.)
- key: capacity_of_energy_power_solar_pv_solar_radiation
  step_value: 1.0
  unit: MW
  related_node: energy_power_solar_pv_solar_radiation
<<<<<<< HEAD
  position: 3
=======
  position: 2
  slide_key: supply_electricity_renewable_solar_power
- key: capacity_of_energy_power_solar_csp_solar_radiation
  step_value: 1.0
  unit: MW
  related_node: energy_power_solar_csp_solar_radiation
  position: 5
  dependent_on: has_solar_csp
>>>>>>> 6de6702cc (Move household solar PV to renewable electricity and solar thermal collectors to households - space heating. Remove slide households - solar panels.)
  slide_key: supply_electricity_renewable_solar_power
- key: capacity_of_energy_battery_solar_pv_solar_radiation
  step_value: 1.0
  unit: MW
  related_node: energy_battery_solar_pv_solar_radiation
  position: 4
  slide_key: supply_electricity_renewable_solar_power
- key: capacity_of_energy_power_solar_pv_offshore
  step_value: 1.0
  unit: MW
  related_node: energy_power_solar_pv_offshore
<<<<<<< HEAD
  position: 5
=======
  position: 3
>>>>>>> 6de6702cc (Move household solar PV to renewable electricity and solar thermal collectors to households - space heating. Remove slide households - solar panels.)
  dependent_on: has_offshore_solar
  slide_key: supply_electricity_renewable_solar_power
- key: capacity_of_energy_power_solar_csp_solar_radiation
  step_value: 1.0
  unit: MW
  related_node: energy_power_solar_csp_solar_radiation
  position: 6
  dependent_on: has_solar_csp
  slide_key: supply_electricity_renewable_solar_power
