---
- key: capacity_of_energy_heat_solar_mt_solar_thermal
  step_value: 1.0
  unit: MW
  interface_group: non_dispatchable_heat
  position: 100
  related_node: energy_heat_solar_mt_solar_thermal
  slide_key: supply_heat_sources_mt
- key: capacity_of_energy_heat_well_deep_mt_geothermal
  step_value: 1.0
  unit: MW
  interface_group: non_dispatchable_heat
  position: 105
  related_node: energy_heat_well_deep_mt_geothermal
  slide_key: supply_heat_sources_mt
- key: capacity_of_energy_heat_well_shallow_heatpump_mt_geothermal
  step_value: 1.0
  unit: MW
  interface_group: non_dispatchable_heat
  position: 110
  related_node: energy_heat_well_shallow_heatpump_mt_geothermal
  slide_key: supply_heat_sources_mt
- key: volume_of_mt_residual_heat
  step_value: 0.1
  unit: PJ
  interface_group: non_dispatchable_heat
  position: 115
  related_node: energy_heat_production_mt_residual_heat
  slide_key: supply_heat_sources_mt
- key: volume_of_mt_imported_heat
  step_value: 0.1
  interface_group: non_dispatchable_heat
  unit: PJ
  position: 120
  slide_key: supply_heat_sources_mt

- key: capacity_of_energy_heat_heatpump_water_water_mt_electricity
  step_value: 1.0
  unit: MW
  interface_group: dispatchable_heat
  position: 205
  related_node: energy_heat_heatpump_water_water_mt_electricity
  slide_key: supply_heat_sources_mt
- key: capacity_of_energy_heat_boiler_mt_electricity
  step_value: 1.0
  unit: MW
  interface_group: dispatchable_heat
  position: 210
  related_node: energy_heat_boiler_mt_electricity
  slide_key: supply_heat_sources_mt
- key: capacity_of_energy_heat_burner_mt_hydrogen
  step_value: 1.0
  unit: MW
  interface_group: dispatchable_heat
  position: 215
  related_node: energy_heat_burner_mt_hydrogen
  slide_key: supply_heat_sources_mt
- key: capacity_of_energy_heat_burner_mt_wood_pellets
  step_value: 1.0
  unit: MW
  interface_group: dispatchable_heat
  position: 220
  related_node: energy_heat_burner_mt_wood_pellets
  slide_key: supply_heat_sources_mt
- key: capacity_of_energy_heat_burner_mt_waste_mix
  step_value: 1.0
  unit: MW
  interface_group: dispatchable_heat
  position: 225
  related_node: energy_heat_burner_mt_waste_mix
  slide_key: supply_heat_sources_mt
- key: capacity_of_energy_heat_burner_mt_crude_oil
  step_value: 1.0
  unit: MW
  interface_group: dispatchable_heat
  dependent_on: has_coal_oil_for_heating_built_environment
  position: 230
  related_node: energy_heat_burner_mt_crude_oil
  slide_key: supply_heat_sources_mt
- key: capacity_of_energy_heat_burner_mt_network_gas
  step_value: 1.0
  unit: MW
  interface_group: dispatchable_heat
  position: 235
  related_node: energy_heat_burner_mt_network_gas
  slide_key: supply_heat_sources_mt
- key: capacity_of_energy_heat_burner_mt_coal
  step_value: 1.0
  unit: MW
  interface_group: dispatchable_heat
  dependent_on: has_coal_oil_for_heating_built_environment
  position: 240
  related_node: energy_heat_burner_mt_coal
  slide_key: supply_heat_sources_mt
- key: capacity_of_energy_heat_heatpump_surface_water_water_ts_mt_electricity
  step_value: 1.0
  unit: MW
  interface_group: dispatchable_heat
  position: 245
  slide_key: supply_heat_sources_mt
- key: capacity_of_energy_heat_heatpump_waste_water_water_ts_mt_electricity
  step_value: 1.0
  unit: MW
  interface_group: dispatchable_heat
  position: 250
  slide_key: supply_heat_sources_mt
- key: capacity_of_energy_heat_heatpump_drink_water_water_ts_mt_electricity
  step_value: 1.0
  unit: MW
  interface_group: dispatchable_heat
  position: 255
  slide_key: supply_heat_sources_mt


