---
- key: energy_heat_network_storage_mt_loss_share  
  step_value: 0.1
  unit: "%"
  position: 3
  slide_key: supply_heat_storage_mt
- key: energy_heat_network_storage_mt_steam_hot_water_output_capacity_share
  step_value: 0.1
  unit: "%"
  fixed: false
  position: 2
  slide_key: supply_heat_storage_mt
- key: heat_storage_enabled_mt
  step_value: 0.1
  unit: boolean
  position: 1
  slide_key: supply_heat_storage_mt
