---
- key: capacity_of_energy_heat_lt_solar_thermal
  step_value: 0.1
  unit: MW
  position: 1
  slide_key: solar_thermal
- key: capacity_of_energy_heat_mt_solar_thermal
  step_value: 0.1
  unit: MW
  position: 2
  slide_key: solar_thermal
