---
- key: capacity_of_energy_heat_well_lt_shallow_geothermal
  step_value: 0.1
  unit: MW
  interface_group: shallow_geothermal_heat
  position: 1
  slide_key: geothermal_heat
- key: capacity_of_energy_heat_well_mt_shallow_geothermal
  step_value: 0.1
  unit: MW
  interface_group: shallow_geothermal_heat
  position: 2
  slide_key: geothermal_heat
- key: capacity_of_energy_heat_well_lt_deep_geothermal
  step_value: 0.1
  unit: MW
  interface_group: geothermal_heat
  position: 3
  slide_key: geothermal_heat
- key: capacity_of_energy_heat_well_mt_deep_geothermal
  step_value: 0.1
  unit: MW
  interface_group: geothermal_heat
  position: 4
  slide_key: geothermal_heat
- key: capacity_of_energy_heat_well_ht_deep_geothermal
  step_value: 0.1
  unit: MW
  interface_group: geothermal_heat
  position: 5
  slide_key: geothermal_heat
