---
- key: capacity_of_energy_heat_burner_lt_network_gas
  step_value: 0.1
  unit: MW
  position: 1
  slide_key: network_gas_burner
- key: capacity_of_energy_heat_burner_mt_network_gas
  step_value: 0.1
  unit: MW
  position: 2
  slide_key: network_gas_burner
- key: capacity_of_energy_heat_burner_ht_network_gas
  step_value: 0.1
  unit: MW
  position: 3
  slide_key: network_gas_burner
