---

- key: demand_of_molecules_direct_air_capture_co2
  step_value: 0.1
  unit: "Mton"
  related_node: molecules_direct_air_capture_co2
  interface_group: direct_air_capture
  position: 5
  slide_key: supply_ccus_capture_energy
- key: share_of_energy_power_ultra_supercritical_ccs_coal
  step_value: 1.0
  unit: "%"
  interface_group: power_plants
  related_node: energy_power_ultra_supercritical_ccs_coal
  position: 100
  slide_key: supply_ccus_capture_energy
- key: share_of_energy_power_combined_cycle_ccs_coal
  step_value: 1.0
  unit: "%"
  interface_group: power_plants
  related_node: energy_power_combined_cycle_ccs_coal
  position: 105
  slide_key: supply_ccus_capture_energy
- key: share_of_energy_power_combined_cycle_ccs_network_gas
  step_value: 1.0
  unit: "%"
  interface_group: power_plants
  related_node: energy_power_combined_cycle_ccs_network_gas
  position: 110
  slide_key: supply_ccus_capture_energy
- key: share_of_energy_power_ultra_supercritical_oxyfuel_ccs_lignite
  step_value: 1.0
  unit: "%"
  interface_group: power_plants
  related_node: energy_power_ultra_supercritical_oxyfuel_ccs_lignite
  position: 115
  dependent_on: has_lignite
  slide_key: supply_ccus_capture_energy
- key: share_of_energy_chp_supercritical_ccs_ht_waste_mix
  step_value: 1.0
  unit: "%"
  related_node: energy_chp_supercritical_ccs_ht_waste_mix
  interface_group: power_plants
  position: 120
  slide_key: supply_ccus_capture_energy
- key: share_of_energy_chp_supercritical_ccs_mt_waste_mix
  step_value: 1.0
  unit: "%"
  related_node: energy_chp_supercritical_ccs_mt_waste_mix
  interface_group: power_plants
  position: 125
  slide_key: supply_ccus_capture_energy
- key: share_of_energy_power_supercritical_ccs_waste_mix
  step_value: 1.0
  unit: "%"
  related_node: energy_power_supercritical_ccs_waste_mix
  interface_group: power_plants
  position: 130
  slide_key: supply_ccus_capture_energy
- key: share_of_energy_power_wood_pellets_ccs_must_run
  step_value: 1.0
  unit: "%"
  related_node: energy_power_wood_pellets_ccs_must_run
  interface_group: power_plants_beccus
  position: 135
  slide_key: supply_ccus_capture_energy  
- key: share_of_energy_power_wood_pellets_ccs_dispatchable
  step_value: 1.0
  unit: "%"
  related_node: energy_power_wood_pellets_ccs_dispatchable
  interface_group: power_plants_beccus
  position: 137
  slide_key: supply_ccus_capture_energy  
- key: share_of_energy_chp_local_mt_wood_pellets_ccs_must_run
  step_value: 1.0
  unit: "%"
  related_node: energy_chp_local_mt_wood_pellets_ccs_must_run
  interface_group: power_plants_beccus
  position: 150
  slide_key: supply_ccus_capture_energy
- key: share_of_energy_chp_local_mt_wood_pellets_ccs_dispatchable
  step_value: 1.0
  unit: "%"
  related_node: energy_chp_local_mt_wood_pellets_ccs_dispatchable
  interface_group: power_plants_beccus
  position: 155
  slide_key: supply_ccus_capture_energy
- key: share_of_energy_chp_local_ht_wood_pellets_ccs_must_run
  step_value: 1.0
  unit: "%"
  related_node: energy_chp_local_ht_wood_pellets_ccs_must_run
  interface_group: power_plants_beccus
  position: 160
  slide_key: supply_ccus_capture_energy
- key: share_of_energy_chp_local_ht_wood_pellets_ccs_dispatchable
  step_value: 1.0
  unit: "%"
  related_node: energy_chp_local_ht_wood_pellets_ccs_dispatchable
  interface_group: power_plants_beccus
  position: 165
  slide_key: supply_ccus_capture_energy



