---
- key: capacity_of_energy_chp_local_wood_pellets
  step_value: 0.1
  unit: MW
  related_node: energy_chp_local_wood_pellets
  position: 5
  slide_key: supply_electricity_renewable_biomass_plants  
 
- key: capacity_of_energy_power_wood_pellets
  step_value: 0.1
  unit: MW
  related_node: energy_power_wood_pellets
  position: 10
  slide_key: supply_electricity_renewable_biomass_plants

- key: capacity_of_energy_chp_local_engine_biogas
  step_value: 0.1
  unit: MW
  related_node: energy_chp_local_engine_biogas
  position: 15
  slide_key: supply_electricity_renewable_biomass_plants

