---
- key: share_of_industry_chemicals_other_reused_residual_heat
  step_value: 1.0
  unit: "%"
  interface_group: residual_heat
  position: 3
  slide_key: supply_heat_overview_residual
- key: share_of_industry_chemicals_fertilizers_reused_residual_heat
  step_value: 1.0
  unit: "%"
  interface_group: residual_heat
  position: 3
  slide_key: supply_heat_overview_residual
- key: share_of_industry_chemicals_refineries_reused_residual_heat
  step_value: 1.0
  unit: "%"
  interface_group: residual_heat
  position: 3
  slide_key: supply_heat_overview_residual
- key: share_of_industry_other_ict_reused_residual_heat
  step_value: 1.0
  unit: "%"
  interface_group: residual_heat
  position: 3
  slide_key: supply_heat_overview_residual
