api_url: https://tyndp2026.engine.energytransitionmodel.com
converter_detail_url: https://tyndp2026.engine.energytransitionmodel.com/converters
esdl_api_url: https://esdl.energytransitionmodel.com/api/v1/
gquery_detail_url: https://tyndp2026.engine.energytransitionmodel.com/data/latest/gqueries/
live_server: production
multi_year_charts_url: https://myc.energytransitionmodel.com
partners_url: https://tyndp2026.energytransitionmodel.com

identity:
  client_uri: https://tyndp2026.energytransitionmodel.com
