ete_url: https://engine.energytransitionmodel.com
converter_detail_url: https://engine.energytransitionmodel.com/converters
esdl_ete_url: https://esdl.energytransitionmodel.com/api/v1/
gquery_detail_url: https://engine.energytransitionmodel.com/data/latest/gqueries/
live_server: production
collections_url: https://myc.energytransitionmodel.com
partners_url: https://energytransitionmodel.com

identity:
  client_uri: https://energytransitionmodel.com
