ete_url: https://beta.engine.energytransitionmodel.com
converter_detail_url: http://beta.et-engine.com/converters
esdl_ete_url: http://beta-esdl.energytransitionmodel.com/api/v1/
gquery_detail_url: http://beta.et-engine.com/data/latest/gqueries/
live_server: staging
multi_year_charts_url: https://myc-beta.energytransitionmodel.com
partners_url: https://beta.energytransitionmodel.com

identity:
  client_uri: https://beta.energytransitionmodel.com
